using System.Text.Json;

namespace Win32Emu.Tools.ApiStatusGenerator;

/// <summary>
/// Exports API status metadata generated by source generators to JSON files.
/// The API metadata is generated at compile-time by the ApiStatusGenerator and Win16ApiStatusGenerator source generators.
/// </summary>
class Program
{
	static void Main(string[] args)
	{
		Console.WriteLine("Win32Emu API Status Exporter");
		Console.WriteLine("=============================");
		Console.WriteLine();

		if (args.Length < 1)
		{
			Console.WriteLine("Usage: Win32Emu.Tools.ApiStatusGenerator <output-directory>");
			Console.WriteLine();
			Console.WriteLine("Example:");
			Console.WriteLine("  Win32Emu.Tools.ApiStatusGenerator docs/pages");
			Console.WriteLine();
			Console.WriteLine("This will generate:");
			Console.WriteLine("  - api-status.json (Win32 modules)");
			Console.WriteLine("  - win16-api-status.json (Win16 modules)");
			Console.WriteLine();
			Console.WriteLine("Note: This tool exports the API status metadata that is generated");
			Console.WriteLine("      at compile-time by the source generators.");
			return;
		}

		var outputDir = args[0];
		
		if (!Directory.Exists(outputDir))
		{
			Directory.CreateDirectory(outputDir);
		}

		// Export Win32 API status
		ExportWin32ApiStatus(outputDir);
		
		// Export Win16 API status
		ExportWin16ApiStatus(outputDir);
	}

	static void ExportWin32ApiStatus(string outputDir)
	{
		Console.WriteLine("Exporting Win32 API status...");
		
		var outputPath = Path.Combine(outputDir, "api-status.json");
		
		// Get the JSON from the generated metadata class
		var json = Win32Emu.Win32.ApiStatusMetadata.Json;
		
		// Parse to get statistics for display
		using var doc = JsonDocument.Parse(json);
		var root = doc.RootElement;
		var modules = root.GetProperty("modules");
		var moduleCount = modules.GetArrayLength();
		
		var totalFunctions = 0;
		var stubFunctions = 0;
		
		foreach (var module in modules.EnumerateArray())
		{
			var functions = module.GetProperty("functions");
			totalFunctions += functions.GetArrayLength();
			stubFunctions += functions.EnumerateArray()
				.Count(function => function.GetProperty("isStub").GetBoolean());
		}
		
		File.WriteAllText(outputPath, json);
		
		Console.WriteLine($"  Output: {outputPath}");
		Console.WriteLine($"  Modules: {moduleCount}");
		Console.WriteLine($"  Functions: {totalFunctions}");
		Console.WriteLine($"  Stubs: {stubFunctions}");
		Console.WriteLine($"  Implementation rate: {((totalFunctions - stubFunctions) * 100.0 / totalFunctions):F1}%");
		Console.WriteLine();
	}

	static void ExportWin16ApiStatus(string outputDir)
	{
		Console.WriteLine("Exporting Win16 API status...");
		
		var outputPath = Path.Combine(outputDir, "win16-api-status.json");
		
		// Get the JSON from the generated metadata class
		var json = Win32Emu.Win32.Win16ApiStatusMetadata.Json;
		
		// Parse to get statistics for display
		using var doc = JsonDocument.Parse(json);
		var root = doc.RootElement;
		var modules = root.GetProperty("modules");
		var moduleCount = modules.GetArrayLength();
		
		var totalFunctions = modules.EnumerateArray()
			.Select(module => module.GetProperty("functions").GetArrayLength())
			.Sum();
		
		File.WriteAllText(outputPath, json);
		
		Console.WriteLine($"  Output: {outputPath}");
		Console.WriteLine($"  Modules: {moduleCount}");
		Console.WriteLine($"  Functions: {totalFunctions}");
		Console.WriteLine();
	}
}
