using System.Text.Json;

namespace Win32Emu.Tools.ApiStatusGenerator;

/// <summary>
/// Exports API status metadata generated by source generators to JSON file.
/// The API metadata is generated at compile-time by the ApiStatusGenerator source generator.
/// </summary>
class Program
{
	static void Main(string[] args)
	{
		Console.WriteLine("Win32Emu API Status Exporter");
		Console.WriteLine("=============================");
		Console.WriteLine();

		if (args.Length < 1)
		{
			Console.WriteLine("Usage: Win32Emu.Tools.ApiStatusGenerator <output-json-path>");
			Console.WriteLine();
			Console.WriteLine("Example:");
			Console.WriteLine("  Win32Emu.Tools.ApiStatusGenerator docs/pages/api-status.json");
			Console.WriteLine();
			Console.WriteLine("Note: This tool exports the API status metadata that is generated");
			Console.WriteLine("      at compile-time by the ApiStatusGenerator source generator.");
			return;
		}

		var outputPath = args[0];

		var outputDir = Path.GetDirectoryName(outputPath);
		if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
		{
			Directory.CreateDirectory(outputDir);
		}

		// Get the JSON from the generated metadata class
		var json = Win32Emu.Win32.ApiStatusMetadata.Json;
		
		// Parse to get statistics for display
		using var doc = JsonDocument.Parse(json);
		var root = doc.RootElement;
		var modules = root.GetProperty("modules");
		var moduleCount = modules.GetArrayLength();
		
		var totalFunctions = 0;
		var stubFunctions = 0;
		
		foreach (var module in modules.EnumerateArray())
		{
			var functions = module.GetProperty("functions");
			totalFunctions += functions.GetArrayLength();
			stubFunctions += functions.EnumerateArray()
				.Count(function => function.GetProperty("isStub").GetBoolean());
		}
		
		File.WriteAllText(outputPath, json);
		
		Console.WriteLine();
		Console.WriteLine($"Exported API status data: {outputPath}");
		Console.WriteLine($"Total modules: {moduleCount}");
		Console.WriteLine($"Total functions: {totalFunctions}");
		Console.WriteLine($"Stub functions: {stubFunctions}");
		Console.WriteLine($"Implementation rate: {((totalFunctions - stubFunctions) * 100.0 / totalFunctions):F1}%");
	}
}
