<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ErrorReport>send</ErrorReport>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsmResolver.PE" Version="6.0.0-beta.4" />
    <PackageReference Include="AsmResolver.PE.Win32Resources" Version="6.0.0-beta.4" />
    <PackageReference Include="DiscUtils.Core" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Fat" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Iso9660" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Vhd" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Vhdx" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Vmdk" Version="0.16.13" />
    <PackageReference Include="Iced" Version="1.21.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.10" />
    <PackageReference Include="OpenTelemetry" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.13.0" />
    <PackageReference Include="SDL3-CS" Version="3.3.2.1" />
    <PackageReference Include="SharpMetal" Version="1.0.0" />
    <PackageReference Include="Silk.NET.GLFW" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenAL" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.22.0" />
    <PackageReference Include="System.Threading.Channels" Version="9.0.10" />
    <PackageReference Include="UnicornEngine.Unicorn" Version="2.1.4-a40db6c" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Win32Emu.Generators\Win32Emu.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Win32Emu.Rtl\Win32Emu.Rtl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Examples\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Win32Emu.Tests.Kernel32" />
    <InternalsVisibleTo Include="Win32Emu.Tests.User32" />
    <InternalsVisibleTo Include="Win32Emu.Tests.Emulator" />
    <InternalsVisibleTo Include="Win32Emu.Tests.Gui" />
    <InternalsVisibleTo Include="Win32Emu.Tests.CodeGen" />
  </ItemGroup>

</Project>
