/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int __cdecl sub_401000(CHAR *lpString, LPCSTR lpString2);
HWND __cdecl sub_401050(HWND hDlg, int nIDDlgItem, LPCSTR name, int a4, int cy);
BOOL sub_4010B0(HWND hDlg, LPCSTR a2, ...);
HRESULT __cdecl sub_4010F0(void *a1);
INT_PTR __stdcall DialogFunc(HWND hWnd, UINT a2, WPARAM a3, LPARAM a4); // idb
BOOL __cdecl sub_4022C0(HWND hDlg, int nIDDlgItem, BOOL bEnable);
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
int __cdecl sub_402360(int a1, LPCCH lpMultiByteStr, int a3, int a4); // idb
// int __stdcall DirectXSetupA(_DWORD, _DWORD, _DWORD); weak
// void __cdecl __noreturn exit(int Code);
// int sprintf(char *const Buffer, const char *const Format, ...);
// int __cdecl atoi(const char *String);
// char *__cdecl strstr(const char *Str, const char *SubStr);
// char *__cdecl _strupr(char *String);

//-------------------------------------------------------------------------
// Data declarations

const IID rclsid = { 136193u, 0u, 0u, { 192u, 0u, 0u, 0u, 0u, 0u, 0u, 70u } }; // idb
const IID riid = { 136430u, 0u, 0u, { 192u, 0u, 0u, 0u, 0u, 0u, 0u, 70u } }; // idb
_UNKNOWN unk_407360; // weak
int dword_40A048 = 0; // weak
char *off_40A050[294] =
{
  "Ign_win.exe",
  "remove.exe",
  "readme.txt",
  "H_pan1.pic",
  "H_pan2.pic",
  "H_signs.pic",
  "N_pangfx.pic",
  "N_Signs.pic",
  "N_sysgfx.pic",
  "N_sysg_2.pic",
  "S_pangfx.pic",
  "S_Signs.pic",
  "Pokal.pic",
  "menubkg.dat",
  "sys.col",
  "xruds137.exe",
  "Ghosts\\readme.txt",
  "Baltazar\\data\\demotrk.pic",
  "Baltazar\\data\\democar.pic",
  "Baltazar\\data\\Menu.tab",
  "Baltazar\\data\\Menu.col",
  "Baltazar\\data\\MARK.PIC",
  "Baltazar\\data\\bilar.pic",
  "Baltazar\\data\\Trk_spr.pic",
  "Baltazar\\data\\bluedark.lft",
  "Baltazar\\data\\bluegrey.lft",
  "Baltazar\\data\\bluelite.lft",
  "Baltazar\\data\\red_dark.lft",
  "Baltazar\\data\\red_grey.lft",
  "Baltazar\\data\\red_lite.lft",
  "Baltazar\\data\\Menucar.plc",
  "Baltazar\\data\\Menucar.msh",
  "Baltazar\\data\\Menucar.tex",
  "Baltazar\\data\\Conspr.pic",
  "Baltazar\\data\\Car_sel.pic",
  "Baltazar\\data\\Ign_logo.pic",
  "Baltazar\\data\\flaggor.pic",
  "Baltazar\\data\\Default.psq",
  "Baltazar\\data\\Ign1.cdp",
  "Baltazar\\data\\Ign2.cdp",
  "Baltazar\\data\\Ign3_0.cdp",
  "Baltazar\\data\\Ign3_1.cdp",
  "Baltazar\\data\\Ign3_2.cdp",
  "Baltazar\\data\\Ign3_3.cdp",
  "Baltazar\\data\\test.pfm",
  "Baltazar\\data\\textures\\boom.tex",
  "Baltazar\\data\\textures\\canada.tex",
  "Baltazar\\data\\textures\\cars.tex",
  "Baltazar\\data\\textures\\darksmok.tex",
  "Baltazar\\data\\textures\\divspr.tex",
  "Baltazar\\data\\textures\\exsmoke.tex",
  "Baltazar\\data\\textures\\light.tex",
  "Baltazar\\data\\textures\\smoke.tex",
  "Baltazar\\data\\Sound\\0_grp0\\0_sel.wav",
  "Baltazar\\data\\Sound\\0_grp0\\1_flip.wav",
  "Baltazar\\data\\Sound\\0_grp0\\2_no.wav",
  "Baltazar\\data\\Sound\\0_grp0\\3_intro.wav",
  "CARS\\TEST.AIS",
  "CARS\\Cars.msh",
  "CARS\\Cars.tex",
  "CARS\\Cars.plc",
  "CARS\\COOPER\\SOUND\\01_a.wav",
  "CARS\\COOPER\\SOUND\\ENGINE.INF",
  "CARS\\COOPER\\SOUND\\00_a.wav",
  "CARS\\Cop\\SOUND\\01_a.pat",
  "CARS\\Cop\\SOUND\\ENGINE.INF",
  "CARS\\Cop\\SOUND\\00_a.pat",
  "CARS\\Dodge\\SOUND\\01_a.wav",
  "CARS\\Dodge\\SOUND\\ENGINE.INF",
  "CARS\\Dodge\\SOUND\\00_a.wav",
  "CARS\\JEEP\\SOUND\\01_a.pat",
  "CARS\\JEEP\\SOUND\\ENGINE.INF",
  "CARS\\JEEP\\SOUND\\00_a.pat",
  "CARS\\Mustang\\SOUND\\01_a.wav",
  "CARS\\Mustang\\SOUND\\ENGINE.INF",
  "CARS\\Mustang\\SOUND\\00_a.wav",
  "CARS\\Nascar\\SOUND\\01_a.wav",
  "CARS\\Nascar\\SOUND\\ENGINE.INF",
  "CARS\\Nascar\\SOUND\\00_a.wav",
  "CARS\\PORSCHE\\SOUND\\00_a.wav",
  "CARS\\PORSCHE\\SOUND\\01_a.wav",
  "CARS\\PORSCHE\\SOUND\\ENGINE.INF",
  "CARS\\School\\SOUND\\01_a.pat",
  "CARS\\School\\SOUND\\ENGINE.INF",
  "CARS\\School\\SOUND\\00_a.pat",
  "CARS\\Truck\\SOUND\\01_a.pat",
  "CARS\\Truck\\SOUND\\ENGINE.INF",
  "CARS\\Truck\\SOUND\\00_a.pat",
  "CARS\\Van\\SOUND\\01_a.pat",
  "CARS\\Van\\SOUND\\ENGINE.INF",
  "CARS\\Van\\SOUND\\00_a.pat",
  "CARS\\VW\\SOUND\\01_a.wav",
  "CARS\\VW\\SOUND\\ENGINE.INF",
  "CARS\\VW\\SOUND\\00_a.wav",
  "fonts\\IGNITION.FNT",
  "fonts\\YELLOW.LFT",
  "fonts\\POS.LFT",
  "fonts\\SPEED.LFT",
  "fonts\\YELLOW_S.LFT",
  "fonts\\YELLOW_H.LFT",
  "fonts\\POS_S.LFT",
  "fonts\\POS_H.LFT",
  "fonts\\SPEED_S.LFT",
  "fonts\\SPEED_H.LFT",
  "fonts\\RESULT.LFT",
  "fonts\\mini.LFT",
  "fonts\\small.LFT",
  "GENERAL\\SMOKE.TEX",
  "GENERAL\\DARKSMOK.TEX",
  "GENERAL\\LIGHT.TEX",
  "GENERAL\\BOOM.TEX",
  "GENERAL\\DIVSPR.TEX",
  "GENERAL\\EXSMOKE.TEX",
  "GENERAL\\SOUND\\Boost\\00_boost.wav",
  "GENERAL\\SOUND\\Boost\\01_klick.wav",
  "GENERAL\\SOUND\\Boost\\02_ok.wav",
  "GENERAL\\SOUND\\Boost\\03_siren.pat",
  "GENERAL\\SOUND\\Boost\\04_honk.wav",
  "GENERAL\\SOUND\\Boost\\05_cool.wav",
  "GENERAL\\SOUND\\Boost\\06_jeep.wav",
  "GENERAL\\SOUND\\Boost\\07_cop.pat",
  "GENERAL\\SOUND\\Boost\\08_cruis.wav",
  "GENERAL\\SOUND\\Boost\\09_schoo.wav",
  "GENERAL\\SOUND\\Boost\\10_monst.wav",
  "GENERAL\\SOUND\\Boost\\11_bug.wav",
  "GENERAL\\SOUND\\Boost\\12_truck.wav",
  "GENERAL\\SOUND\\Boost\\13_bad.wav",
  "GENERAL\\SOUND\\Boost\\14_doggi.wav",
  "GENERAL\\SOUND\\COLL\\00_me_me.pat",
  "GENERAL\\SOUND\\COLL\\01_ME_JO.XI",
  "GENERAL\\SOUND\\COLL\\02_gniss.pat",
  "GENERAL\\SOUND\\COLL\\03_duns.pat",
  "GENERAL\\SOUND\\COLL\\04_EXPLO.wav",
  "GENERAL\\SOUND\\COLL\\05_wadea.pat",
  "GENERAL\\SOUND\\COLL\\06_mos.wav",
  "GENERAL\\SOUND\\COLL\\07_omos.wav",
  "GENERAL\\SOUND\\COLL\\08_tinye.wav",
  "GENERAL\\SOUND\\COLL\\09_landa.wav",
  "GENERAL\\SOUND\\Div\\00_redye.pat",
  "GENERAL\\SOUND\\Div\\01_green.pat",
  "GENERAL\\SOUND\\Div\\02_gear.pat",
  "GENERAL\\SOUND\\Div\\03_Start.wav",
  "GENERAL\\SOUND\\Div\\04_ghost.wav",
  "GENERAL\\SOUND\\Div\\05_swosh.wav",
  "GENERAL\\SOUND\\ROLL\\00_R_ASF.XI",
  "GENERAL\\SOUND\\ROLL\\01_R_GRA.XI",
  "GENERAL\\SOUND\\ROLL\\04_r_sno.xi",
  "GENERAL\\SOUND\\ROLL\\02_r_mud.xi",
  "GENERAL\\SOUND\\ROLL\\03_r_san.xi",
  "GENERAL\\SOUND\\SKID\\00_S_ASF.XI",
  "GENERAL\\SOUND\\SKID\\02_s_mud.xi",
  "GENERAL\\SOUND\\SKID\\01_s_gra.pat",
  "GENERAL\\SOUND\\SKID\\03_s_san.pat",
  "GENERAL\\SOUND\\SKID\\04_s_sno.pat",
  "LEVELS\\Austria\\AUSTRIA.PLC",
  "LEVELS\\Austria\\AUSTRIA.MSH",
  "LEVELS\\Austria\\AUSTRIA.COL",
  "LEVELS\\Austria\\AUSTRIA.POS",
  "LEVELS\\Austria\\AUSTRIA.TEX",
  "LEVELS\\Austria\\Austria.tab",
  "LEVELS\\Austria\\AUSTRIA.PIC",
  "LEVELS\\Austria\\Austria.pan",
  "LEVELS\\Austria\\AUSTRIA.TRI",
  "LEVELS\\Austria\\AUSTRIA.SRF",
  "LEVELS\\Austria\\austria.shd",
  "LEVELS\\Austria\\Sound\\00_lavin.wav",
  "LEVELS\\Austria\\Sound\\01_Klock.pat",
  "LEVELS\\Austria\\Sound\\02_Wind.wav",
  "LEVELS\\Austria\\Sound\\03_Kano.pat",
  "LEVELS\\Austria\\Sound\\04_Lift.pat",
  "LEVELS\\Austria\\Sound\\05_jodel.wav",
  "LEVELS\\Austria\\Sound\\06_bells.pat",
  "LEVELS\\Austria\\Sound\\07_stenm.pat",
  "LEVELS\\Brazil\\Brazil.plc",
  "LEVELS\\Brazil\\Brazil.msh",
  "LEVELS\\Brazil\\brazil.shd",
  "LEVELS\\Brazil\\Brazil.col",
  "LEVELS\\Brazil\\Brazil.pos",
  "LEVELS\\Brazil\\BRAZIL.PIC",
  "LEVELS\\Brazil\\BRAZIL.TAB",
  "LEVELS\\Brazil\\Brazil.srf",
  "LEVELS\\Brazil\\Brazil.pan",
  "LEVELS\\Brazil\\Brazil.tex",
  "LEVELS\\Brazil\\brazil.tri",
  "LEVELS\\Brazil\\Sound\\00_Djung.wav",
  "LEVELS\\Brazil\\Sound\\01_Djung.wav",
  "LEVELS\\Brazil\\Sound\\02_Djung.wav",
  "LEVELS\\Brazil\\Sound\\03_Djung.wav",
  "LEVELS\\Brazil\\Sound\\04_Djung.wav",
  "LEVELS\\Brazil\\Sound\\05_Djung.wav",
  "LEVELS\\Brazil\\Sound\\06_tribe.wav",
  "LEVELS\\Brazil\\Sound\\07_fors.pat",
  "LEVELS\\Canada\\CANADA.PIC",
  "LEVELS\\Canada\\Canada.plc",
  "LEVELS\\Canada\\CANADA.TRI",
  "LEVELS\\Canada\\CANADA.SRF",
  "LEVELS\\Canada\\Canada.tab",
  "LEVELS\\Canada\\CANADA.COL",
  "LEVELS\\Canada\\CANADA.MSH",
  "LEVELS\\Canada\\CANADA.POS",
  "LEVELS\\Canada\\CANADA.TEX",
  "LEVELS\\Canada\\Canada.pan",
  "LEVELS\\Canada\\canada.shd",
  "LEVELS\\Canada\\Sound\\00_rain.wav",
  "LEVELS\\Canada\\Sound\\01_thund.pat",
  "LEVELS\\Canada\\Sound\\02_light.pat",
  "LEVELS\\Canada\\Sound\\03_train.wav",
  "LEVELS\\Canada\\Sound\\04_water.pat",
  "LEVELS\\Canada\\Sound\\06_trakt.pat",
  "LEVELS\\Canada\\Sound\\07_bell.wav",
  "LEVELS\\Canada\\Sound\\08_farm.wav",
  "LEVELS\\Canada\\Sound\\09_for.wav",
  "LEVELS\\Canada\\Sound\\10_for.wav",
  "LEVELS\\Canada\\Sound\\11_for.wav",
  "LEVELS\\Canada\\Sound\\12_for.wav",
  "LEVELS\\Canada\\Sound\\13_fact.wav",
  "LEVELS\\Carib\\CARIB.TRI",
  "LEVELS\\Carib\\CARIB.SRF",
  "LEVELS\\Carib\\CARIB.TEX",
  "LEVELS\\Carib\\Carib.pan",
  "LEVELS\\Carib\\CARIB.TAB",
  "LEVELS\\Carib\\CARIB.COL",
  "LEVELS\\Carib\\Carib.plc",
  "LEVELS\\Carib\\Carib.pos",
  "LEVELS\\Carib\\Carib.msh",
  "LEVELS\\Carib\\CARIB.PIC",
  "LEVELS\\Carib\\carib.shd",
  "LEVELS\\Carib\\SOUND\\00_wave.wav",
  "LEVELS\\Carib\\SOUND\\01_samba.wav",
  "LEVELS\\Carib\\SOUND\\02_wave.wav",
  "LEVELS\\Carib\\SOUND\\03_wave.wav",
  "LEVELS\\Carib\\SOUND\\04_wave.wav",
  "LEVELS\\Carib\\SOUND\\05_wave.wav",
  "LEVELS\\Carib\\SOUND\\06_wave.wav",
  "LEVELS\\Carib\\SOUND\\07_boat.wav",
  "LEVELS\\Iceland\\iceland.msh",
  "LEVELS\\Iceland\\iceland.shd",
  "LEVELS\\Iceland\\Iceland.tex",
  "LEVELS\\Iceland\\ICELAND.PIC",
  "LEVELS\\Iceland\\Iceland.tab",
  "LEVELS\\Iceland\\Iceland.plc",
  "LEVELS\\Iceland\\Iceland.pos",
  "LEVELS\\Iceland\\Iceland.srf",
  "LEVELS\\Iceland\\ICELAND.COL",
  "LEVELS\\Iceland\\Iceland.tri",
  "LEVELS\\Iceland\\Iceland.pan",
  "LEVELS\\Iceland\\SOUND\\00_vulca.wav",
  "LEVELS\\Iceland\\SOUND\\01_boat.wav",
  "LEVELS\\Iceland\\SOUND\\02_wave.wav",
  "LEVELS\\Iceland\\SOUND\\03_for.wav",
  "LEVELS\\Iceland\\SOUND\\04_fores.wav",
  "LEVELS\\Iceland\\SOUND\\05_klunk.pat",
  "LEVELS\\Iceland\\SOUND\\06_fors.pat",
  "LEVELS\\Iceland\\SOUND\\07_wind.wav",
  "LEVELS\\Iceland\\SOUND\\08_wind.wav",
  "LEVELS\\Japan\\JAPAN.TRI",
  "LEVELS\\Japan\\JAPAN.MSH",
  "LEVELS\\Japan\\JAPAN.COL",
  "LEVELS\\Japan\\JAPAN.PLC",
  "LEVELS\\Japan\\JAPAN.POS",
  "LEVELS\\Japan\\JAPAN.TAB",
  "LEVELS\\Japan\\JAPAN.TEX",
  "LEVELS\\Japan\\JAPAN.SRF",
  "LEVELS\\Japan\\Japan.pan",
  "LEVELS\\Japan\\JAPAN.PIC",
  "LEVELS\\Japan\\japan.shd",
  "LEVELS\\Japan\\Sound\\00_jam.wav",
  "LEVELS\\Japan\\Sound\\01_city.wav",
  "LEVELS\\Japan\\Sound\\02_city.wav",
  "LEVELS\\Japan\\Sound\\03_train.wav",
  "LEVELS\\Japan\\Sound\\04_fligh.wav",
  "LEVELS\\Japan\\Sound\\05_sir1.wav",
  "LEVELS\\Japan\\Sound\\06_sir3.wav",
  "LEVELS\\Japan\\Sound\\08_fog.wav",
  "LEVELS\\USA\\USA.POS",
  "LEVELS\\USA\\USA.TEX",
  "LEVELS\\USA\\USA.PIC",
  "LEVELS\\USA\\USA.COL",
  "LEVELS\\USA\\Usa.pan",
  "LEVELS\\USA\\USA.TRI",
  "LEVELS\\USA\\USA.TAB",
  "LEVELS\\USA\\Usa.plc",
  "LEVELS\\USA\\USA.SRF",
  "LEVELS\\USA\\Usa.msh",
  "LEVELS\\USA\\usa.shd",
  "LEVELS\\USA\\SOUND\\00_truck.pat",
  "LEVELS\\USA\\SOUND\\01_tuta.pat",
  "LEVELS\\USA\\SOUND\\02_syrsa.wav",
  "LEVELS\\USA\\SOUND\\03_city.wav",
  "LEVELS\\USA\\SOUND\\04_gruva.pat",
  "LEVELS\\USA\\SOUND\\05_smedj.pat",
  "LEVELS\\USA\\SOUND\\06_torna.pat",
  "LEVELS\\USA\\SOUND\\07_gam.pat",
  "LEVELS\\USA\\SOUND\\08_tohit.pat"
}; // weak
char *off_40A054[293] =
{
  "remove.exe",
  "readme.txt",
  "H_pan1.pic",
  "H_pan2.pic",
  "H_signs.pic",
  "N_pangfx.pic",
  "N_Signs.pic",
  "N_sysgfx.pic",
  "N_sysg_2.pic",
  "S_pangfx.pic",
  "S_Signs.pic",
  "Pokal.pic",
  "menubkg.dat",
  "sys.col",
  "xruds137.exe",
  "Ghosts\\readme.txt",
  "Baltazar\\data\\demotrk.pic",
  "Baltazar\\data\\democar.pic",
  "Baltazar\\data\\Menu.tab",
  "Baltazar\\data\\Menu.col",
  "Baltazar\\data\\MARK.PIC",
  "Baltazar\\data\\bilar.pic",
  "Baltazar\\data\\Trk_spr.pic",
  "Baltazar\\data\\bluedark.lft",
  "Baltazar\\data\\bluegrey.lft",
  "Baltazar\\data\\bluelite.lft",
  "Baltazar\\data\\red_dark.lft",
  "Baltazar\\data\\red_grey.lft",
  "Baltazar\\data\\red_lite.lft",
  "Baltazar\\data\\Menucar.plc",
  "Baltazar\\data\\Menucar.msh",
  "Baltazar\\data\\Menucar.tex",
  "Baltazar\\data\\Conspr.pic",
  "Baltazar\\data\\Car_sel.pic",
  "Baltazar\\data\\Ign_logo.pic",
  "Baltazar\\data\\flaggor.pic",
  "Baltazar\\data\\Default.psq",
  "Baltazar\\data\\Ign1.cdp",
  "Baltazar\\data\\Ign2.cdp",
  "Baltazar\\data\\Ign3_0.cdp",
  "Baltazar\\data\\Ign3_1.cdp",
  "Baltazar\\data\\Ign3_2.cdp",
  "Baltazar\\data\\Ign3_3.cdp",
  "Baltazar\\data\\test.pfm",
  "Baltazar\\data\\textures\\boom.tex",
  "Baltazar\\data\\textures\\canada.tex",
  "Baltazar\\data\\textures\\cars.tex",
  "Baltazar\\data\\textures\\darksmok.tex",
  "Baltazar\\data\\textures\\divspr.tex",
  "Baltazar\\data\\textures\\exsmoke.tex",
  "Baltazar\\data\\textures\\light.tex",
  "Baltazar\\data\\textures\\smoke.tex",
  "Baltazar\\data\\Sound\\0_grp0\\0_sel.wav",
  "Baltazar\\data\\Sound\\0_grp0\\1_flip.wav",
  "Baltazar\\data\\Sound\\0_grp0\\2_no.wav",
  "Baltazar\\data\\Sound\\0_grp0\\3_intro.wav",
  "CARS\\TEST.AIS",
  "CARS\\Cars.msh",
  "CARS\\Cars.tex",
  "CARS\\Cars.plc",
  "CARS\\COOPER\\SOUND\\01_a.wav",
  "CARS\\COOPER\\SOUND\\ENGINE.INF",
  "CARS\\COOPER\\SOUND\\00_a.wav",
  "CARS\\Cop\\SOUND\\01_a.pat",
  "CARS\\Cop\\SOUND\\ENGINE.INF",
  "CARS\\Cop\\SOUND\\00_a.pat",
  "CARS\\Dodge\\SOUND\\01_a.wav",
  "CARS\\Dodge\\SOUND\\ENGINE.INF",
  "CARS\\Dodge\\SOUND\\00_a.wav",
  "CARS\\JEEP\\SOUND\\01_a.pat",
  "CARS\\JEEP\\SOUND\\ENGINE.INF",
  "CARS\\JEEP\\SOUND\\00_a.pat",
  "CARS\\Mustang\\SOUND\\01_a.wav",
  "CARS\\Mustang\\SOUND\\ENGINE.INF",
  "CARS\\Mustang\\SOUND\\00_a.wav",
  "CARS\\Nascar\\SOUND\\01_a.wav",
  "CARS\\Nascar\\SOUND\\ENGINE.INF",
  "CARS\\Nascar\\SOUND\\00_a.wav",
  "CARS\\PORSCHE\\SOUND\\00_a.wav",
  "CARS\\PORSCHE\\SOUND\\01_a.wav",
  "CARS\\PORSCHE\\SOUND\\ENGINE.INF",
  "CARS\\School\\SOUND\\01_a.pat",
  "CARS\\School\\SOUND\\ENGINE.INF",
  "CARS\\School\\SOUND\\00_a.pat",
  "CARS\\Truck\\SOUND\\01_a.pat",
  "CARS\\Truck\\SOUND\\ENGINE.INF",
  "CARS\\Truck\\SOUND\\00_a.pat",
  "CARS\\Van\\SOUND\\01_a.pat",
  "CARS\\Van\\SOUND\\ENGINE.INF",
  "CARS\\Van\\SOUND\\00_a.pat",
  "CARS\\VW\\SOUND\\01_a.wav",
  "CARS\\VW\\SOUND\\ENGINE.INF",
  "CARS\\VW\\SOUND\\00_a.wav",
  "fonts\\IGNITION.FNT",
  "fonts\\YELLOW.LFT",
  "fonts\\POS.LFT",
  "fonts\\SPEED.LFT",
  "fonts\\YELLOW_S.LFT",
  "fonts\\YELLOW_H.LFT",
  "fonts\\POS_S.LFT",
  "fonts\\POS_H.LFT",
  "fonts\\SPEED_S.LFT",
  "fonts\\SPEED_H.LFT",
  "fonts\\RESULT.LFT",
  "fonts\\mini.LFT",
  "fonts\\small.LFT",
  "GENERAL\\SMOKE.TEX",
  "GENERAL\\DARKSMOK.TEX",
  "GENERAL\\LIGHT.TEX",
  "GENERAL\\BOOM.TEX",
  "GENERAL\\DIVSPR.TEX",
  "GENERAL\\EXSMOKE.TEX",
  "GENERAL\\SOUND\\Boost\\00_boost.wav",
  "GENERAL\\SOUND\\Boost\\01_klick.wav",
  "GENERAL\\SOUND\\Boost\\02_ok.wav",
  "GENERAL\\SOUND\\Boost\\03_siren.pat",
  "GENERAL\\SOUND\\Boost\\04_honk.wav",
  "GENERAL\\SOUND\\Boost\\05_cool.wav",
  "GENERAL\\SOUND\\Boost\\06_jeep.wav",
  "GENERAL\\SOUND\\Boost\\07_cop.pat",
  "GENERAL\\SOUND\\Boost\\08_cruis.wav",
  "GENERAL\\SOUND\\Boost\\09_schoo.wav",
  "GENERAL\\SOUND\\Boost\\10_monst.wav",
  "GENERAL\\SOUND\\Boost\\11_bug.wav",
  "GENERAL\\SOUND\\Boost\\12_truck.wav",
  "GENERAL\\SOUND\\Boost\\13_bad.wav",
  "GENERAL\\SOUND\\Boost\\14_doggi.wav",
  "GENERAL\\SOUND\\COLL\\00_me_me.pat",
  "GENERAL\\SOUND\\COLL\\01_ME_JO.XI",
  "GENERAL\\SOUND\\COLL\\02_gniss.pat",
  "GENERAL\\SOUND\\COLL\\03_duns.pat",
  "GENERAL\\SOUND\\COLL\\04_EXPLO.wav",
  "GENERAL\\SOUND\\COLL\\05_wadea.pat",
  "GENERAL\\SOUND\\COLL\\06_mos.wav",
  "GENERAL\\SOUND\\COLL\\07_omos.wav",
  "GENERAL\\SOUND\\COLL\\08_tinye.wav",
  "GENERAL\\SOUND\\COLL\\09_landa.wav",
  "GENERAL\\SOUND\\Div\\00_redye.pat",
  "GENERAL\\SOUND\\Div\\01_green.pat",
  "GENERAL\\SOUND\\Div\\02_gear.pat",
  "GENERAL\\SOUND\\Div\\03_Start.wav",
  "GENERAL\\SOUND\\Div\\04_ghost.wav",
  "GENERAL\\SOUND\\Div\\05_swosh.wav",
  "GENERAL\\SOUND\\ROLL\\00_R_ASF.XI",
  "GENERAL\\SOUND\\ROLL\\01_R_GRA.XI",
  "GENERAL\\SOUND\\ROLL\\04_r_sno.xi",
  "GENERAL\\SOUND\\ROLL\\02_r_mud.xi",
  "GENERAL\\SOUND\\ROLL\\03_r_san.xi",
  "GENERAL\\SOUND\\SKID\\00_S_ASF.XI",
  "GENERAL\\SOUND\\SKID\\02_s_mud.xi",
  "GENERAL\\SOUND\\SKID\\01_s_gra.pat",
  "GENERAL\\SOUND\\SKID\\03_s_san.pat",
  "GENERAL\\SOUND\\SKID\\04_s_sno.pat",
  "LEVELS\\Austria\\AUSTRIA.PLC",
  "LEVELS\\Austria\\AUSTRIA.MSH",
  "LEVELS\\Austria\\AUSTRIA.COL",
  "LEVELS\\Austria\\AUSTRIA.POS",
  "LEVELS\\Austria\\AUSTRIA.TEX",
  "LEVELS\\Austria\\Austria.tab",
  "LEVELS\\Austria\\AUSTRIA.PIC",
  "LEVELS\\Austria\\Austria.pan",
  "LEVELS\\Austria\\AUSTRIA.TRI",
  "LEVELS\\Austria\\AUSTRIA.SRF",
  "LEVELS\\Austria\\austria.shd",
  "LEVELS\\Austria\\Sound\\00_lavin.wav",
  "LEVELS\\Austria\\Sound\\01_Klock.pat",
  "LEVELS\\Austria\\Sound\\02_Wind.wav",
  "LEVELS\\Austria\\Sound\\03_Kano.pat",
  "LEVELS\\Austria\\Sound\\04_Lift.pat",
  "LEVELS\\Austria\\Sound\\05_jodel.wav",
  "LEVELS\\Austria\\Sound\\06_bells.pat",
  "LEVELS\\Austria\\Sound\\07_stenm.pat",
  "LEVELS\\Brazil\\Brazil.plc",
  "LEVELS\\Brazil\\Brazil.msh",
  "LEVELS\\Brazil\\brazil.shd",
  "LEVELS\\Brazil\\Brazil.col",
  "LEVELS\\Brazil\\Brazil.pos",
  "LEVELS\\Brazil\\BRAZIL.PIC",
  "LEVELS\\Brazil\\BRAZIL.TAB",
  "LEVELS\\Brazil\\Brazil.srf",
  "LEVELS\\Brazil\\Brazil.pan",
  "LEVELS\\Brazil\\Brazil.tex",
  "LEVELS\\Brazil\\brazil.tri",
  "LEVELS\\Brazil\\Sound\\00_Djung.wav",
  "LEVELS\\Brazil\\Sound\\01_Djung.wav",
  "LEVELS\\Brazil\\Sound\\02_Djung.wav",
  "LEVELS\\Brazil\\Sound\\03_Djung.wav",
  "LEVELS\\Brazil\\Sound\\04_Djung.wav",
  "LEVELS\\Brazil\\Sound\\05_Djung.wav",
  "LEVELS\\Brazil\\Sound\\06_tribe.wav",
  "LEVELS\\Brazil\\Sound\\07_fors.pat",
  "LEVELS\\Canada\\CANADA.PIC",
  "LEVELS\\Canada\\Canada.plc",
  "LEVELS\\Canada\\CANADA.TRI",
  "LEVELS\\Canada\\CANADA.SRF",
  "LEVELS\\Canada\\Canada.tab",
  "LEVELS\\Canada\\CANADA.COL",
  "LEVELS\\Canada\\CANADA.MSH",
  "LEVELS\\Canada\\CANADA.POS",
  "LEVELS\\Canada\\CANADA.TEX",
  "LEVELS\\Canada\\Canada.pan",
  "LEVELS\\Canada\\canada.shd",
  "LEVELS\\Canada\\Sound\\00_rain.wav",
  "LEVELS\\Canada\\Sound\\01_thund.pat",
  "LEVELS\\Canada\\Sound\\02_light.pat",
  "LEVELS\\Canada\\Sound\\03_train.wav",
  "LEVELS\\Canada\\Sound\\04_water.pat",
  "LEVELS\\Canada\\Sound\\06_trakt.pat",
  "LEVELS\\Canada\\Sound\\07_bell.wav",
  "LEVELS\\Canada\\Sound\\08_farm.wav",
  "LEVELS\\Canada\\Sound\\09_for.wav",
  "LEVELS\\Canada\\Sound\\10_for.wav",
  "LEVELS\\Canada\\Sound\\11_for.wav",
  "LEVELS\\Canada\\Sound\\12_for.wav",
  "LEVELS\\Canada\\Sound\\13_fact.wav",
  "LEVELS\\Carib\\CARIB.TRI",
  "LEVELS\\Carib\\CARIB.SRF",
  "LEVELS\\Carib\\CARIB.TEX",
  "LEVELS\\Carib\\Carib.pan",
  "LEVELS\\Carib\\CARIB.TAB",
  "LEVELS\\Carib\\CARIB.COL",
  "LEVELS\\Carib\\Carib.plc",
  "LEVELS\\Carib\\Carib.pos",
  "LEVELS\\Carib\\Carib.msh",
  "LEVELS\\Carib\\CARIB.PIC",
  "LEVELS\\Carib\\carib.shd",
  "LEVELS\\Carib\\SOUND\\00_wave.wav",
  "LEVELS\\Carib\\SOUND\\01_samba.wav",
  "LEVELS\\Carib\\SOUND\\02_wave.wav",
  "LEVELS\\Carib\\SOUND\\03_wave.wav",
  "LEVELS\\Carib\\SOUND\\04_wave.wav",
  "LEVELS\\Carib\\SOUND\\05_wave.wav",
  "LEVELS\\Carib\\SOUND\\06_wave.wav",
  "LEVELS\\Carib\\SOUND\\07_boat.wav",
  "LEVELS\\Iceland\\iceland.msh",
  "LEVELS\\Iceland\\iceland.shd",
  "LEVELS\\Iceland\\Iceland.tex",
  "LEVELS\\Iceland\\ICELAND.PIC",
  "LEVELS\\Iceland\\Iceland.tab",
  "LEVELS\\Iceland\\Iceland.plc",
  "LEVELS\\Iceland\\Iceland.pos",
  "LEVELS\\Iceland\\Iceland.srf",
  "LEVELS\\Iceland\\ICELAND.COL",
  "LEVELS\\Iceland\\Iceland.tri",
  "LEVELS\\Iceland\\Iceland.pan",
  "LEVELS\\Iceland\\SOUND\\00_vulca.wav",
  "LEVELS\\Iceland\\SOUND\\01_boat.wav",
  "LEVELS\\Iceland\\SOUND\\02_wave.wav",
  "LEVELS\\Iceland\\SOUND\\03_for.wav",
  "LEVELS\\Iceland\\SOUND\\04_fores.wav",
  "LEVELS\\Iceland\\SOUND\\05_klunk.pat",
  "LEVELS\\Iceland\\SOUND\\06_fors.pat",
  "LEVELS\\Iceland\\SOUND\\07_wind.wav",
  "LEVELS\\Iceland\\SOUND\\08_wind.wav",
  "LEVELS\\Japan\\JAPAN.TRI",
  "LEVELS\\Japan\\JAPAN.MSH",
  "LEVELS\\Japan\\JAPAN.COL",
  "LEVELS\\Japan\\JAPAN.PLC",
  "LEVELS\\Japan\\JAPAN.POS",
  "LEVELS\\Japan\\JAPAN.TAB",
  "LEVELS\\Japan\\JAPAN.TEX",
  "LEVELS\\Japan\\JAPAN.SRF",
  "LEVELS\\Japan\\Japan.pan",
  "LEVELS\\Japan\\JAPAN.PIC",
  "LEVELS\\Japan\\japan.shd",
  "LEVELS\\Japan\\Sound\\00_jam.wav",
  "LEVELS\\Japan\\Sound\\01_city.wav",
  "LEVELS\\Japan\\Sound\\02_city.wav",
  "LEVELS\\Japan\\Sound\\03_train.wav",
  "LEVELS\\Japan\\Sound\\04_fligh.wav",
  "LEVELS\\Japan\\Sound\\05_sir1.wav",
  "LEVELS\\Japan\\Sound\\06_sir3.wav",
  "LEVELS\\Japan\\Sound\\08_fog.wav",
  "LEVELS\\USA\\USA.POS",
  "LEVELS\\USA\\USA.TEX",
  "LEVELS\\USA\\USA.PIC",
  "LEVELS\\USA\\USA.COL",
  "LEVELS\\USA\\Usa.pan",
  "LEVELS\\USA\\USA.TRI",
  "LEVELS\\USA\\USA.TAB",
  "LEVELS\\USA\\Usa.plc",
  "LEVELS\\USA\\USA.SRF",
  "LEVELS\\USA\\Usa.msh",
  "LEVELS\\USA\\usa.shd",
  "LEVELS\\USA\\SOUND\\00_truck.pat",
  "LEVELS\\USA\\SOUND\\01_tuta.pat",
  "LEVELS\\USA\\SOUND\\02_syrsa.wav",
  "LEVELS\\USA\\SOUND\\03_city.wav",
  "LEVELS\\USA\\SOUND\\04_gruva.pat",
  "LEVELS\\USA\\SOUND\\05_smedj.pat",
  "LEVELS\\USA\\SOUND\\06_torna.pat",
  "LEVELS\\USA\\SOUND\\07_gam.pat",
  "LEVELS\\USA\\SOUND\\08_tohit.pat"
}; // weak
char *off_40A058[292] =
{
  "readme.txt",
  "H_pan1.pic",
  "H_pan2.pic",
  "H_signs.pic",
  "N_pangfx.pic",
  "N_Signs.pic",
  "N_sysgfx.pic",
  "N_sysg_2.pic",
  "S_pangfx.pic",
  "S_Signs.pic",
  "Pokal.pic",
  "menubkg.dat",
  "sys.col",
  "xruds137.exe",
  "Ghosts\\readme.txt",
  "Baltazar\\data\\demotrk.pic",
  "Baltazar\\data\\democar.pic",
  "Baltazar\\data\\Menu.tab",
  "Baltazar\\data\\Menu.col",
  "Baltazar\\data\\MARK.PIC",
  "Baltazar\\data\\bilar.pic",
  "Baltazar\\data\\Trk_spr.pic",
  "Baltazar\\data\\bluedark.lft",
  "Baltazar\\data\\bluegrey.lft",
  "Baltazar\\data\\bluelite.lft",
  "Baltazar\\data\\red_dark.lft",
  "Baltazar\\data\\red_grey.lft",
  "Baltazar\\data\\red_lite.lft",
  "Baltazar\\data\\Menucar.plc",
  "Baltazar\\data\\Menucar.msh",
  "Baltazar\\data\\Menucar.tex",
  "Baltazar\\data\\Conspr.pic",
  "Baltazar\\data\\Car_sel.pic",
  "Baltazar\\data\\Ign_logo.pic",
  "Baltazar\\data\\flaggor.pic",
  "Baltazar\\data\\Default.psq",
  "Baltazar\\data\\Ign1.cdp",
  "Baltazar\\data\\Ign2.cdp",
  "Baltazar\\data\\Ign3_0.cdp",
  "Baltazar\\data\\Ign3_1.cdp",
  "Baltazar\\data\\Ign3_2.cdp",
  "Baltazar\\data\\Ign3_3.cdp",
  "Baltazar\\data\\test.pfm",
  "Baltazar\\data\\textures\\boom.tex",
  "Baltazar\\data\\textures\\canada.tex",
  "Baltazar\\data\\textures\\cars.tex",
  "Baltazar\\data\\textures\\darksmok.tex",
  "Baltazar\\data\\textures\\divspr.tex",
  "Baltazar\\data\\textures\\exsmoke.tex",
  "Baltazar\\data\\textures\\light.tex",
  "Baltazar\\data\\textures\\smoke.tex",
  "Baltazar\\data\\Sound\\0_grp0\\0_sel.wav",
  "Baltazar\\data\\Sound\\0_grp0\\1_flip.wav",
  "Baltazar\\data\\Sound\\0_grp0\\2_no.wav",
  "Baltazar\\data\\Sound\\0_grp0\\3_intro.wav",
  "CARS\\TEST.AIS",
  "CARS\\Cars.msh",
  "CARS\\Cars.tex",
  "CARS\\Cars.plc",
  "CARS\\COOPER\\SOUND\\01_a.wav",
  "CARS\\COOPER\\SOUND\\ENGINE.INF",
  "CARS\\COOPER\\SOUND\\00_a.wav",
  "CARS\\Cop\\SOUND\\01_a.pat",
  "CARS\\Cop\\SOUND\\ENGINE.INF",
  "CARS\\Cop\\SOUND\\00_a.pat",
  "CARS\\Dodge\\SOUND\\01_a.wav",
  "CARS\\Dodge\\SOUND\\ENGINE.INF",
  "CARS\\Dodge\\SOUND\\00_a.wav",
  "CARS\\JEEP\\SOUND\\01_a.pat",
  "CARS\\JEEP\\SOUND\\ENGINE.INF",
  "CARS\\JEEP\\SOUND\\00_a.pat",
  "CARS\\Mustang\\SOUND\\01_a.wav",
  "CARS\\Mustang\\SOUND\\ENGINE.INF",
  "CARS\\Mustang\\SOUND\\00_a.wav",
  "CARS\\Nascar\\SOUND\\01_a.wav",
  "CARS\\Nascar\\SOUND\\ENGINE.INF",
  "CARS\\Nascar\\SOUND\\00_a.wav",
  "CARS\\PORSCHE\\SOUND\\00_a.wav",
  "CARS\\PORSCHE\\SOUND\\01_a.wav",
  "CARS\\PORSCHE\\SOUND\\ENGINE.INF",
  "CARS\\School\\SOUND\\01_a.pat",
  "CARS\\School\\SOUND\\ENGINE.INF",
  "CARS\\School\\SOUND\\00_a.pat",
  "CARS\\Truck\\SOUND\\01_a.pat",
  "CARS\\Truck\\SOUND\\ENGINE.INF",
  "CARS\\Truck\\SOUND\\00_a.pat",
  "CARS\\Van\\SOUND\\01_a.pat",
  "CARS\\Van\\SOUND\\ENGINE.INF",
  "CARS\\Van\\SOUND\\00_a.pat",
  "CARS\\VW\\SOUND\\01_a.wav",
  "CARS\\VW\\SOUND\\ENGINE.INF",
  "CARS\\VW\\SOUND\\00_a.wav",
  "fonts\\IGNITION.FNT",
  "fonts\\YELLOW.LFT",
  "fonts\\POS.LFT",
  "fonts\\SPEED.LFT",
  "fonts\\YELLOW_S.LFT",
  "fonts\\YELLOW_H.LFT",
  "fonts\\POS_S.LFT",
  "fonts\\POS_H.LFT",
  "fonts\\SPEED_S.LFT",
  "fonts\\SPEED_H.LFT",
  "fonts\\RESULT.LFT",
  "fonts\\mini.LFT",
  "fonts\\small.LFT",
  "GENERAL\\SMOKE.TEX",
  "GENERAL\\DARKSMOK.TEX",
  "GENERAL\\LIGHT.TEX",
  "GENERAL\\BOOM.TEX",
  "GENERAL\\DIVSPR.TEX",
  "GENERAL\\EXSMOKE.TEX",
  "GENERAL\\SOUND\\Boost\\00_boost.wav",
  "GENERAL\\SOUND\\Boost\\01_klick.wav",
  "GENERAL\\SOUND\\Boost\\02_ok.wav",
  "GENERAL\\SOUND\\Boost\\03_siren.pat",
  "GENERAL\\SOUND\\Boost\\04_honk.wav",
  "GENERAL\\SOUND\\Boost\\05_cool.wav",
  "GENERAL\\SOUND\\Boost\\06_jeep.wav",
  "GENERAL\\SOUND\\Boost\\07_cop.pat",
  "GENERAL\\SOUND\\Boost\\08_cruis.wav",
  "GENERAL\\SOUND\\Boost\\09_schoo.wav",
  "GENERAL\\SOUND\\Boost\\10_monst.wav",
  "GENERAL\\SOUND\\Boost\\11_bug.wav",
  "GENERAL\\SOUND\\Boost\\12_truck.wav",
  "GENERAL\\SOUND\\Boost\\13_bad.wav",
  "GENERAL\\SOUND\\Boost\\14_doggi.wav",
  "GENERAL\\SOUND\\COLL\\00_me_me.pat",
  "GENERAL\\SOUND\\COLL\\01_ME_JO.XI",
  "GENERAL\\SOUND\\COLL\\02_gniss.pat",
  "GENERAL\\SOUND\\COLL\\03_duns.pat",
  "GENERAL\\SOUND\\COLL\\04_EXPLO.wav",
  "GENERAL\\SOUND\\COLL\\05_wadea.pat",
  "GENERAL\\SOUND\\COLL\\06_mos.wav",
  "GENERAL\\SOUND\\COLL\\07_omos.wav",
  "GENERAL\\SOUND\\COLL\\08_tinye.wav",
  "GENERAL\\SOUND\\COLL\\09_landa.wav",
  "GENERAL\\SOUND\\Div\\00_redye.pat",
  "GENERAL\\SOUND\\Div\\01_green.pat",
  "GENERAL\\SOUND\\Div\\02_gear.pat",
  "GENERAL\\SOUND\\Div\\03_Start.wav",
  "GENERAL\\SOUND\\Div\\04_ghost.wav",
  "GENERAL\\SOUND\\Div\\05_swosh.wav",
  "GENERAL\\SOUND\\ROLL\\00_R_ASF.XI",
  "GENERAL\\SOUND\\ROLL\\01_R_GRA.XI",
  "GENERAL\\SOUND\\ROLL\\04_r_sno.xi",
  "GENERAL\\SOUND\\ROLL\\02_r_mud.xi",
  "GENERAL\\SOUND\\ROLL\\03_r_san.xi",
  "GENERAL\\SOUND\\SKID\\00_S_ASF.XI",
  "GENERAL\\SOUND\\SKID\\02_s_mud.xi",
  "GENERAL\\SOUND\\SKID\\01_s_gra.pat",
  "GENERAL\\SOUND\\SKID\\03_s_san.pat",
  "GENERAL\\SOUND\\SKID\\04_s_sno.pat",
  "LEVELS\\Austria\\AUSTRIA.PLC",
  "LEVELS\\Austria\\AUSTRIA.MSH",
  "LEVELS\\Austria\\AUSTRIA.COL",
  "LEVELS\\Austria\\AUSTRIA.POS",
  "LEVELS\\Austria\\AUSTRIA.TEX",
  "LEVELS\\Austria\\Austria.tab",
  "LEVELS\\Austria\\AUSTRIA.PIC",
  "LEVELS\\Austria\\Austria.pan",
  "LEVELS\\Austria\\AUSTRIA.TRI",
  "LEVELS\\Austria\\AUSTRIA.SRF",
  "LEVELS\\Austria\\austria.shd",
  "LEVELS\\Austria\\Sound\\00_lavin.wav",
  "LEVELS\\Austria\\Sound\\01_Klock.pat",
  "LEVELS\\Austria\\Sound\\02_Wind.wav",
  "LEVELS\\Austria\\Sound\\03_Kano.pat",
  "LEVELS\\Austria\\Sound\\04_Lift.pat",
  "LEVELS\\Austria\\Sound\\05_jodel.wav",
  "LEVELS\\Austria\\Sound\\06_bells.pat",
  "LEVELS\\Austria\\Sound\\07_stenm.pat",
  "LEVELS\\Brazil\\Brazil.plc",
  "LEVELS\\Brazil\\Brazil.msh",
  "LEVELS\\Brazil\\brazil.shd",
  "LEVELS\\Brazil\\Brazil.col",
  "LEVELS\\Brazil\\Brazil.pos",
  "LEVELS\\Brazil\\BRAZIL.PIC",
  "LEVELS\\Brazil\\BRAZIL.TAB",
  "LEVELS\\Brazil\\Brazil.srf",
  "LEVELS\\Brazil\\Brazil.pan",
  "LEVELS\\Brazil\\Brazil.tex",
  "LEVELS\\Brazil\\brazil.tri",
  "LEVELS\\Brazil\\Sound\\00_Djung.wav",
  "LEVELS\\Brazil\\Sound\\01_Djung.wav",
  "LEVELS\\Brazil\\Sound\\02_Djung.wav",
  "LEVELS\\Brazil\\Sound\\03_Djung.wav",
  "LEVELS\\Brazil\\Sound\\04_Djung.wav",
  "LEVELS\\Brazil\\Sound\\05_Djung.wav",
  "LEVELS\\Brazil\\Sound\\06_tribe.wav",
  "LEVELS\\Brazil\\Sound\\07_fors.pat",
  "LEVELS\\Canada\\CANADA.PIC",
  "LEVELS\\Canada\\Canada.plc",
  "LEVELS\\Canada\\CANADA.TRI",
  "LEVELS\\Canada\\CANADA.SRF",
  "LEVELS\\Canada\\Canada.tab",
  "LEVELS\\Canada\\CANADA.COL",
  "LEVELS\\Canada\\CANADA.MSH",
  "LEVELS\\Canada\\CANADA.POS",
  "LEVELS\\Canada\\CANADA.TEX",
  "LEVELS\\Canada\\Canada.pan",
  "LEVELS\\Canada\\canada.shd",
  "LEVELS\\Canada\\Sound\\00_rain.wav",
  "LEVELS\\Canada\\Sound\\01_thund.pat",
  "LEVELS\\Canada\\Sound\\02_light.pat",
  "LEVELS\\Canada\\Sound\\03_train.wav",
  "LEVELS\\Canada\\Sound\\04_water.pat",
  "LEVELS\\Canada\\Sound\\06_trakt.pat",
  "LEVELS\\Canada\\Sound\\07_bell.wav",
  "LEVELS\\Canada\\Sound\\08_farm.wav",
  "LEVELS\\Canada\\Sound\\09_for.wav",
  "LEVELS\\Canada\\Sound\\10_for.wav",
  "LEVELS\\Canada\\Sound\\11_for.wav",
  "LEVELS\\Canada\\Sound\\12_for.wav",
  "LEVELS\\Canada\\Sound\\13_fact.wav",
  "LEVELS\\Carib\\CARIB.TRI",
  "LEVELS\\Carib\\CARIB.SRF",
  "LEVELS\\Carib\\CARIB.TEX",
  "LEVELS\\Carib\\Carib.pan",
  "LEVELS\\Carib\\CARIB.TAB",
  "LEVELS\\Carib\\CARIB.COL",
  "LEVELS\\Carib\\Carib.plc",
  "LEVELS\\Carib\\Carib.pos",
  "LEVELS\\Carib\\Carib.msh",
  "LEVELS\\Carib\\CARIB.PIC",
  "LEVELS\\Carib\\carib.shd",
  "LEVELS\\Carib\\SOUND\\00_wave.wav",
  "LEVELS\\Carib\\SOUND\\01_samba.wav",
  "LEVELS\\Carib\\SOUND\\02_wave.wav",
  "LEVELS\\Carib\\SOUND\\03_wave.wav",
  "LEVELS\\Carib\\SOUND\\04_wave.wav",
  "LEVELS\\Carib\\SOUND\\05_wave.wav",
  "LEVELS\\Carib\\SOUND\\06_wave.wav",
  "LEVELS\\Carib\\SOUND\\07_boat.wav",
  "LEVELS\\Iceland\\iceland.msh",
  "LEVELS\\Iceland\\iceland.shd",
  "LEVELS\\Iceland\\Iceland.tex",
  "LEVELS\\Iceland\\ICELAND.PIC",
  "LEVELS\\Iceland\\Iceland.tab",
  "LEVELS\\Iceland\\Iceland.plc",
  "LEVELS\\Iceland\\Iceland.pos",
  "LEVELS\\Iceland\\Iceland.srf",
  "LEVELS\\Iceland\\ICELAND.COL",
  "LEVELS\\Iceland\\Iceland.tri",
  "LEVELS\\Iceland\\Iceland.pan",
  "LEVELS\\Iceland\\SOUND\\00_vulca.wav",
  "LEVELS\\Iceland\\SOUND\\01_boat.wav",
  "LEVELS\\Iceland\\SOUND\\02_wave.wav",
  "LEVELS\\Iceland\\SOUND\\03_for.wav",
  "LEVELS\\Iceland\\SOUND\\04_fores.wav",
  "LEVELS\\Iceland\\SOUND\\05_klunk.pat",
  "LEVELS\\Iceland\\SOUND\\06_fors.pat",
  "LEVELS\\Iceland\\SOUND\\07_wind.wav",
  "LEVELS\\Iceland\\SOUND\\08_wind.wav",
  "LEVELS\\Japan\\JAPAN.TRI",
  "LEVELS\\Japan\\JAPAN.MSH",
  "LEVELS\\Japan\\JAPAN.COL",
  "LEVELS\\Japan\\JAPAN.PLC",
  "LEVELS\\Japan\\JAPAN.POS",
  "LEVELS\\Japan\\JAPAN.TAB",
  "LEVELS\\Japan\\JAPAN.TEX",
  "LEVELS\\Japan\\JAPAN.SRF",
  "LEVELS\\Japan\\Japan.pan",
  "LEVELS\\Japan\\JAPAN.PIC",
  "LEVELS\\Japan\\japan.shd",
  "LEVELS\\Japan\\Sound\\00_jam.wav",
  "LEVELS\\Japan\\Sound\\01_city.wav",
  "LEVELS\\Japan\\Sound\\02_city.wav",
  "LEVELS\\Japan\\Sound\\03_train.wav",
  "LEVELS\\Japan\\Sound\\04_fligh.wav",
  "LEVELS\\Japan\\Sound\\05_sir1.wav",
  "LEVELS\\Japan\\Sound\\06_sir3.wav",
  "LEVELS\\Japan\\Sound\\08_fog.wav",
  "LEVELS\\USA\\USA.POS",
  "LEVELS\\USA\\USA.TEX",
  "LEVELS\\USA\\USA.PIC",
  "LEVELS\\USA\\USA.COL",
  "LEVELS\\USA\\Usa.pan",
  "LEVELS\\USA\\USA.TRI",
  "LEVELS\\USA\\USA.TAB",
  "LEVELS\\USA\\Usa.plc",
  "LEVELS\\USA\\USA.SRF",
  "LEVELS\\USA\\Usa.msh",
  "LEVELS\\USA\\usa.shd",
  "LEVELS\\USA\\SOUND\\00_truck.pat",
  "LEVELS\\USA\\SOUND\\01_tuta.pat",
  "LEVELS\\USA\\SOUND\\02_syrsa.wav",
  "LEVELS\\USA\\SOUND\\03_city.wav",
  "LEVELS\\USA\\SOUND\\04_gruva.pat",
  "LEVELS\\USA\\SOUND\\05_smedj.pat",
  "LEVELS\\USA\\SOUND\\06_torna.pat",
  "LEVELS\\USA\\SOUND\\07_gam.pat",
  "LEVELS\\USA\\SOUND\\08_tohit.pat"
}; // weak
HKEY hKey = NULL; // idb
CHAR String2[2] = "\\"; // idb
CHAR SrcStr[4] = { '\0', '\0', '\0', '\0' }; // idb
CHAR ValueName[] = "Ignition Path"; // idb
CHAR SubKey[] = "Software\\UDS\\Ignition"; // idb
CHAR RootPathName[] = "C:\\"; // idb
CHAR byte_40A534[4] = { '\0', '\0', '\0', '\0' }; // idb
CHAR aSmagIni[] = "SMAG.INI"; // idb
CHAR aWinIni[] = "WIN.INI"; // idb
char byte_40A54C[4] = { '\0', '\0', '\0', '\0' }; // weak
char SubStr[] = "\\IGNITION"; // idb
CHAR TemplateName[] = "DLG_MASTER"; // idb
DWORD dwDisposition; // idb
int dword_40B804; // weak
int dword_40B808; // weak
CHAR Caption[512]; // idb
HINSTANCE hInst; // idb
CHAR sz; // idb
CHAR String; // idb
char byte_40BB21; // weak
char byte_40BB22; // weak
int dword_40BC28; // weak
// extern LSTATUS (__stdcall *RegCreateKeyExA)(HKEY hKey, LPCSTR lpSubKey, DWORD Reserved, LPSTR lpClass, DWORD dwOptions, REGSAM samDesired, const LPSECURITY_ATTRIBUTES lpSecurityAttributes, PHKEY phkResult, LPDWORD lpdwDisposition);
// extern LSTATUS (__stdcall *RegSetValueExA)(HKEY hKey, LPCSTR lpValueName, DWORD Reserved, DWORD dwType, const BYTE *lpData, DWORD cbData);
// extern LSTATUS (__stdcall *RegCloseKey)(HKEY hKey);
// extern BOOL (__stdcall *DeleteObject)(HGDIOBJ ho);
// extern int (__stdcall *MultiByteToWideChar)(UINT CodePage, DWORD dwFlags, LPCCH lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr, int cchWideChar);
// extern DWORD (__stdcall *GetModuleFileNameA)(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// extern UINT (__stdcall *GetWindowsDirectoryA)(LPSTR lpBuffer, UINT uSize);
// extern BOOL (__stdcall *GetDiskFreeSpaceA)(LPCSTR lpRootPathName, LPDWORD lpSectorsPerCluster, LPDWORD lpBytesPerSector, LPDWORD lpNumberOfFreeClusters, LPDWORD lpTotalNumberOfClusters);
// extern BOOL (__stdcall *SetFileAttributesA)(LPCSTR lpFileName, DWORD dwFileAttributes);
// extern LPSTR (__stdcall *lstrcpyA)(LPSTR lpString1, LPCSTR lpString2);
// extern BOOL (__stdcall *CreateDirectoryA)(LPCSTR lpPathName, LPSECURITY_ATTRIBUTES lpSecurityAttributes);
// extern HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName);
// extern int (__stdcall *lstrlenA)(LPCSTR lpString);
// extern LPSTR (__stdcall *lstrcatA)(LPSTR lpString1, LPCSTR lpString2);
// extern int (__stdcall *SHFileOperationA)(LPSHFILEOPSTRUCTA lpFileOp);
// extern void (__stdcall *SHChangeNotify)(LONG wEventId, UINT uFlags, LPCVOID dwItem1, LPCVOID dwItem2);
// extern HRESULT (__stdcall *SHGetMalloc)(IMalloc **ppMalloc);
// extern LPITEMIDLIST (__stdcall *SHBrowseForFolderA)(LPBROWSEINFOA lpbi);
// extern BOOL (__stdcall *SHGetPathFromIDListA)(LPCITEMIDLIST pidl, LPSTR pszPath);
// extern HRESULT (__stdcall *SHGetSpecialFolderLocation)(HWND hwnd, int csidl, LPITEMIDLIST *ppidl);
// extern HCURSOR (__stdcall *SetCursor)(HCURSOR hCursor);
// extern HCURSOR (__stdcall *LoadCursorA)(HINSTANCE hInstance, LPCSTR lpCursorName);
// extern LRESULT (__stdcall *SendMessageA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern HANDLE (__stdcall *LoadImageA)(HINSTANCE hInst, LPCSTR name, UINT type, int cx, int cy, UINT fuLoad);
// extern HWND (__stdcall *GetDlgItem)(HWND hDlg, int nIDDlgItem);
// extern BOOL (__stdcall *SetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPCSTR lpString);
// extern int (__stdcall *wvsprintfA)(LPSTR, LPCSTR, va_list arglist);
// extern LPSTR (__stdcall *CharNextA)(LPCSTR lpsz);
// extern INT_PTR (__stdcall *DialogBoxParamA)(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam);
// extern LRESULT (__stdcall *SendDlgItemMessageA)(HWND hDlg, int nIDDlgItem, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern HWND (__stdcall *SetFocus)(HWND hWnd);
// extern int (__stdcall *GetWindowTextA)(HWND hWnd, LPSTR lpString, int nMaxCount);
// extern BOOL (__stdcall *EndDialog)(HWND hDlg, INT_PTR nResult);
// extern int (*wsprintfA)(LPSTR, LPCSTR, ...);
// extern BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow);
// extern BOOL (__stdcall *SetWindowTextA)(HWND hWnd, LPCSTR lpString);
// extern BOOL (__stdcall *EnableWindow)(HWND hWnd, BOOL bEnable);
// extern BOOL (__stdcall *ExitWindowsEx)(UINT uFlags, DWORD dwReason);
// extern int (__stdcall *LoadStringA)(HINSTANCE hInstance, UINT uID, LPSTR lpBuffer, int cchBufferMax);
// extern int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// extern void (__stdcall *CoUninitialize)();
// extern HRESULT (__stdcall *CoInitialize)(LPVOID pvReserved);
// extern HRESULT (__stdcall *CoCreateInstance)(const IID *const rclsid, LPUNKNOWN pUnkOuter, DWORD dwClsContext, const IID *const riid, LPVOID *ppv);


//----- (00401000) --------------------------------------------------------
int __cdecl sub_401000(CHAR *lpString, LPCSTR lpString2)
{
  int v2; // eax
  CHAR v3; // al
  int result; // eax

  v2 = lstrlenA(lpString);
  if ( v2 > 0 )
  {
    v3 = lpString[v2 - 1];
    if ( v3 != 92 && v3 != 47 )
      lstrcatA(lpString, String2);
  }
  lstrcatA(lpString, lpString2);
  result = lstrlenA(lpString);
  lpString[result + 1] = 0;
  return result;
}

//----- (00401050) --------------------------------------------------------
HWND __cdecl sub_401050(HWND hDlg, int nIDDlgItem, LPCSTR name, int a4, int cy)
{
  HWND result; // eax
  HWND v6; // esi

  result = GetDlgItem(hDlg, nIDDlgItem);
  v6 = result;
  if ( result )
  {
    result = (HWND)LoadImageA(hInst, name, 0, a4, cy, 0x3020u);
    if ( result )
    {
      result = (HWND)SendMessageA(v6, 0x172u, 0, (LPARAM)result);
      if ( result )
        return (HWND)DeleteObject(result);
    }
  }
  return result;
}

//----- (004010B0) --------------------------------------------------------
BOOL sub_4010B0(HWND hDlg, LPCSTR a2, ...)
{
  CHAR String[128]; // [esp+0h] [ebp-80h] BYREF
  va_list va; // [esp+8Ch] [ebp+Ch] BYREF

  va_start(va, a2);
  wvsprintfA(String, a2, va);
  return SetDlgItemTextA(hDlg, 1009, String);
}

//----- (004010F0) --------------------------------------------------------
HRESULT __cdecl sub_4010F0(void *a1)
{
  HRESULT result; // eax
  IMalloc *ppMalloc; // [esp+8h] [ebp-4h] BYREF

  result = SHGetMalloc(&ppMalloc);
  if ( ppMalloc )
  {
    ppMalloc->lpVtbl->Free(ppMalloc, a1);
    return ppMalloc->lpVtbl->Release(ppMalloc);
  }
  return result;
}

//----- (00401130) --------------------------------------------------------
INT_PTR __stdcall DialogFunc(HWND hWnd, UINT a2, WPARAM a3, LPARAM a4)
{
  HCURSOR CursorA; // eax
  HMODULE ModuleHandleA; // eax
  HWND DlgItem; // eax
  HWND v8; // eax
  HMODULE v9; // eax
  HMODULE v10; // eax
  HWND v11; // eax
  HWND v12; // ebp
  HWND v13; // eax
  HWND v14; // eax
  HCURSOR v15; // eax
  HWND v16; // eax
  HMODULE v17; // eax
  HWND v18; // eax
  HWND v19; // eax
  HMODULE v20; // eax
  HMODULE v21; // eax
  void (__stdcall *v22)(HWND, LPCSTR, LPCSTR, UINT); // edi
  INT_PTR v23; // esi
  HMODULE v24; // eax
  HMODULE v25; // eax
  HMODULE v26; // eax
  HMODULE v27; // eax
  HMODULE v28; // eax
  HMODULE v29; // eax
  HMODULE v30; // eax
  HMODULE v31; // eax
  HMODULE v32; // eax
  HWND v33; // eax
  HWND v34; // eax
  HCURSOR v35; // eax
  HMODULE v36; // eax
  HMODULE v37; // eax
  LPCSTR *v38; // esi
  HMODULE v39; // eax
  HMODULE v40; // eax
  HMODULE v41; // eax
  HMODULE v42; // eax
  HMODULE v43; // eax
  HMODULE v44; // eax
  HMODULE v45; // eax
  HWND v46; // eax
  HWND v47; // eax
  HWND v48; // eax
  HWND v49; // eax
  HWND v50; // eax
  HWND v51; // eax
  HMODULE v52; // eax
  HWND v53; // eax
  HMODULE v54; // eax
  HWND v55; // eax
  HMODULE v56; // eax
  HWND v57; // eax
  HMODULE v58; // eax
  HWND v59; // eax
  HMODULE v60; // eax
  HWND v61; // eax
  HWND v62; // eax
  HMODULE v63; // eax
  HWND v64; // eax
  HMODULE v65; // eax
  HWND v66; // eax
  HWND v67; // eax
  ITEMIDLIST *v68; // ebx
  HMODULE v69; // eax
  HMODULE v70; // eax
  UINT v71; // [esp-Ch] [ebp-1894h]
  INT_PTR v72; // [esp-4h] [ebp-188Ch]
  CHAR RootPathName[2]; // [esp+10h] [ebp-1878h] BYREF
  char v74[2]; // [esp+12h] [ebp-1876h] BYREF
  DWORD NumberOfFreeClusters; // [esp+14h] [ebp-1874h] BYREF
  DWORD BytesPerSector; // [esp+18h] [ebp-1870h] BYREF
  DWORD SectorsPerCluster; // [esp+1Ch] [ebp-186Ch] BYREF
  struct _browseinfoA bi; // [esp+20h] [ebp-1868h] BYREF
  struct _SHFILEOPSTRUCTA FileOp; // [esp+40h] [ebp-1848h] BYREF
  DWORD TotalNumberOfClusters; // [esp+60h] [ebp-1828h] BYREF
  LPITEMIDLIST ppidl; // [esp+64h] [ebp-1824h] BYREF
  CHAR Buffer[512]; // [esp+68h] [ebp-1820h] BYREF
  CHAR String1[260]; // [esp+268h] [ebp-1620h] BYREF
  INT_PTR String[193]; // [esp+36Ch] [ebp-151Ch] BYREF
  CHAR PathName[260]; // [esp+670h] [ebp-1218h] BYREF
  CHAR v86[260]; // [esp+774h] [ebp-1114h] BYREF
  CHAR v87[260]; // [esp+878h] [ebp-1010h] BYREF
  CHAR MultiByteStr[260]; // [esp+97Ch] [ebp-F0Ch] BYREF
  CHAR v89[260]; // [esp+A80h] [ebp-E08h] BYREF
  CHAR Caption[512]; // [esp+B84h] [ebp-D04h] BYREF
  CHAR Text[512]; // [esp+D84h] [ebp-B04h] BYREF
  CHAR pszPath[260]; // [esp+F84h] [ebp-904h] BYREF
  BYTE Data[512]; // [esp+1088h] [ebp-800h] BYREF
  CHAR v94[1024]; // [esp+1288h] [ebp-600h] BYREF
  CHAR v95[512]; // [esp+1688h] [ebp-200h] BYREF

  switch ( a2 )
  {
    case 0x20u:
      if ( !dword_40B808 )
        return 0;
      CursorA = LoadCursorA(0, (LPCSTR)0x7F02);
      SetCursor(CursorA);
      return 1;
    case 0x110u:
      dword_40B808 = 0;
      dword_40B804 = 0;
      ModuleHandleA = GetModuleHandleA(0);
      LoadStringA(ModuleHandleA, 0x65u, ::Caption, 512);
      SetWindowTextA(hWnd, ::Caption);
      DlgItem = GetDlgItem(hWnd, 1008);
      EnableWindow(DlgItem, 0);
      v8 = GetDlgItem(hWnd, 1007);
      EnableWindow(v8, 0);
      v9 = GetModuleHandleA(0);
      LoadStringA(v9, 0x76u, Buffer, 512);
      sub_401050(hWnd, 1002, Buffer, 175, 195);
      SendDlgItemMessageA(hWnd, 1000, 0xC5u, 0x104u, 0);
      v10 = GetModuleHandleA(0);
      LoadStringA(v10, 0x64u, Buffer, 512);
      SetDlgItemTextA(hWnd, 1000, Buffer);
      SendDlgItemMessageA(hWnd, 1000, 0xB1u, 0, 16777472);
      v11 = GetDlgItem(hWnd, 1000);
      SetFocus(v11);
      return 0;
    case 0x111u:
      if ( a3 != 1 )
      {
        if ( a3 == 2 )
        {
          if ( !dword_40B808 )
            EndDialog(hWnd, -1);
        }
        else if ( a3 == 1011 && !dword_40B804 )
        {
          bi.hwndOwner = hWnd;
          bi.pidlRoot = 0;
          bi.pszDisplayName = (LPSTR)String;
          bi.lpszTitle = 0;
          bi.ulFlags = 1;
          memset(&bi.lpfn, 0, 12);
          v68 = SHBrowseForFolderA(&bi);
          if ( v68 )
          {
            SHGetPathFromIDListA(v68, (LPSTR)String);
            SetDlgItemTextA(hWnd, 1000, (LPCSTR)String);
            sub_4010F0(v68);
          }
        }
        return 0;
      }
      if ( dword_40B808 > 0 )
        return 0;
      if ( dword_40B804 )
      {
        if ( dword_40B804 != 1 )
          return 0;
        v72 = 0;
        if ( dword_40BC28 )
        {
          ExitWindowsEx(2u, 0);
          return 0;
        }
        v12 = hWnd;
        goto LABEL_58;
      }
      v12 = hWnd;
      ++dword_40B808;
      v13 = GetDlgItem(hWnd, 1);
      EnableWindow(v13, 0);
      v14 = GetDlgItem(hWnd, 2);
      EnableWindow(v14, 0);
      v15 = LoadCursorA(0, (LPCSTR)0x7F02);
      SetCursor(v15);
      v16 = GetDlgItem(hWnd, 1000);
      GetWindowTextA(v16, &::String, 262);
      _strupr(&::String);
      if ( !strstr(&::String, SubStr) )
      {
        strcat(&::String, SubStr);
        strcat(&::String, byte_40A54C);
      }
      sub_4022C0(hWnd, 1011, 0);
      v17 = GetModuleHandleA(0);
      LoadStringA(v17, 0x78u, Buffer, 512);
      sub_4010B0(hWnd, Buffer);
      GetWindowsDirectoryA(v86, 0x104u);
      sub_401000(v86, aWinIni);
      lstrcpyA(String1, &::String);
      sub_401000(String1, aSmagIni);
      FileOp.hwnd = hWnd;
      FileOp.pFrom = v86;
      FileOp.pTo = String1;
      FileOp.wFunc = 2;
      FileOp.fFlags = 20;
      if ( SHFileOperationA(&FileOp) )
      {
        sub_4010B0(hWnd, byte_40A534);
        v18 = GetDlgItem(hWnd, 1);
        EnableWindow(v18, 1);
        v19 = GetDlgItem(hWnd, 2);
        EnableWindow(v19, 1);
        --dword_40B808;
        return 0;
      }
      FileOp.hwnd = hWnd;
      FileOp.pFrom = String1;
      FileOp.wFunc = 3;
      FileOp.pTo = 0;
      FileOp.fFlags = 20;
      SHFileOperationA(&FileOp);
      sub_4010B0(hWnd, byte_40A534);
      if ( dword_40A048 )
      {
        v23 = String[0];
        v22 = (void (__stdcall *)(HWND, LPCSTR, LPCSTR, UINT))MessageBoxA;
      }
      else
      {
        dword_40A048 = 1;
        v20 = GetModuleHandleA(0);
        LoadStringA(v20, 0x6Eu, Text, 512);
        v21 = GetModuleHandleA(0);
        LoadStringA(v21, 0x6Fu, Caption, 512);
        v22 = (void (__stdcall *)(HWND, LPCSTR, LPCSTR, UINT))MessageBoxA;
        v23 = MessageBoxA(hWnd, Text, Caption, 4u);
        sub_4010B0(hWnd, byte_40A534);
        if ( v23 == 6 )
        {
          v24 = GetModuleHandleA(0);
          LoadStringA(v24, 0x79u, Buffer, 512);
          sub_4010B0(hWnd, Buffer);
          v25 = GetModuleHandleA(0);
          LoadStringA(v25, 0x81u, Buffer, 512);
          *(_QWORD *)String = atoi(Buffer) << 20;
          GetDiskFreeSpaceA(
            ::RootPathName,
            &SectorsPerCluster,
            &BytesPerSector,
            &NumberOfFreeClusters,
            &TotalNumberOfClusters);
          *(_QWORD *)&bi.hwndOwner = NumberOfFreeClusters * (unsigned __int64)BytesPerSector * SectorsPerCluster;
          if ( *(__int64 *)&bi.hwndOwner < *(__int64 *)String )
          {
            v26 = GetModuleHandleA(0);
            LoadStringA(v26, 0x6Cu, Text, 512);
            sprintf(
              v94,
              Text,
              (unsigned int)(*(_QWORD *)String / 1024LL),
              (unsigned int)(*(_QWORD *)&bi.hwndOwner / 1024LL));
            v27 = GetModuleHandleA(0);
            LoadStringA(v27, 0x6Du, Caption, 512);
            MessageBoxA(hWnd, v94, Caption, 0);
LABEL_57:
            v72 = -1;
LABEL_58:
            EndDialog(v12, v72);
            return 0;
          }
          v28 = GetModuleHandleA(0);
          LoadStringA(v28, 0x7Au, Buffer, 512);
          sub_4010B0(hWnd, Buffer);
          v23 = DirectXSetupA(hWnd, 0, 268438079);
          sub_4010B0(hWnd, byte_40A534);
          if ( v23 < 0 )
          {
            if ( v23 == -13 )
              v71 = 128;
            else
              v71 = 123;
            v29 = GetModuleHandleA(0);
            LoadStringA(v29, v71, Buffer, 512);
            MessageBoxA(hWnd, Buffer, ::Caption, 0);
            EndDialog(hWnd, v23);
            return 0;
          }
        }
      }
      v30 = GetModuleHandleA(0);
      LoadStringA(v30, 0x82u, Buffer, 512);
      *(_QWORD *)String = atoi(Buffer) << 20;
      if ( byte_40BB21 == 58 && byte_40BB22 == 92 )
      {
        RootPathName[0] = ::String;
        RootPathName[1] = byte_40BB21;
        strcpy(v74, "\\");
        GetDiskFreeSpaceA(
          RootPathName,
          &SectorsPerCluster,
          &BytesPerSector,
          &NumberOfFreeClusters,
          &TotalNumberOfClusters);
        *(_QWORD *)&bi.hwndOwner = NumberOfFreeClusters * (unsigned __int64)BytesPerSector * SectorsPerCluster;
      }
      else
      {
        bi.hwndOwner = (HWND)104857600;
        bi.pidlRoot = 0;
      }
      if ( *(__int64 *)&bi.hwndOwner < *(__int64 *)String )
      {
        v31 = GetModuleHandleA(0);
        LoadStringA(v31, 0x70u, Text, 512);
        sprintf(
          v94,
          Text,
          (unsigned int)(*(_QWORD *)String / 1024LL),
          (unsigned int)(*(_QWORD *)&bi.hwndOwner / 1024LL));
        v32 = GetModuleHandleA(0);
        LoadStringA(v32, 0x71u, Caption, 512);
        v22(hWnd, v94, Caption, 0);
        v33 = GetDlgItem(hWnd, 1);
        EnableWindow(v33, 1);
        v34 = GetDlgItem(hWnd, 2);
        EnableWindow(v34, 1);
        v35 = LoadCursorA(0, (LPCSTR)0x7F00);
        SetCursor(v35);
        sub_4022C0(hWnd, 1011, 1);
        --dword_40B808;
        return 0;
      }
      v36 = GetModuleHandleA(0);
      LoadStringA(v36, 0x79u, Buffer, 512);
      sub_4010B0(hWnd, Buffer);
      sub_4010B0(hWnd, byte_40A534);
      dword_40BC28 = v23 == 0;
      v37 = GetModuleHandleA(0);
      LoadStringA(v37, 0x7Cu, Buffer, 512);
      v38 = (LPCSTR *)off_40A050;
      sub_4010B0(hWnd, Buffer);
      do
      {
        lstrcpyA(v86, &sz);
        sub_401000(v86, *v38);
        lstrcpyA(String1, &::String);
        sub_401000(String1, *v38);
        v39 = GetModuleHandleA(0);
        LoadStringA(v39, 0x7Du, Buffer, 512);
        sub_4010B0(hWnd, Buffer, *v38);
        FileOp.hwnd = hWnd;
        FileOp.pFrom = v86;
        FileOp.pTo = String1;
        FileOp.fFlags = 532;
        FileOp.wFunc = 2;
        while ( SHFileOperationA(&FileOp) )
        {
          v40 = GetModuleHandleA(0);
          LoadStringA(v40, 0x7Eu, Buffer, 512);
          wsprintfA((LPSTR)String, Buffer, *v38);
          if ( ((int (__stdcall *)(HWND, LPCSTR, LPCSTR, UINT))v22)(hWnd, (LPCSTR)String, ::Caption, 5u) == 2 )
            goto LABEL_37;
        }
        SetFileAttributesA(String1, 0x80u);
LABEL_37:
        ++v38;
      }
      while ( v38 < (LPCSTR *)&hKey );
      sub_4010B0(hWnd, byte_40A534);
      v41 = GetModuleHandleA(0);
      LoadStringA(v41, 0x7Fu, Buffer, 512);
      sub_4010B0(hWnd, Buffer);
      String[0] = RegCreateKeyExA(HKEY_LOCAL_MACHINE, SubKey, 0, 0, 0, 0xF003Fu, 0, &hKey, &dwDisposition);
      if ( String[0] )
        exit(1);
      strcpy((char *)Data, &::String);
      RegSetValueExA(hKey, ValueName, 0, 1u, Data, strlen((const char *)Data));
      RegCloseKey(hKey);
      hKey = 0;
      v42 = GetModuleHandleA(0);
      LoadStringA(v42, 0x66u, v95, 512);
      SHGetSpecialFolderLocation(0, 2, &ppidl);
      SHGetPathFromIDListA(ppidl, pszPath);
      wsprintfA(PathName, "%s\\%s", pszPath, v95);
      strcat(PathName, SrcStr);
      CreateDirectoryA(PathName, 0);
      SHChangeNotify(8, 1u, PathName, 0);
      wsprintfA(v89, "%s\\%s", &::String, off_40A050[0]);
      v43 = GetModuleHandleA(0);
      LoadStringA(v43, 0x67u, v87, 260);
      wsprintfA(MultiByteStr, "%s\\%s.lnk", PathName, v87);
      sub_402360((int)v89, MultiByteStr, (int)byte_40A534, (int)&::String);
      wsprintfA(v89, "%s\\%s", &::String, off_40A054[0]);
      v44 = GetModuleHandleA(0);
      LoadStringA(v44, 0x68u, v87, 260);
      wsprintfA(MultiByteStr, "%s\\%s.lnk", PathName, v87);
      sub_402360((int)v89, MultiByteStr, (int)byte_40A534, (int)&::String);
      wsprintfA(v89, "%s\\%s", &::String, off_40A058[0]);
      v45 = GetModuleHandleA(0);
      LoadStringA(v45, 0x69u, v87, 260);
      wsprintfA(MultiByteStr, "%s\\%s.lnk", PathName, v87);
      sub_402360((int)v89, MultiByteStr, (int)byte_40A534, (int)byte_40A534);
      sub_4010B0(hWnd, byte_40A534);
      if ( String[0] >= 0 )
      {
        v46 = GetDlgItem(hWnd, 1000);
        ShowWindow(v46, 0);
        v47 = GetDlgItem(hWnd, 1005);
        ShowWindow(v47, 0);
        v48 = GetDlgItem(hWnd, 1006);
        ShowWindow(v48, 0);
        v49 = GetDlgItem(hWnd, 1001);
        ShowWindow(v49, 0);
        v50 = GetDlgItem(hWnd, 1009);
        ShowWindow(v50, 0);
        v51 = GetDlgItem(hWnd, 1011);
        ShowWindow(v51, 0);
        if ( !dword_40BC28 )
        {
          v63 = GetModuleHandleA(0);
          LoadStringA(v63, 0x3EDu, Buffer, 512);
          SetDlgItemTextA(hWnd, 1006, Buffer);
          v64 = GetDlgItem(hWnd, 1006);
          ShowWindow(v64, 5);
          v65 = GetModuleHandleA(0);
          LoadStringA(v65, 0x74u, Buffer, 512);
          v66 = GetDlgItem(hWnd, 1);
          SetWindowTextA(v66, Buffer);
          ++dword_40B804;
          v67 = GetDlgItem(hWnd, 1);
          EnableWindow(v67, 1);
          --dword_40B808;
          return 0;
        }
        v52 = GetModuleHandleA(0);
        LoadStringA(v52, 0x3EBu, Buffer, 512);
        SetDlgItemTextA(hWnd, 1005, Buffer);
        v53 = GetDlgItem(hWnd, 1005);
        ShowWindow(v53, 5);
        v54 = GetModuleHandleA(0);
        LoadStringA(v54, 0x3ECu, Buffer, 512);
        SetDlgItemTextA(hWnd, 1006, Buffer);
        v55 = GetDlgItem(hWnd, 1006);
        ShowWindow(v55, 5);
        v56 = GetModuleHandleA(0);
        LoadStringA(v56, 0x75u, Buffer, 512);
        v57 = GetDlgItem(hWnd, 1);
        SetWindowTextA(v57, Buffer);
        v58 = GetModuleHandleA(0);
        LoadStringA(v58, 0x83u, Buffer, 512);
        v59 = GetDlgItem(hWnd, 2);
        SetWindowTextA(v59, Buffer);
        v60 = GetModuleHandleA(0);
        LoadStringA(v60, 0x77u, Buffer, 512);
        sub_401050(hWnd, 1002, Buffer, 270, 195);
        ++dword_40B804;
      }
      v61 = GetDlgItem(hWnd, 1);
      EnableWindow(v61, 1);
      v62 = GetDlgItem(hWnd, 2);
      EnableWindow(v62, 1);
      --dword_40B808;
      if ( String[0] < 0 )
        EndDialog(hWnd, String[0]);
      return 0;
    case 0x112u:
      if ( a3 == 61536 )
      {
        v69 = GetModuleHandleA(0);
        LoadStringA(v69, 0x6Au, Text, 512);
        v70 = GetModuleHandleA(0);
        LoadStringA(v70, 0x6Bu, Caption, 512);
        v12 = hWnd;
        if ( MessageBoxA(hWnd, Text, Caption, 4u) == 6 )
          goto LABEL_57;
      }
      return 0;
    default:
      return 0;
  }
}
// 40242C: using guessed type int __stdcall DirectXSetupA(_DWORD, _DWORD, _DWORD);
// 40A048: using guessed type int dword_40A048;
// 40A050: using guessed type char *off_40A050[294];
// 40A054: using guessed type char *off_40A054[293];
// 40A058: using guessed type char *off_40A058[292];
// 40B804: using guessed type int dword_40B804;
// 40B808: using guessed type int dword_40B808;
// 40BB21: using guessed type char byte_40BB21;
// 40BB22: using guessed type char byte_40BB22;
// 40BC28: using guessed type int dword_40BC28;

//----- (004022C0) --------------------------------------------------------
BOOL __cdecl sub_4022C0(HWND hDlg, int nIDDlgItem, BOOL bEnable)
{
  HWND DlgItem; // eax

  DlgItem = GetDlgItem(hDlg, nIDDlgItem);
  return EnableWindow(DlgItem, bEnable);
}

//----- (004022E0) --------------------------------------------------------
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{
  CHAR *v4; // esi
  LPSTR v5; // eax

  v4 = &sz;
  hInst = hInstance;
  GetModuleFileNameA(hInstance, &sz, 0x104u);
  v5 = &sz;
  if ( sz )
  {
    do
    {
      if ( *v5 == 92 || *v5 == 47 )
        v4 = v5;
      v5 = CharNextA(v5);
    }
    while ( *v5 );
  }
  *v4 = 0;
  CoInitialize(0);
  DialogBoxParamA(hInstance, TemplateName, 0, DialogFunc, 0);
  CoUninitialize();
  return 0;
}

//----- (00402360) --------------------------------------------------------
int __cdecl sub_402360(int a1, LPCCH lpMultiByteStr, int a3, int a4)
{
  HRESULT v4; // esi
  int result; // eax
  LPVOID ppv; // [esp+34h] [ebp-210h] BYREF
  int v7; // [esp+38h] [ebp-20Ch] BYREF
  WCHAR WideCharStr[260]; // [esp+3Ch] [ebp-208h] BYREF

  v4 = CoCreateInstance(&rclsid, 0, 1u, &riid, &ppv);
  if ( v4 >= 0 )
  {
    (*(void (__stdcall **)(LPVOID, int))(*(_DWORD *)ppv + 80))(ppv, a1);
    (*(void (__stdcall **)(LPVOID, int))(*(_DWORD *)ppv + 28))(ppv, a3);
    (*(void (__stdcall **)(LPVOID, int))(*(_DWORD *)ppv + 36))(ppv, a4);
    v4 = (**(int (__stdcall ***)(LPVOID, void *, int *))ppv)(ppv, &unk_407360, &v7);
    if ( v4 >= 0 )
    {
      MultiByteToWideChar(0, 0, lpMultiByteStr, -1, WideCharStr, 260);
      result = (*(int (__stdcall **)(int, WCHAR *, int))(*(_DWORD *)v7 + 24))(v7, WideCharStr, 1);
      v4 = result;
      if ( result < 0 )
        return result;
      (*(void (__stdcall **)(int))(*(_DWORD *)v7 + 8))(v7);
    }
    (*(void (__stdcall **)(LPVOID))(*(_DWORD *)ppv + 8))(ppv);
  }
  return v4;
}

// nfuncs=102 queued=8 decompiled=8 lumina nreq=0 worse=0 better=0
// ALL OK, 8 function(s) have been successfully decompiled
