// Generated by Rec Studio 4 - build Sep 23 2015

L004022E0(
    _unknown_ __ecx,                       // r2
    intOrPtr _a4                           // _cfa_4
)
{
    intOrPtr* __ebx;                       // r1
    intOrPtr __edi;                        // r4
    char* __esi;                           // r5
    intOrPtr _t5;                          // _t5

    __esi = 4241944;
    __edi = _a4;
    _push(260);
    _push(4241944);
     *4241936 = __edi;
    _push(__edi);
    __imp__GetModuleFileNameA();
    if( *4241944 == 0) {
L6:
        _push(0);
         *__esi = 0;
        __imp__CoInitialize();
        _push(0);
        _push(4198704);
        _push(0);
        _push("DLG_MASTER");
        _push(__edi);
        __imp__DialogBoxParamA();
        __imp__CoUninitialize();
        return;
    }
    __ebx = __imp__CharNextA;
    do {
        _t5 =  *4241944;
        if(_t5 == 92 || _t5 == 47) {
            __esi = 4241944;
        }
        _push(4241944);
         *__ebx();
    } while( *4241944 != 0);
    goto L6;
}

L00402440()
{
    __eax =  *4247408;
    if(__eax != 0) {
         *__eax();
    }
    L00402560(4227080, 4227088);
    L00402560(4227072, 4227076);
}

L00402470(
    intOrPtr _a4                           // _cfa_4
)
{
    __eax = _a4;
    L004024B0(__eax, 0, 0);
    return __eax;
}

L004024B0(
    intOrPtr _a4,                          // _cfa_4
    intOrPtr _a8,                          // _cfa_8
    char _a12                              // _cfa_c
)
{
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    _unknown_ _t4;                         // _t4
    char _t5;                              // _t5
    intOrPtr* _t6;                         // _t6
    _unknown_ _t8;                         // _t8
    intOrPtr _t9;                          // _t9

    _push(_t4);
    _push(_t8);
    _t9 = _a4;
    _push(_t6);
    if( *4236736 == 1) {
        _push(_t9);
        __imp__GetCurrentProcess();
        _push(__eax);
        __imp__TerminateProcess();
    }
     *4236732 = 1;
    _t5 = _a12;
     *4236728 = _t5;
    if(_a8 == 0) {
        if( *4247404 != 0) {
            _t6 =  *4247400 - 4;
            while(_t6 >=  *4247404) {
                __eax =  *_t6;
                if(__eax != 0) {
                     *__eax();
                }
                _t6 = _t6 - 4;
            }
        }
        L00402560(4227092, 4227100);
    }
    L00402560(4227104, 4227108);
    if(_t5 == 0) {
         *4236736 = 1;
        _push(_t9);
        __imp__ExitProcess();
    }
    _pop(__edi);
    _pop(__esi);
    _pop(__ebx);
}

L00402560(
    intOrPtr* _a4,                         // _cfa_4
    intOrPtr _a8                           // _cfa_8
)
{
    intOrPtr __edi;                        // r4
    intOrPtr* __esi;                       // r5

    __edi = _a8;
    __esi = _a4;
    while(__edi > __esi) {
        __eax =  *__esi;
        if(__eax != 0) {
             *__eax();
        }
        __esi = __esi + 4;
    }
}

L004029F0(
    intOrPtr _a4                           // _cfa_4
)
{
    _unknown_ _t3;                         // _t3

    if( *4236764 == 1) {
        L00404550();
    }
    _t3 = L00404590(_a4);
    _push(255);
     *4236760();
    __esp = __esp + 4;
    return _t3;
}

L00403A20(
    intOrPtr _a4                           // _cfa_4
)
{
    return L00403A40(_a4, 0, 4);
}

L00403A40(
    _unknown_ _a4,                         // _cfa_4
    signed int _a8,                        // _cfa_8
    signed int _a12                        // _cfa_c
)
{
    signed int _t10;                       // _t10
    signed int _t14;                       // _t14

    if((_a12 & 0) != 0) {
L5:
        return 1;
    } else {
        _t10 = _a8;
        _t14 = 0;
        if(_t10 != 0) {
            _t14 = 0 & _t10;
        }
        if(_t14 != 0) {
            goto L5;
        } else {
            return 0;
        }
    }
}

L00403A80()
{
    intOrPtr _v4;                          // _cfa_fffffffc
    intOrPtr* __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    char* __ebp;                           // r6
    intOrPtr* _t8;                         // _t8
    _unknown_ _t11;                        // _t11
    intOrPtr _t13;                         // _t13
    signed int _t20;                       // _t20
    intOrPtr _t33;                         // _t33
    signed int _t39;                       // _t39
    _unknown_ _t40;                        // _t40

    __edx =  *4236752;
    _t39 = 0;
    while( *__edx != 0) {
        if( *__edx != 61) {
            _t39 = _t39 + 1;
        }
        asm("repne scasb");
        __edx = __edx +  !-1;
    }
    _t8 = L00404F00(4 + _t39 * 4);
     *4236704 = _t8;
    __ebx = _t8;
    if(__ebx == 0) {
        L004029F0(9);
    }
    __ebp =  *4236752;
    while( *__ebp != 0) {
        asm("repne scasb");
        _t20 =  !-1;
        _v4 = -1;
        if( *__ebp != 61) {
            _t13 = L00404F00(_t20);
             *__ebx = _t13;
            if(_t13 == 0) {
                L004029F0(9);
            }
            asm("repne scasb");
            _t40 = __ebp - -1;
            _t33 =  *__ebx;
            __ebx = __ebx + 4;
            _push(-1 << 2);
            _push(_t40);
            _push(_t33);
            memcpy();
            __esp = __esp + 12;
            _push(3 << 0);
            _push(_t40);
            _push(_t40 + -1 + ( !-1 >> 2));
            memcpy();
            __esp = __esp + 12;
        }
        __ebp = __ebp + _v4;
    }
    _t11 = L00404EB0( *4236752);
     *4236752 = 0;
     *__ebx = 0;
    return _t11;
}

signed int L00403B70()
{
    char _v16;                             // _cfa_fffffff0
    signed int _v20;                       // _cfa_ffffffec
    _unknown_ __edi;                       // r4
    intOrPtr __esi;                        // r5
    signed int _t22;                       // _t22
    _unknown_ _t26;                        // _t26
    intOrPtr _t27;                         // _t27

    _push(_t26);
    _push(260);
    __esi = 4242744;
    _push(4242744);
    _push(0);
    __imp__GetModuleFileNameA();
     *4236720 = 4242744;
    if( *((char*)( *4247396)) != 0) {
        __esi =  *4247396;
    }
    _push( &_v16);
    _push( &_v20);
    _push(0);
    _push(0);
    _push(__esi);
    L00403C10();
    __esp = __esp + 20;
    _t27 = L00404F00((_v20 << 2) + _v16);
    if(_t27 == 0) {
        L004029F0(8);
    }
    _push( &_v16);
    _push( &_v20);
    _push(_t27 + _v20 * 4);
    _push(_t27);
    _push(__esi);
    L00403C10();
    __esp = __esp + 20;
    _t22 = _v20 - 1;
     *4236696 = _t27;
    _pop(__edi);
     *4236692 = _t22;
    return _t22;
}

L00403C10()
{
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    intOrPtr* _t40;                        // _t40
    intOrPtr* _t41;                        // _t41
    intOrPtr _t43;                         // _t43
    char _t46;                             // _t46
    intOrPtr* _t47;                        // _t47
    char _t48;                             // _t48
    unsigned int _t49;                     // _t49
    char _t55;                             // _t55
    _unknown_ _t58;                        // _t58
    signed int _t59;                       // _t59
    _unknown_ _t60;                        // _t60
    intOrPtr* _t61;                        // _t61
    intOrPtr* _t62;                        // _t62
    unsigned int _t63;                     // _t63
    unsigned int _t64;                     // _t64

    __ecx =  *((intOrPtr*)(__esp + 20));
    _push(_t34);
    _t40 =  *((intOrPtr*)(__esp + 20));
    _push(_t60);
    _t61 =  *((intOrPtr*)(__esp + 12));
    _push(_t58);
    __eax =  *((intOrPtr*)(__esp + 24));
    _push(_t63);
     *__ecx = 0;
     *_t40 = 1;
    if( *((intOrPtr*)(__esp + 24)) != 0) {
         *((intOrPtr*)(__esp + 24)) =  *((intOrPtr*)(__esp + 24)) + 4;
         *((intOrPtr*)( *((intOrPtr*)(__esp + 24)))) = __eax;
    }
    if( *_t61 == 34) {
        _t62 = _t61 + 1;
        if( *_t62 == 34) {
L24:
             *__ecx =  *__ecx + 1;
            if(__eax != 0) {
                 *__eax = 0;
                __eax = __eax + 1;
            }
            if( *_t62 == 34) {
                _t62 = _t62 + 1;
            }
L28:
            _t59 = 0;
L29:
            while( *_t62 != 0) {
                while(1) {
                    _t43 =  *_t62;
                    if(_t43 != 32 && _t43 != 9) {
                        break;
                    }
                    _t62 = _t62 + 1;
                }
                if( *_t62 == 0) {
                    break;
                }
                if( *((intOrPtr*)(__esp + 24)) != 0) {
                     *((intOrPtr*)(__esp + 24)) =  *((intOrPtr*)(__esp + 24)) + 4;
                     *((intOrPtr*)( *((intOrPtr*)(__esp + 24)))) = __eax;
                }
                 *((intOrPtr*)( *((intOrPtr*)(__esp + 32)))) =  *((intOrPtr*)( *((intOrPtr*)(__esp + 32)))) + 1;
                while(1) {
                    _t34 = 1;
                    _t64 = 0;
                    if( *_t62 != 92) {
                        goto L39;
                    }
                    do {
L38:
                        _t62 = _t62 + 1;
                        _t64 = _t64 + 1;
                    } while( *_t62 == 92);
L39:
                    if( *_t62 != 34) {
L47:
                        _t63 = _t64 - 1;
                        if(_t64 == 0) {
L51:
                            _t46 =  *_t62;
                            if(_t46 == 0 || _t59 == 0 && (_t46 == 32 || _t46 == 9)) {
                                if(__eax != 0) {
                                     *__eax = 0;
                                    __eax = __eax + 1;
                                }
                                 *__ecx =  *__ecx + 1;
                                goto L29;
                            } else {
                                if(_t34 == 0) {
L63:
                                    _t62 = _t62 + 1;
                                    while(1) {
                                        _t34 = 1;
                                        _t64 = 0;
                                        if( *_t62 != 92) {
                                            goto L39;
                                        }
                                        goto L38;
                                    }
                                }
                                if(__eax == 0) {
                                    if(( *0x0040A8B9 & 4) != 0) {
                                        _t62 = _t62 + 1;
                                         *__ecx =  *__ecx + 1;
                                    }
                                     *__ecx =  *__ecx + 1;
                                    goto L63;
                                }
                                if(( *0x0040A8B9 & 4) != 0) {
                                     *__eax = _t46;
                                    _t62 = _t62 + 1;
                                    __eax = __eax + 1;
                                     *__ecx =  *__ecx + 1;
                                }
                                _t48 =  *_t62;
                                __eax = __eax + 1;
                                _t62 = _t62 + 1;
                                 *((char*)(__eax - 1)) = _t48;
                                 *__ecx =  *__ecx + 1;
                                _t34 = 1;
                                _t64 = 0;
                                if( *_t62 != 92) {
                                    goto L39;
                                }
                                goto L38;
                            }
                        } else {
                            goto L48;
                        }
                        do {
L48:
                            if(__eax != 0) {
                                 *__eax = 92;
                                __eax = __eax + 1;
                            }
                            _t49 = _t63;
                             *__ecx =  *__ecx + 1;
                            _t63 = _t63 - 1;
                        } while(_t49 != 0);
                        goto L51;
                    }
                    if((_t64 & 1) != 0) {
L46:
                        _t64 = _t64 >> 1;
                        goto L47;
                    }
                    if(_t59 == 0) {
L44:
                        _t34 = 0;
L45:
                        asm("sbb edi, edi");
                        _t59 =  ~_t59;
                        goto L46;
                    }
                    _t47 = _t62 + 1;
                    if( *_t47 != 34) {
                        goto L44;
                    }
                    _t62 = _t47;
                    goto L45;
                }
            }
            if( *((intOrPtr*)(__esp + 24)) != 0) {
                 *((intOrPtr*)( *((intOrPtr*)(__esp + 24)))) = 0;
            }
            _t41 =  *((intOrPtr*)(__esp + 32));
            _pop(__ebp);
            _pop(__edi);
            _pop(__esi);
            _pop(__ebx);
             *_t41 =  *_t41 + 1;
            return __eax;
        } else {
            goto L17;
        }
        while(1) {
L17:
            _t34 =  *_t62;
            if( *_t62 == 0) {
                goto L24;
            }
            if(( *0x0040A8B9 & 4) != 0) {
                 *__ecx =  *__ecx + 1;
                if(__eax != 0) {
                    _t62 = _t62 + 1;
                     *__eax = 0;
                    __eax = __eax + 1;
                }
            }
             *__ecx =  *__ecx + 1;
            if(__eax != 0) {
                 *__eax =  *_t62;
                __eax = __eax + 1;
            }
            _t62 = _t62 + 1;
            if( *_t62 != 34) {
                continue;
            } else {
                goto L24;
            }
        }
        goto L24;
    } else {
        goto L3;
    }
    do {
L3:
         *__ecx =  *__ecx + 1;
        if(__eax != 0) {
             *__eax =  *_t62;
            __eax = __eax + 1;
        }
        _t55 =  *_t61;
        _t62 = _t61 + 1;
        _t34 = _t55;
        if(( *0x0040A8B9 & 4) != 0) {
             *__ecx =  *__ecx + 1;
            if(__eax != 0) {
                _t34 =  *_t62;
                 *__eax =  *_t62;
                __eax = __eax + 1;
            }
            _t62 = _t62 + 1;
        }
        if(_t55 == 32) {
            break;
        }
        if(_t55 == 0) {
L13:
            _t62 = _t62 - 1;
            goto L28;
        }
    } while(_t55 != 9);
    if(_t55 != 0) {
        if(__eax != 0) {
             *((char*)(__eax - 1)) = 0;
        }
        goto L28;
    }
    goto L13;
}

L00403DF0(
    signed int __eax                       // r0
)
{
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    signed int _t15;                       // _t15
    signed int _t18;                       // _t18
    signed int _t21;                       // _t21
    signed int _t23;                       // _t23
    intOrPtr _t24;                         // _t24
    intOrPtr* _t29;                        // _t29
    signed int _t30;                       // _t30
    short* _t31;                           // _t31
    _unknown_ _t34;                        // _t34
    signed int _t35;                       // _t35
    signed int _t37;                       // _t37

    _t15 = 0;
    _t23 = 0;
    _t29 = __imp__GetEnvironmentStringsW;
    if( *4237488 != 0) {
L6:
        if( *4237488 != 1) {
            __eflags =  *4237488 - 2;
            if( *4237488 != 2) {
                __eflags = 0;
                return;
            } else {
                __eflags = _t15;
                if(_t15 != 0) {
L23:
                    _t35 = _t15;
                    __eflags =  *_t15;
                    if( *_t15 != 0) {
                        goto L24;
                        do {
                            do {
L24:
                                _t35 = _t35 + 1;
                                __eflags =  *_t35;
                            } while( *_t35 != 0);
                            _t35 = _t35 + 1;
                            __eflags =  *_t35;
                        } while( *_t35 != 0);
                    }
                    _t37 = _t35 - _t15 + 1;
                    _push(_t37);
                    L00404F00();
                     *((intOrPtr*)(__esp + 20)) = __eax;
                    __esp = __esp + 4;
                    __eflags = __eax;
                    if(__eax != 0) {
                        _t24 =  *((intOrPtr*)(__esp + 16));
                        _t30 = _t15;
                        _t18 = _t37 >> 2;
                        _push(_t18 << 2);
                        _push(_t30);
                        _push(_t24);
                        memcpy();
                        __esp = __esp + 12;
                        _push(_t15);
                        _t21 = _t37 & 3;
                        __eflags = _t21;
                        _push(_t21 << 0);
                        _push(_t30);
                        _push(_t30 + _t18 + _t18);
                        memcpy();
                        __esp = __esp + 12;
                        __imp__FreeEnvironmentStringsA();
                        return;
                    } else {
                        _push(_t15);
                        __imp__FreeEnvironmentStringsA();
                        __eflags = 0;
                        return;
                    }
                } else {
                    __imp__GetEnvironmentStrings();
                    _t15 = __eax;
                    __eflags = __eax;
                    if(__eax != 0) {
                        goto L23;
                    } else {
                        __eflags = 0;
                        return;
                    }
                }
            }
        } else {
            if(_t23 != 0) {
L10:
                __eflags =  *_t23;
                _t31 = _t23;
                if( *_t23 != 0) {
                    goto L11;
                    do {
                        do {
L11:
                            _t31 = _t31 + 2;
                            __eflags =  *_t31;
                        } while( *_t31 != 0);
                        _t31 = _t31 + 2;
                        __eflags =  *_t31;
                    } while( *_t31 != 0);
                }
                _push(0);
                _push(0);
                _t34 = (_t31 - _t23 >> 1) + 1;
                _push(0);
                _push(0);
                _push(_t34);
                _push(_t23);
                _push(0);
                _push(0);
                __imp__WideCharToMultiByte();
                __eflags = __eax;
                if(__eax == 0) {
L18:
                    _push(_t23);
                    __imp__FreeEnvironmentStringsW();
                    __eflags = 0;
                    return;
                } else {
                    L00404F00(__eax);
                    __eflags = __eax;
                    if(__eax == 0) {
                        goto L18;
                    } else {
                        _push(0);
                        _push(0);
                        _push(__eax);
                        _push(__eax);
                        _push(_t34);
                        _push(_t23);
                        _push(0);
                        _push(0);
                        __imp__WideCharToMultiByte();
                        __eflags = __eax;
                        if(__eflags == 0) {
                            L00404EB0(__eax);
                            __eflags = 0;
                        }
                        _push(_t23);
                        __imp__FreeEnvironmentStringsW();
                        return;
                    }
                }
            } else {
                 *_t29();
                _t23 = __eax;
                if(__eax != 0) {
                    goto L10;
                } else {
                    return;
                }
            }
        }
    } else {
         *_t29();
        _t23 = __eax;
        if(__eax == 0) {
            __imp__GetEnvironmentStrings();
            _t15 = __eax;
            __eflags = __eax;
            if(__eflags == 0) {
                __eflags = 0;
                return;
            } else {
                 *4237488 = 2;
                goto L6;
            }
        } else {
             *4237488 = 1;
            goto L6;
        }
    }
}

L00403F80(
    intOrPtr _a4                           // _cfa_4
)
{
    char _v20;                             // _cfa_ffffffec
    char _v22;                             // _cfa_ffffffea
    signed int _v24;                       // _cfa_ffffffe8
    intOrPtr _v28;                         // _cfa_ffffffe4
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    _unknown_ __ebp;                       // r6
    intOrPtr* _t43;                        // _t43
    _unknown_ _t44;                        // _t44
    signed int _t47;                       // _t47
    intOrPtr _t55;                         // _t55
    _unknown_ _t57;                        // _t57
    _unknown_ _t64;                        // _t64
    intOrPtr* _t74;                        // _t74
    signed char _t77;                      // _t77
    char _t82;                             // _t82
    char _t86;                             // _t86
    _unknown_ _t89;                        // _t89
    signed int _t92;                       // _t92
    char* _t95;                            // _t95
    char* _t96;                            // _t96
    _unknown_ _t97;                        // _t97
    intOrPtr _t98;                         // _t98

    __esp = __esp - 24;
    _push(_t64);
    _push(_t95);
    _push(_t89);
    _push(_t97);
    _t98 = L00404160(_a4);
    if(_t98 !=  *4237756) {
        if(_t98 != 0) {
            _v24 = 0;
            _t43 = 4237792;
            while( *_t43 != _t98) {
                _t43 = _t43 + 48;
                _v24 = _v24 + 1;
                if(_t43 < 4238032) {
                    continue;
                } else {
                    _push( &_v20);
                    _push(_t98);
                    __imp__GetCPInfo();
                    if( &_v20 != 1) {
                        if( *4237780 == 0) {
                            _pop(__ebp);
                            _pop(__edi);
                            _pop(__esi);
                            _pop(__ebx);
                            __esp = __esp + 24;
                            return -1;
                        } else {
                            L00404210();
                            _pop(__ebp);
                            _pop(__edi);
                            _pop(__esi);
                            _pop(__ebx);
                            __esp = __esp + 24;
                            return 0;
                        }
                    } else {
                        _push(64 << 2);
                        _push(0);
                        _push(4237496);
                        memset();
                        __esp = __esp + 12;
                        asm("stosb");
                        if(_v28 <= 1) {
                            _t55 = 0;
                             *4237756 = 0;
                        } else {
                            _t95 =  &_v22;
                            if(_v22 != 0) {
                                while( *((intOrPtr*)(_t95 + 1)) != 0) {
                                    _t82 =  *_t95;
                                    if(0 >= 0) {
                                        do {
                                             *(_t82 + 4237497) =  *(_t82 + 4237497) | 4;
                                            _t82 = _t82 + 1;
                                        } while(0 >= _t82);
                                    }
                                    _t95 = _t95 + 2;
                                    if( *_t95 != 0) {
                                        continue;
                                    }
                                    goto L14;
                                }
                            }
L14:
                            _t57 = 1;
                            do {
                                 *(_t57 + 4237497) =  *(_t57 + 4237497) | 8;
                                _t57 = _t57 + 1;
                            } while(_t57 < 255);
                            _push(_t98);
                             *4237756 = _t98;
                            _t55 = L004041B0();
                            __esp = __esp + 4;
                        }
                        _pop(__ebp);
                        _pop(__edi);
                         *4237760 = _t55;
                        _pop(__esi);
                        _pop(__ebx);
                         *4237768 = 0;
                         *((intOrPtr*)(0x40a9cc)) = 0;
                         *((intOrPtr*)(0x40a9d0)) = 0;
                        __esp = __esp + 24;
                        return 0;
                    }
                }
                goto L31;
            }
            _t44 = 0;
            _push(64 << 2);
            _push(0);
            _push(4237496);
            memset();
            __esp = __esp + 12;
            asm("stosb");
            _t92 = (_v24 + _v24 * 2) * 2;
            do {
                _t96 = 4237808 + (_t44 + _t92) * 8;
                if( *_t96 != 0) {
                    while( *((intOrPtr*)(_t96 + 1)) != 0) {
                        _t86 =  *_t96;
                        if(0 >= 0) {
                            _t77 =  *((intOrPtr*)(_t44 + 4237784));
                            do {
                                 *(_t86 + 4237497) =  *(_t86 + 4237497) | _t77;
                                _t86 = _t86 + 1;
                            } while(0 >= _t86);
                        }
                        _t96 = _t96 + 2;
                        if( *_t96 != 0) {
                            continue;
                        }
                        goto L24;
                    }
                }
L24:
                _t44 = _t44 + 1;
            } while(_t44 < 4);
            _push(_t98);
             *4237756 = _t98;
             *4237760 = L004041B0();
            _t47 = _v24 << 4;
            __esp = __esp + 4;
            _t74 = _t47 + 4237796 + _t47 * 2;
            _pop(__ebp);
            _pop(__edi);
            _pop(__esi);
             *4237768 =  *_t74;
             *((intOrPtr*)(0x40a9cc)) =  *((intOrPtr*)(_t47 + 4237800 + _t47 * 2));
            _pop(__ebx);
             *((intOrPtr*)(0x40a9d0)) = _t74[2];
            __esp = __esp + 24;
            return 0;
        } else {
            L00404210();
            _pop(__ebp);
            _pop(__edi);
            _pop(__esi);
            _pop(__ebx);
            __esp = __esp + 24;
            return 0;
        }
    } else {
        _pop(__ebp);
        _pop(__edi);
        _pop(__esi);
        _pop(__ebx);
        __esp = __esp + 24;
        return 0;
    }
L31:
}

L00404160(
    intOrPtr _a4                           // _cfa_4
)
{
    intOrPtr _t2;                          // _t2

     *4237780 = 0;
    _t2 = _a4;
    if(_t2 == -2) {
         *4237780 = 1;
        goto __imp__GetOEMCP;
    }
    if(_t2 == -3) {
         *4237780 = 1;
        goto __imp__GetACP;
    }
    if(_t2 == -4) {
         *4237780 = 1;
        return  *4238912;
    }
    return _t2;
}

L004041B0(
    intOrPtr _a4                           // _cfa_4
)
{
    if(_a4 - 932 > 18) {
L2:
        return 0;
    } else {
        switch( *((intOrPtr*)(0 +  &M004041E8))) {
            case 0:
                return 1041;
                goto L7;
            case 1:
                return 2052;
                goto L7;
            case 2:
                return 1042;
                goto L7;
            case 3:
                return 1028;
                goto L7;
            case 4:
                goto L2;
        }
    }
L7:
}

L00404210()
{
    _unknown_ __edi;                       // r4
    _unknown_ _t7;                         // _t7

    _push(_t7);
    _push(64 << 2);
    _push(0);
    _push(4237496);
    memset();
    __esp = __esp + 12;
    asm("stosb");
     *4237768 = 0;
    _pop(__edi);
     *4237756 = 0;
     *4237760 = 0;
     *((intOrPtr*)(0x40a9cc)) = 0;
     *((intOrPtr*)(0x40a9d0)) = 0;
    return 0;
}

L00404240()
{
    return L00403F80(-3);
}

L00404250()
{
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    signed int _t37;                       // _t37
    signed int _t39;                       // _t39
    intOrPtr* _t41;                        // _t41
    signed char _t42;                      // _t42
    intOrPtr _t47;                         // _t47
    intOrPtr* _t51;                        // _t51
    intOrPtr* _t52;                        // _t52
    intOrPtr _t53;                         // _t53
    intOrPtr* _t56;                        // _t56
    signed int* _t66;                      // _t66
    intOrPtr* _t67;                        // _t67
    intOrPtr _t68;                         // _t68
    signed int _t69;                       // _t69
    intOrPtr _t70;                         // _t70
    signed int _t71;                       // _t71
    signed int _t72;                       // _t72
    intOrPtr* _t73;                        // _t73

    _t68 = L00404F00(256);
    if(_t68 == 0) {
        L004029F0(27);
    }
     *4247136 = _t68;
     *4247392 = 32;
    if(_t68 + 256 <= _t68) {
L5:
        _push(__esp + 16);
        __imp__GetStartupInfoA();
        if( *((short*)(__esp + 66)) == 0 ||  *((intOrPtr*)(__esp + 68)) == 0) {
L25:
            _t69 = 0;
            _t51 = __imp__GetStdHandle;
            do {
                _t66 = _t69 * 8 +  *4247136;
                if( *_t66 != -1) {
                    _t66[1] = _t66[1] | 128;
                    goto L37;
                }
                _t37 = -10;
                _t66[1] = 129;
                if(_t69 != 0) {
                    _t37 = -11;
                    asm("adc eax, 0xffffffff");
                }
                _push(_t37);
                 *_t51();
                _t71 = _t37;
                if(_t37 == -1) {
L35:
                    _t66[1] = _t66[1] | 64;
                } else {
                    _push(_t71);
                    __imp__GetFileType();
                    if(_t37 == 0) {
                        goto L35;
                    }
                    _t39 = _t37 & 255;
                     *_t66 = _t71;
                    if(_t39 != 2) {
                        if(_t39 == 3) {
                            _t66[1] = _t66[1] | 8;
                        }
                    } else {
                        _t66[1] = _t66[1] | 64;
                    }
                }
L37:
                _t69 = _t69 + 1;
            } while(_t69 < 3);
            _push( *4247392);
            __imp__SetHandleCount();
            return;
        } else {
            _t41 =  *((intOrPtr*)(__esp + 68));
            _t70 =  *_t41;
            _t67 = _t41 + 4;
            _t52 = _t70 + _t67;
            if(_t70 >= 2048) {
                _t70 = 2048;
            }
            if( *4247392 >= _t70) {
L18:
                _t72 = 0;
                if(_t70 <= 0) {
                    goto L25;
                } else {
                    goto L19;
                }
                do {
L19:
                    _t53 =  *_t52;
                    if(_t53 == -1) {
                        goto L24;
                    }
                    _t42 =  *_t67;
                    if((_t42 & 1) == 0) {
                        goto L24;
                    }
                    if((_t42 & 8) != 0) {
L23:
                        _t56 =  *((intOrPtr*)(((_t72 & -25) >> 3) + 4247136)) + (_t72 & 31) * 8;
                         *_t56 =  *_t52;
                         *((char*)(_t56 + 4)) =  *_t67;
                        goto L24;
                    }
                    _push(_t53);
                    __imp__GetFileType();
                    if(_t42 == 0) {
                        goto L24;
                    }
                    goto L23;
L24:
                    _t72 = _t72 + 1;
                    _t67 = _t67 + 1;
                    _t52 = _t52 + 4;
                } while(_t72 < _t70);
                goto L25;
            } else {
                _t73 = 4247140;
                while(1) {
                    _t47 = L00404F00(256);
                    if(_t47 == 0) {
                        break;
                    }
                     *_t73 = _t47;
                     *4247392 =  *4247392 + 32;
                    if(_t47 + 256 <= _t47) {
L15:
                        _t73 = _t73 + 4;
                        if( *4247392 < _t70) {
                            continue;
                        }
                        goto L18;
                    }
                    do {
                         *((char*)(_t47 + 4)) = 0;
                        _t47 = _t47 + 8;
                         *((intOrPtr*)(_t47 - 8)) = -1;
                         *((char*)(_t47 - 3)) = 10;
                    } while( *_t73 + 256 > _t47);
                    goto L15;
                }
                _t70 =  *4247392;
                goto L18;
            }
        }
    } else {
        do {
             *((char*)(_t68 + 4)) = 0;
            _t68 = _t68 + 8;
             *((intOrPtr*)(_t68 - 8)) = -1;
             *((char*)(_t68 - 3)) = 10;
        } while( *4247136 + 256 > _t68);
        goto L5;
    }
}

L00404430(
    intOrPtr __eax                         // r0
)
{
    _push(0);
    _push(4096);
    _push(1);
    __imp__HeapCreate();
     *4247124 = __eax;
    if(__eax != 0) {
        L00404FB0(__eax);
        if(__eax != 0) {
            return 1;
        } else {
            _push( *4247124);
            __imp__HeapDestroy();
            return 0;
        }
    } else {
        return 0;
    }
}

L00404550()
{
    intOrPtr _t1;                          // _t1
    intOrPtr* _t3;                         // _t3

    _t1 =  *4236764;
    if(_t1 == 1 || _t1 == 0 &&  *4236768 == 1) {
        L00404590(252);
        _t3 =  *4238192;
        if(_t3 != 0) {
             *_t3();
        }
        L00404590(255);
        return;
    } else {
        return;
    }
}

L00404590(
    intOrPtr _a4                           // _cfa_4
)
{
    char _v260;                            // _cfa_fffffefc
    char _v272;                            // _cfa_fffffef0
    char _v428;                            // _cfa_fffffe54
    char _v432;                            // _cfa_fffffe50
    signed int __ebx;                      // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    _unknown_ __ebp;                       // r6
    intOrPtr* _t29;                        // _t29
    signed int _t42;                       // _t42
    signed int _t54;                       // _t54
    signed int _t63;                       // _t63
    signed int _t72;                       // _t72
    intOrPtr _t81;                         // _t81
    signed int _t83;                       // _t83
    signed int _t84;                       // _t84
    signed int _t85;                       // _t85
    intOrPtr _t119;                        // _t119
    _unknown_ _t121;                       // _t121
    _unknown_ _t122;                       // _t122
    _unknown_ _t123;                       // _t123
    char* _t126;                           // _t126

    _t42 = 0;
    _t29 = 4238048;
    _t81 = _a4;
    while( *_t29 != _t81) {
        _t29 = _t29 + 8;
        _t42 = _t42 + 1;
        if(_t29 < 4238192) {
            continue;
        }
        break;
    }
    __ebx = _t42 * 8;
    if( *((intOrPtr*)(4238048 + _t42 * 8)) != _t81) {
L17:
        return _t29;
    } else {
        if( *4236764 == 1 ||  *4236764 == 0 &&  *4236768 == 1) {
            if( *4247136 == 0) {
L15:
                _push(-12);
                __imp__GetStdHandle();
                _t119 = _t29;
L16:
                _push(0);
                _push( &_v428);
                asm("repne scasb");
                _push( !-1 - 1);
                _push( *((intOrPtr*)(__ebx + 4238052)));
                _push(_t119);
                __imp__WriteFile();
                return 0;
            }
            _t29 =  *4247136;
            _t119 = _t29[4];
            if(_t119 != -1) {
                goto L16;
            }
            goto L15;
        }
        if(_t81 == 252) {
            goto L17;
        } else {
            _push(260);
            _push( &_v260);
            _push(0);
             *__imp__GetModuleFileNameA();
            if( &_v260 == 0) {
                _push(5 << 2);
                _push("<program name unknown>");
                _push( &_v272);
                memcpy();
                __esp = __esp + 12;
                asm("movsw");
                asm("movsb");
            }
            _t126 =  &_v272;
            asm("repne scasb");
            if( !-1 > 60) {
                _push(3);
                asm("repne scasb");
                _t126 = __esp +  !-1 + 124;
                _push("...");
                _push(_t126);
                L004057B0(0);
                __esp = __esp + 12;
            }
            _push(6 << 2);
            _push("Runtime Error!\n\nProgram: ");
            _push( &_v432);
            memcpy();
            __esp = __esp + 12;
            asm("movsw");
            asm("repne scasb");
            _t83 =  !-1;
            _t121 = _t126 - -1;
            asm("repne scasb");
            _t54 = _t83 >> 2;
            _push(_t54 << 2);
            _push(_t121);
            _push( &_v432 - 1);
            memcpy();
            __esp = __esp + 12;
            _push((_t83 & 3) << 0);
            _push(_t121);
            _push(_t121 + _t54 + _t54);
            memcpy();
            __esp = __esp + 12;
            asm("repne scasb");
            _t84 =  !-1;
            _t122 = "\n\n" - -1;
            asm("repne scasb");
            _t63 = _t84 >> 2;
            _push(_t63 << 2);
            _push(_t122);
            _push( &_v432 - 1);
            memcpy();
            __esp = __esp + 12;
            _push((_t84 & 3) << 0);
            _push(_t122);
            _push(_t122 + _t63 + _t63);
            memcpy();
            __esp = __esp + 12;
            asm("repne scasb");
            _t123 =  *((intOrPtr*)(__ebx + 4238052)) - -1;
            _t85 =  !-1;
            asm("repne scasb");
            _t72 = _t85 >> 2;
            _push(_t72 << 2);
            _push(_t123);
            _push( &_v432 - 1);
            memcpy();
            __esp = __esp + 12;
            _push(73744);
            _push("Microsoft Visual C++ Runtime Library");
            _push((_t85 & 3) << 0);
            _push(_t123);
            _push(_t123 + _t72 + _t72);
            memcpy();
            __esp = __esp + 12;
            _push( &_v432);
            L00405710( &_v432);
            __esp = __esp + 12;
            return  &_v432;
        }
    }
}

L00404EB0(
    intOrPtr _a4                           // _cfa_4
)
{
    char _v4;                              // _cfa_fffffffc
    char _v8;                              // _cfa_fffffff8
    intOrPtr __esi;                        // r5
    _unknown_ _t6;                         // _t6
    _unknown_ _t8;                         // _t8
    intOrPtr _t9;                          // _t9

    __esi = _a4;
    if(__esi == 0) {
        return _t6;
    } else {
        _t8 = L00405260(__esi,  &_v4,  &_v8);
        if(_t8 == 0) {
            _push(__esi);
            _t9 =  *4247124;
            _push(0);
            _push(_t9);
            __imp__HeapFree();
            return _t9;
        }
        return L004052C0(__edx, _v4, _v8, _t8);
    }
}

L00404F00(
    intOrPtr _a4                           // _cfa_4
)
{
    return L00404F20(_a4,  *4241392);
}

L00404F20(
    intOrPtr _a4,                          // _cfa_4
    intOrPtr _a8                           // _cfa_8
)
{
    intOrPtr __edi;                        // r4
    intOrPtr __esi;                        // r5
    _unknown_ _t3;                         // _t3

    __esi = _a4;
    if(__esi <= -32) {
        if(__esi == 0) {
            __esi = 1;
        }
        __edi = _a8;
        while(1) {
            _t3 = 0;
            if(__esi <= -32) {
                _t3 = L00404F70(__esi);
            }
            if(_t3 != 0 || __edi == 0) {
                break;
            }
            if(L00405DE0(__esi) != 0) {
                continue;
            } else {
                return 0;
            }
            goto L12;
        }
        return _t3;
    } else {
        return 0;
    }
L12:
}

L00404F70(
    intOrPtr _a4                           // _cfa_4
)
{
    _unknown_ __esi;                       // r5
    intOrPtr _t2;                          // _t2
    _unknown_ _t5;                         // _t5
    unsigned int _t8;                      // _t8

    _t8 = _a4 + 15 & -16;
    if(_t8 >  *4240996) {
L2:
        _push(_t8);
        _t2 =  *4247124;
        _push(0);
        _push(_t2);
        __imp__HeapAlloc();
        return _t2;
    }
    _push(_t8 >> 4);
    _t5 = L00405310(__ecx);
    __esp = __esp + 4;
    if(_t5 == 0) {
        goto L2;
    }
    return _t5;
}

L00404FB0(
    intOrPtr* __eax                        // r0
)
{
    intOrPtr* __ebx;                       // r1
    _unknown_ __edi;                       // r4
    intOrPtr* __esi;                       // r5
    intOrPtr* _t16;                        // _t16
    intOrPtr* _t36;                        // _t36
    _unknown_ _t37;                        // _t37

    _t16 = __eax;
    if( *4240984 != 0) {
        _push(2068);
        _t16 =  *4247124;
        _push(0);
        _push(_t16);
        __imp__HeapAlloc();
        __esi = _t16;
        __eflags = __esi;
        if(__eflags != 0) {
            goto L2;
        } else {
            __eflags = 0;
            return;
        }
    } else {
        __esi = 4238920;
L2:
        _push(4);
        _t36 = __imp__VirtualAlloc;
        _push(8192);
        _push(4194304);
        _push(0);
         *_t36();
        __ebx = _t16;
        if(__ebx == 0) {
L22:
            __eflags = __esi - 4238920;
            if(__esi != 4238920) {
                _push(__esi);
                _push(0);
                _push( *4247124);
                __imp__HeapFree();
            }
            __eflags = 0;
            return;
        } else {
            _push(4);
            _push(4096);
            _push(65536);
            _push(__ebx);
             *_t36();
            if(_t16 == 0) {
                _push(32768);
                _push(0);
                _push(__ebx);
                __imp__VirtualFree();
                goto L22;
            } else {
                if(__esi != 4238920) {
                     *__esi = 4238920;
                     *((intOrPtr*)(__esi + 4)) =  *4238924;
                     *4238924 = __esi;
                     *((intOrPtr*)(__esi[1])) = __esi;
                } else {
                    if( *4238920 == 0) {
                         *4238920 = 4238920;
                    }
                    if( *4238924 == 0) {
                         *4238924 = 4238920;
                    }
                }
                __ebp = 0;
                __esi[0x204] = __ebx;
                __esi[2] = 0;
                __esi[3] = 16;
                do {
                    _t37 = __esi + __ebp;
                    if(__ebp >= 16) {
                         *((char*)(_t37 + 16)) = 255;
                    } else {
                         *((char*)(_t37 + 16)) = 240;
                    }
                    __ebp = __ebp + 1;
                     *((char*)(_t37 + 1040)) = 241;
                } while(__ebp < 1024);
                _push(16384 << 2);
                _push(0);
                _push(__ebx);
                memset();
                __esp = __esp + 12;
                while(__esi[0x204] + 65536 > __ebx) {
                     *__ebx = __ebx + 8;
                    __ebx[1] = 240;
                     *((char*)(__ebx + 248)) = 255;
                    __ebx = __ebx + 4096;
                }
                return;
            }
        }
    }
}

L00405120(
    intOrPtr* _a4                          // _cfa_4
)
{
    intOrPtr* __esi;                       // r5
    intOrPtr _t7;                          // _t7
    intOrPtr _t9;                          // _t9

    _push(32768);
    __esi = _a4;
    _push(0);
    _t7 = __esi[0x204];
    _push(_t7);
    __imp__VirtualFree();
    if( *4240988 == __esi) {
        _t7 = __esi[1];
         *4240988 = _t7;
    }
    if(__esi == 4238920) {
         *4240984 = 0;
        return _t7;
    } else {
        _push(__esi);
        _push(0);
         *((intOrPtr*)(__esi[1])) =  *__esi;
        _t9 =  *__esi;
         *((intOrPtr*)(_t9 + 4)) = __esi[1];
        _push( *4247124);
        __imp__HeapFree();
        return _t9;
    }
}

L00405180()
{
    char* __ebx;                           // r1
    _unknown_ __edi;                       // r4
    intOrPtr* __esi;                       // r5
    intOrPtr* _t16;                        // _t16
    _unknown_ _t18;                        // _t18
    intOrPtr _t19;                         // _t19

    __esi =  *4238924;
    do {
        if(__esi[0x204] != 0) {
            __ebp = 1023;
            __ebx = __esi + 1039;
             *((intOrPtr*)(__esp + 16)) = 0;
            __edi = 4190208;
            do {
                if( *__ebx != 240) {
                    goto L9;
                }
                _push(16384);
                _push(4096);
                _t18 = __esi[0x204] + __edi;
                _push(_t18);
                __imp__VirtualFree();
                if(_t18 != 0) {
                     *__ebx = 255;
                     *4240992 =  *4240992 - 1;
                    _t19 = __esi[3];
                    if(_t19 == -1 || __ebp < _t19) {
                        __esi[3] = __ebp;
                    }
                     *((intOrPtr*)(__esp + 16)) =  *((intOrPtr*)(__esp + 16)) + 1;
                    _t9 = __esp + 24;
                     *_t9 =  *((intOrPtr*)(__esp + 24)) - 1;
                    if( *_t9 == 0) {
                        break;
                    }
                }
L9:
                __edi = __edi - 4096;
                __ebp = __ebp - 1;
                __ebx = __ebx - 1;
            } while(__edi >= 0);
            _t16 = __esi;
            __esi = __esi[1];
            if( *((intOrPtr*)(__esp + 16)) != 0 &&  *((char*)(_t16 + 16)) == 255) {
                __edx = 1;
                __ecx = _t16 + 17;
                while( *__ecx == 255) {
                    __edx = __edx + 1;
                    __ecx = __ecx + 1;
                    if(__edx < 1024) {
                        continue;
                    }
                    break;
                }
                if(__edx == 1024) {
                    _t16 = L00405120(_t16);
                }
            }
        }
    } while(__esi !=  *4238924 &&  *((intOrPtr*)(__esp + 24)) > 0);
    return _t16;
}

L00405260(
    signed int _a4,                        // _cfa_4
    intOrPtr* _a8,                         // _cfa_8
    signed int* _a12                       // _cfa_c
)
{
    intOrPtr _t7;                          // _t7
    intOrPtr* _t13;                        // _t13
    signed int _t15;                       // _t15
    signed int _t16;                       // _t16

    _t13 = 4238920;
    _t16 = _a4;
    while(1) {
        _t7 = _t13[0x204];
        if(_t7 != 0 && _t7 < _t16 && _t7 + 4194304 > _t16) {
             *_a8 = _t13;
            _t15 = _t16 & -4096;
             *_a12 = _t15;
            return (_t16 - _t15 - 256 >> 4) + _t15 + 8;
        }
        _t13 =  *_t13;
        if(_t13 != 4238920) {
            continue;
        } else {
            return 0;
        }
        break;
    }
}

L004052C0(
    _unknown_ __edx,                       // r3
    intOrPtr _a4,                          // _cfa_4
    intOrPtr _a8,                          // _cfa_8
    char* _a12                             // _cfa_c
)
{
    char* _t10;                            // _t10
    _unknown_ _t11;                        // _t11
    _unknown_ _t15;                        // _t15

    _t15 = (_a8 -  *((intOrPtr*)(_a4 + 2064)) >> 12) + _a4;
    _t10 = _a12;
     *((intOrPtr*)(_t15 + 16)) =  *((intOrPtr*)(_t15 + 16)) +  *_t10;
     *_t10 = 0;
     *((char*)(_t15 + 1040)) = 241;
    if( *((char*)(_t15 + 16)) == 240) {
         *4240992 =  *4240992 + 1;
        if( *4240992 == 32) {
            _push(16);
            _t11 = L00405180();
            __esp = __esp + 4;
            return _t11;
        }
    }
    return _t10;
}

L00405310(
    _unknown_ __ecx                        // r2
)
{
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    _unknown_ _t80;                        // _t80
    intOrPtr* _t83;                        // _t83
    _unknown_ _t95;                        // _t95
    _unknown_ _t98;                        // _t98
    _unknown_ _t99;                        // _t99
    char _t100;                            // _t100
    _unknown_ _t103;                       // _t103
    signed int _t104;                      // _t104
    signed int _t105;                      // _t105
    intOrPtr _t112;                        // _t112
    intOrPtr _t113;                        // _t113
    signed int _t118;                      // _t118
    signed int _t120;                      // _t120
    _unknown_ _t122;                       // _t122
    intOrPtr* _t123;                       // _t123
    _unknown_ _t124;                       // _t124
    intOrPtr* _t125;                       // _t125
    signed int _t126;                      // _t126
    signed int _t127;                      // _t127
    _unknown_ _t128;                       // _t128
    signed int _t129;                      // _t129
    signed int _t130;                      // _t130
    intOrPtr* _t131;                       // _t131
    _unknown_ _t132;                       // _t132
    signed int _t134;                      // _t134
    intOrPtr* _t138;                       // _t138
    signed int _t140;                      // _t140

    _push(_t99);
    _push(_t128);
    _t100 =  *((intOrPtr*)(__esp + 12));
    _push(_t124);
    _push(_t132);
    _t125 =  *4240988;
    goto L1;
    do {
L17:
        _t125 =  *_t125;
        if( *4240988 != _t125) {
L1:
            if( *((intOrPtr*)(_t125 + 2064)) == 0) {
                continue;
            } else {
                break;
            }
        } else {
            _t131 = 4238920;
L19:
            while(_t131[0x204] == 0 ||  *(_t131 + 12) == -1) {
                _t131 =  *_t131;
                if(_t131 != 4238920) {
                    continue;
                } else {
                    L00404FB0(0);
                    if(0 == 0) {
                        _pop(__ebp);
                        _pop(__edi);
                        _pop(__esi);
                        _pop(__ebx);
                        return 0;
                    } else {
                        _t123 =  *((intOrPtr*)(0x810));
                         *((char*)(_t123 + 8)) = _t100;
                         *4240988 = 0;
                         *_t123 = _t100 + _t123 + 8;
                        _pop(__ebp);
                        _pop(__edi);
                        _t123[1] = 240 - _t100;
                        _pop(__esi);
                         *((intOrPtr*)(0x10)) =  *((intOrPtr*)(0x10)) - _t100;
                        _pop(__ebx);
                        return  *((intOrPtr*)(0x810)) + 256;
                    }
                }
                goto L45;
            }
            _t118 =  *(_t131 + 12);
            _t126 = _t118;
            _t103 = _t118 + 16;
            if(_t103 >= 1024) {
                _t103 = 1024;
            }
            _t127 = _t126 + 1;
            if(_t103 > _t127) {
                while( *((intOrPtr*)(_t131 + _t127 + 16)) == 255) {
                    _t127 = _t127 + 1;
                    if(_t103 > _t127) {
                        continue;
                    }
                    goto L32;
                }
            }
L32:
            _push(4);
            _t134 = _t118 << 12;
            _push(4096);
            _push(_t127 - _t118 << 12);
            _t80 =  *((intOrPtr*)(_t131 + 2064)) + _t134;
            _push(_t80);
            __imp__VirtualAlloc();
            if(_t80 != _t134 +  *((intOrPtr*)(_t131 + 2064))) {
                _pop(__ebp);
                _pop(__edi);
                _pop(__esi);
                _pop(__ebx);
                return 0;
            } else {
                _t104 =  *(_t131 + 12);
                _t138 = (_t104 << 12) +  *((intOrPtr*)(_t131 + 2064));
                while(_t104 < _t127) {
                    _t104 = _t104 + 1;
                     *_t138 = _t138 + 8;
                    _t138 = _t138 + 4096;
                    _t122 = _t131 + _t104 - 1;
                     *((intOrPtr*)(_t138 - 4092)) = 240;
                     *((char*)(_t138 - 3848)) = 255;
                     *((char*)(_t122 + 16)) = 240;
                     *((char*)(_t122 + 1040)) = 241;
                }
                 *4240988 = _t131;
                if(_t127 < 1024) {
                    while( *((intOrPtr*)(_t131 + _t127 + 16)) != 255) {
                        _t127 = _t127 + 1;
                        if(_t127 < 1024) {
                            continue;
                        }
                        goto L40;
                    }
                }
L40:
                _t105 =  *(_t131 + 12);
                 *(_t131 + 12) = -1;
                if(_t127 < 1024) {
                     *(_t131 + 12) = _t127;
                }
                _t120 = _t105 << 12;
                _t83 = _t131[0x204] + _t120;
                 *((char*)(_t83 + 8)) = _t100;
                 *(_t131 + 8) = _t105;
                 *((intOrPtr*)(_t131 + _t105 + 16)) =  *((intOrPtr*)(_t131 + _t105 + 16)) - _t100;
                _pop(__ebp);
                _pop(__edi);
                 *_t83 = _t100 + _t83 + 8;
                _t83[1] = _t83[1] - _t100;
                _pop(__esi);
                _pop(__ebx);
                return _t131[0x204] + _t120 + 256;
            }
        }
        goto L45;
    } while();
    _t129 =  *(_t125 + 8);
    if(_t129 >= 1024) {
L10:
        _t132 = 0;
        _t130 = 0;
        if( *(_t125 + 8) > 0) {
            do {
                _t112 =  *((intOrPtr*)(_t125 + _t130 + 16));
                if(0 < _t100 || _t112 == 255 || 0 <= _t100) {
                    goto L16;
                } else {
                    _push(_t100);
                    _push(0);
                    _push( *((intOrPtr*)(_t125 + 2064)) + _t132);
                    _t98 = L00405590();
                    __esp = __esp + 12;
                    if(_t98 != 0) {
                        _pop(__ebp);
                         *4240988 = _t125;
                         *((intOrPtr*)(_t125 + _t130 + 16)) =  *((intOrPtr*)(_t125 + _t130 + 16)) - _t100;
                         *(_t125 + 8) = _t130;
                        _pop(__edi);
                        _pop(__esi);
                        _pop(__ebx);
                        return _t98;
                    } else {
                         *((char*)(_t125 + _t130 + 1040)) = _t100;
                        goto L16;
                    }
                }
                goto L45;
L16:
                _t132 = _t132 + 4096;
                _t130 = _t130 + 1;
            } while( *(_t125 + 8) > _t130);
        }
        goto L17;
    } else {
        _t140 = _t129 << 12;
        do {
            _t113 =  *((intOrPtr*)(_t125 + _t129 + 16));
            if(0 < _t100 || _t113 == 255 || 0 <= _t100) {
                goto L9;
            } else {
                _push(_t100);
                _push(0);
                _push( *((intOrPtr*)(_t125 + 2064)) + _t140);
                _t95 = L00405590();
                __esp = __esp + 12;
                if(_t95 != 0) {
                    _pop(__ebp);
                     *4240988 = _t125;
                     *((intOrPtr*)(_t125 + _t129 + 16)) =  *((intOrPtr*)(_t125 + _t129 + 16)) - _t100;
                     *(_t125 + 8) = _t129;
                    _pop(__edi);
                    _pop(__esi);
                    _pop(__ebx);
                    return _t95;
                } else {
                     *((char*)(_t125 + _t129 + 1040)) = _t100;
                    goto L9;
                }
            }
            goto L45;
L9:
            _t140 = _t140 + 4096;
            _t129 = _t129 + 1;
        } while(_t140 < 4194304);
        goto L10;
    }
L45:
    goto L17;
}

L00405590()
{
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    intOrPtr* _t38;                        // _t38
    intOrPtr _t49;                         // _t49
    intOrPtr _t54;                         // _t54
    intOrPtr _t56;                         // _t56
    char* _t57;                            // _t57
    char* _t61;                            // _t61
    char* _t66;                            // _t66
    char* _t71;                            // _t71
    intOrPtr _t75;                         // _t75
    intOrPtr _t76;                         // _t76
    intOrPtr _t77;                         // _t77
    _unknown_ _t79;                        // _t79
    char* _t80;                            // _t80
    char* _t81;                            // _t81

    _t38 =  *((intOrPtr*)(__esp + 4));
    __edx =  *((intOrPtr*)(__esp + 16));
    _t56 = _t38[1];
    _push(_t79);
    _t71 =  *_t38;
    _t80 = _t71;
    if(__edx > _t56) {
        _t57 = _t56 + _t71;
        if( *_t57 != 0) {
            _t80 = _t57;
        }
        _t75 =  *((intOrPtr*)(__esp + 24));
        if(__edx + _t80 >= _t38 + 248) {
L24:
            _t81 = _t38 + 8;
            if(_t71 <= _t38 + 8) {
L34:
                _pop(__ebp);
                return 0;
            } else {
                while(__edx + _t81 <= _t38 + 247) {
                    if( *_t81 != 0) {
                        _t81 = _t81;
                        goto L33;
                    } else {
                        _t61 = _t81 + 1;
                        _t49 = 1;
                        while( *_t61 == 0) {
                            _t61 = _t61 + 1;
                            _t49 = _t49 + 1;
                        }
                        if(_t49 >= __edx) {
                            _t76 = __edx + _t81;
                            if(_t76 >= _t38 + 248) {
                                _t38[1] = 0;
                                 *_t38 = _t38 + 8;
                            } else {
                                 *_t38 = _t76;
                                _t38[1] = _t49 - __edx;
                            }
                             *_t81 = __dl;
                            _pop(__ebp);
                            return (_t81 - _t38 << 4) + _t38 + 128;
                        } else {
                            _t75 = _t75 - _t49;
                            if(__edx > _t75) {
                                _pop(__ebp);
                                return 0;
                            } else {
                                _t81 = _t61;
L33:
                                if(_t71 > _t81) {
                                    continue;
                                } else {
                                    goto L34;
                                }
                            }
                        }
                    }
                    goto L40;
                }
                goto L34;
            }
        } else {
            do {
                if( *_t80 != 0) {
                    _t80 = _t80;
                    goto L17;
                } else {
                    _t66 = _t80 + 1;
                    _t54 = 1;
                    while( *_t66 == 0) {
                        _t66 = _t66 + 1;
                        _t54 = _t54 + 1;
                    }
                    if(_t54 >= __edx) {
                        _t77 = __edx + _t80;
                        if(_t77 >= _t38 + 248) {
                            _t38[1] = 0;
                             *_t38 = _t38 + 8;
                        } else {
                             *_t38 = _t77;
                            _t38[1] = _t54 - __edx;
                        }
                         *_t80 = __dl;
                        _pop(__ebp);
                        return (_t80 - _t38 << 4) + _t38 + 128;
                    } else {
                        if(_t71 != _t80) {
                            _t75 = _t75 - _t54;
                            if(__edx > _t75) {
                                _pop(__ebp);
                                return 0;
                            } else {
                                _t80 = _t66;
                                goto L17;
                            }
                        } else {
                            _t80 = _t66;
                            _t38[1] = _t54;
                            goto L17;
                        }
                    }
                }
                goto L40;
L17:
            } while(__edx + _t80 < _t38 + 248);
            goto L24;
        }
    } else {
         *_t71 = __dl;
        if(__edx + _t71 >= _t38 + 248) {
            _t38[1] = 0;
             *_t38 = _t38 + 8;
        } else {
             *_t38 =  *_t38 + __edx;
            _t38[1] = _t38[1] - __edx;
        }
        _pop(__ebp);
        return (_t71 - _t38 << 4) + _t38 + 128;
    }
L40:
}

L00405710(
    intOrPtr __eax,                        // r0
    intOrPtr _a4,                          // _cfa_4
    intOrPtr _a8,                          // _cfa_8
    intOrPtr _a12                          // _cfa_c
)
{
    intOrPtr* __ebx;                       // r1
    intOrPtr* __esi;                       // r5
    intOrPtr* _t5;                         // _t5

    __esi = 0;
    if( *4241000 != 0) {
L4:
        _t5 =  *4241004;
        if(_t5 != 0) {
             *_t5();
            __esi = _t5;
        }
        if(__esi != 0 &&  *4241008 != 0) {
            _push(__esi);
             *4241008();
            __esi = _t5;
        }
        _push(_a12);
        _push(_a8);
        _push(_a4);
        _push(__esi);
         *4241000();
        return;
    } else {
        _push("user32.dll");
        __imp__LoadLibraryA();
        if(__eax == 0) {
L10:
            return;
        } else {
            _push("MessageBoxA");
            __ebx = __imp__GetProcAddress;
            _push(__eax);
             *__ebx();
             *4241000 = __eax;
            if(__eax == 0) {
                goto L10;
            } else {
                _push("GetActiveWindow");
                _push(__eax);
                 *__ebx();
                _push("GetLastActivePopup");
                 *4241004 = __eax;
                _push(__eax);
                 *__ebx();
                 *4241008 = __eax;
                goto L4;
            }
        }
    }
}

signed int L004057B0(
    _unknown_ __eax,                       // r0
    signed int _a4,                        // _cfa_4
    signed int _a8,                        // _cfa_8
    unsigned int _a12                      // _cfa_c
)
{
    _unknown_ __ebx;                       // r1
    signed int __edi;                      // r4
    _unknown_ __esi;                       // r5
    signed int _t23;                       // _t23
    signed int _t28;                       // _t28
    _unknown_ _t29;                        // _t29
    signed int _t30;                       // _t30
    unsigned int _t31;                     // _t31
    unsigned int _t32;                     // _t32
    unsigned int _t33;                     // _t33
    signed int _t36;                       // _t36
    _unknown_ _t40;                        // _t40
    signed int _t41;                       // _t41

    _t31 = _a12;
    if(_t31 == 0) {
L19:
        return _a4;
    } else {
        _push(_t40);
        _push(_t29);
        _t30 = _t31;
        _t41 = _a8;
        __edi = _a4;
        if((_t41 & 3) != 0) {
            while(1) {
                _t23 =  *_t41;
                _t41 = _t41 + 1;
                 *__edi = _t23;
                __edi = __edi + 1;
                _t31 = _t31 - 1;
                if(_t31 == 0) {
                    goto L11;
                }
                if(_t23 == 0) {
                    if((__edi & 3) == 0) {
L15:
                        _t30 = _t31;
                        _t32 = _t31 >> 2;
                        if(_t32 != 0) {
                            goto L31;
                        } else {
                            goto L16;
                        }
                    } else {
                        while(1) {
                             *__edi = _t23;
                            __edi = __edi + 1;
                            _t31 = _t31 - 1;
                            if(_t31 == 0) {
                                goto L34;
                            }
                            if((__edi & 3) != 0) {
                                continue;
                            } else {
                                goto L15;
                            }
                            goto L35;
                        }
                        goto L34;
                    }
                } else {
                    if((_t41 & 3) != 0) {
                        continue;
                    } else {
                        _t30 = _t31;
                        _t33 = _t31 >> 2;
                        if(_t33 != 0) {
                            goto L21;
                        } else {
                            goto L8;
                        }
                    }
                }
                goto L35;
            }
            goto L11;
        } else {
            _t33 = _t31 >> 2;
            if(_t33 != 0) {
                do {
L21:
                    _t28 =  *_t41 ^ -1 ^ 2130640639 +  *_t41;
                    _t36 =  *_t41;
                    _t41 = _t41 + 4;
                    if((_t28 & -2130640640) == 0) {
                        goto L20;
                    } else {
                        if(_t36 == 0) {
                             *__edi = 0;
                            goto L30;
                        } else {
                            if(_t36 == 0) {
                                 *__edi = _t36 & 255;
                                goto L30;
                            } else {
                                if((_t36 & 16711680) == 0) {
                                     *__edi = _t36 & 65535;
                                    goto L30;
                                } else {
                                    if((_t36 & -16777216) != 0) {
                                        goto L20;
                                    } else {
                                         *__edi = _t36;
L30:
                                        __edi = __edi + 4;
                                        _t23 = 0;
                                        _t32 = _t33 - 1;
                                        if(_t32 != 0) {
L31:
                                            _t23 = 0;
                                            do {
                                                 *__edi = _t23;
                                                __edi = __edi + 4;
                                                _t32 = _t32 - 1;
                                            } while(_t32 != 0);
                                        }
                                        _t30 = _t30 & 3;
                                        if(_t30 != 0) {
                                            goto L16;
                                        } else {
L34:
                                            _pop(__ebx);
                                            _pop(__esi);
                                            return _a4;
                                        }
                                    }
                                }
                            }
                        }
                    }
                    goto L35;
L20:
                     *__edi = _t36;
                    __edi = __edi + 4;
                    _t33 = _t33 - 1;
                } while(_t33 != 0);
L8:
                _t30 = _t30 & 3;
                if(_t30 == 0) {
                    goto L11;
                } else {
                    goto L9;
                }
            } else {
                while(1) {
L9:
                    _t23 =  *_t41;
                    _t41 = _t41 + 1;
                     *__edi = _t23;
                    __edi = __edi + 1;
                    if(_t23 == 0) {
                        break;
                    }
                    _t30 = _t30 - 1;
                    if(_t30 != 0) {
                        continue;
                    } else {
L11:
                        _pop(__ebx);
                        _pop(__esi);
                        return _a4;
                    }
                    goto L35;
                }
L17:
                _t30 = _t30 - 1;
                if(_t30 != 0) {
L16:
                     *__edi = _t23;
                    __edi = __edi + 1;
                    goto L17;
                }
                _pop(__ebx);
                _pop(__esi);
                goto L19;
            }
        }
    }
L35:
}

L00405DE0(
    intOrPtr _a4                           // _cfa_4
)
{
    intOrPtr _t3;                          // _t3

    __ecx =  *4243004;
    if(__ecx == 0) {
L3:
        return;
    } else {
        _t3 = _a4;
        _push(_t3);
         *__ecx();
        __esp = __esp + 4;
        if(_t3 == 0) {
            goto L3;
        } else {
            return;
        }
    }
}

L00405DE0(
    intOrPtr _a4                           // _cfa_4
)
{
    intOrPtr _t3;                          // _t3

    __ecx =  *4243004;
    if(__ecx == 0) {
L3:
        return;
    } else {
        _t3 = _a4;
        _push(_t3);
         *__ecx();
        __esp = __esp + 4;
        if(_t3 == 0) {
            goto L3;
        } else {
            return;
        }
    }
}

// Statistics:
//     511 Register nodes
//     932 Temporaries nodes
//     104 Casts
//     217 Statements
//     150 Labels
//     109 Gotos
//      35 Blocks
//    5139 Nodes
//      20 Assembly nodes
//      77 Unknown Types


Total time: 0 seconds.
