// tmpg83xd8u2_text.c
// Generated by decompiling tmpg83xd8u2
// using Reko decompiler version 0.11.6.0.

#include "tmpg83xd8u2.h"

INT_PTR g_t401130(HWND tArg04, UINT tArg08, WPARAM tArg0C, LPARAM tArg10) = ??/* Unexpected function type (fn INT_PTR (HWND, UINT, WPARAM, LPARAM)) */ ; // 00401130
// 004022E0: Register word32 fn004022E0(Stack Eq_3 dwArg04)
// Called from:
//      Win32CrtStartup
word32 fn004022E0(Eq_3 dwArg04)
{
	g_t40BA10.u0 = (HINSTANCE) dwArg04;
	GetModuleFileNameA(dwArg04, 4241944, 0x0104);
	Eq_9 esi_13;
	esi_13.u0 = 4241944;
	Eq_9 eax_25;
	eax_25.u0 = 4241944;
	if (g_b40BA18 != 0x00)
	{
		do
		{
			byte cl_30 = eax_25.u2->b0000;
			if (cl_30 == 0x5C || cl_30 == 0x2F)
				esi_13 = eax_25;
			eax_25 = CharNextA(eax_25);
		} while (eax_25.u2->b0000 != 0x00);
	}
	esi_13.u2->b0000 = 0x00;
	CoInitialize(0x00);
	DialogBoxParamA(dwArg04, 4236636, null, &g_t401130, 0x00);
	CoUninitialize();
	return 0x00;
}

// 00402440: void fn00402440()
// Called from:
//      Win32CrtStartup
void fn00402440()
{
	<anonymous> * eax_5 = g_ptr40CF70;
	if (eax_5 != null)
		eax_5();
	fn00402560(&g_dw408008, &g_dw408010);
	fn00402560(&g_dw408000, &g_dw408004);
}

// 00402470: void fn00402470(Stack Eq_80 dwArg04)
// Called from:
//      Win32CrtStartup
void fn00402470(Eq_80 dwArg04)
{
	fn004024B0(dwArg04, 0x00, 0x00);
}

<anonymous> g_t402490 = <code>; // 00402490
// 004024B0: void fn004024B0(Stack Eq_80 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C)
// Called from:
//      fn00402470
void fn004024B0(Eq_80 dwArg04, word32 dwArg08, word32 dwArg0C)
{
	ptr32 fp;
	if (g_dw40A5C0 == 0x01)
		TerminateProcess(GetCurrentProcess(), dwArg04);
	g_dw40A5BC = 0x01;
	g_b40A5B8 = (byte) dwArg0C;
	ptr32 esp_25 = fp - 0x0C;
	if (dwArg08 == 0x00)
	{
		if (g_ptr40CF6C != null)
		{
			up32 edi_33 = g_dw40CF68;
			word32 * edi_34 = edi_33 - 0x04;
			if (edi_33 - 0x04 >= g_ptr40CF6C)
			{
				do
				{
					<anonymous> * eax_39 = *edi_34;
					if (eax_39 != null)
						eax_39();
					edi_34 -= 0x04;
				} while (edi_34 >= g_ptr40CF6C);
			}
		}
		struct Eq_124 * esp_59 = esp_25 - 4;
		esp_59->ptr0000 = &g_dw40801C;
		esp_59->ptrFFFFFFFC = &g_dw408014;
		fn00402560(esp_59->ptrFFFFFFFC, esp_59->ptr0000);
	}
	fn00402560(&g_dw408020, &g_dw408024);
	if (dwArg0C != 0x00)
		return;
	g_dw40A5C0 = 0x01;
	ExitProcess(dwArg04);
}

// 00402560: void fn00402560(Stack (ptr32 word32) dwArg04, Stack (ptr32 word32) dwArg08)
// Called from:
//      fn00402440
//      fn004024B0
void fn00402560(word32 * dwArg04, word32 * dwArg08)
{
	word32 * esi_11 = dwArg04;
	if (dwArg08 > dwArg04)
	{
		do
		{
			<anonymous> * eax_16 = *esi_11;
			if (eax_16 != null)
				eax_16();
			++esi_11;
		} while (dwArg08 > esi_11);
	}
}

// 00402850: Register Eq_10 Win32CrtStartup()
Eq_10 Win32CrtStartup()
{
	selector fs;
	Eq_10 eax_6 = fs->t0000;
	ptr32 fp;
	fs->t0000 = fp - 20;
	g_t40A584.u0 = (ptr32) GetVersion();
	g_dw40A590 = (uint32) g_b40A585;
	Eq_10 eax_38;
	eax_38.u0 = g_t40A584.u0;
	g_t40A584.u0 = (ptr32) (g_t40A584.u0 >> 0x10);
	g_dw40A58C = eax_38 & 0xFF;
	g_dw40A588 = ((eax_38 & 0xFF) << 0x08) + g_dw40A590;
	if (fn00404430() == 0x00)
		fn004029F0(0x1C);
	fn00404250();
	fn00404240();
	g_t40CF64.u1 = (word32 *) GetCommandLineA();
	Eq_9 eax_91 = fn00403DF0();
	g_t40A5D0.u1 = (word32 *) eax_91;
	if (eax_91 == 0x00 || g_t40CF64.u1 == 0x00)
		fn00402470(~0x00);
	fn00403B70();
	fn00403A80();
	fn00402440();
	Eq_9 esi_141;
	esi_141.u1 = g_t40CF64.u1;
	cu8 al_142 = esi_141.u2->b0000;
	if (al_142 != 0x22)
	{
		if (al_142 > 0x20)
		{
			do
				esi_141.u1 = esi_141 + (struct Eq_283 *) 0x01;
			while (esi_141.u2->b0000 > 0x20);
		}
		goto l00402955;
	}
	esi_141.u1 = esi_141 + (struct Eq_270 *) 0x01;
	if (*(esi_141 + (struct Eq_270 *) 0x01) != 0x22)
	{
		do
		{
			byte bl_153 = esi_141.u2->b0000;
			if (bl_153 == 0x00)
				break;
			if (fn00403A20(bl_153) != 0x00)
				esi_141.u1 = esi_141 + (struct Eq_311 *) 0x01;
			esi_141.u1 = esi_141 + (struct Eq_304 *) 0x01;
		} while (esi_141.u2->b0000 != 0x22);
		if (esi_141.u2->b0000 != 0x22)
		{
l00402955:
			if (esi_141.u2->b0000 != 0x00)
			{
				while (esi_141.u2->b0000 <= 0x20)
				{
					esi_141.u1 = esi_141 + (struct Eq_337 *) 0x01;
					if (esi_141.u2->b0000 == 0x00)
						break;
				}
			}
			Eq_314 tLoc74;
			tLoc74.dwFlags = (DWORD) 0x00;
			GetStartupInfoA(&tLoc74);
			fn00402470(fn004022E0(GetModuleHandleA(0x00)));
			fs->t0000 = eax_6;
			return eax_6;
		}
	}
	esi_141.u1 = esi_141 + (struct Eq_290 *) 0x01;
	goto l00402955;
}

// 004029F0: void fn004029F0(Stack word32 dwArg04)
// Called from:
//      Win32CrtStartup
//      fn00403A80
//      fn00403B70
//      fn00404250
void fn004029F0(word32 dwArg04)
{
	if (g_dw40A5DC == 0x01)
		fn00404550();
	fn00404590(dwArg04);
	g_ptr40A5D8();
}

// 00403A20: Register word32 fn00403A20(Stack byte bArg04)
// Called from:
//      Win32CrtStartup
word32 fn00403A20(byte bArg04)
{
	word32 dwArg04;
	return fn00403A40((byte) dwArg04, 0x00, 0x04);
}

// 00403A40: Register word32 fn00403A40(Stack uint8 bArg04, Stack ui32 dwArg08, Stack ui32 dwArg0C)
// Called from:
//      fn00403A20
word32 fn00403A40(uint8 bArg04, ui32 dwArg08, ui32 dwArg0C)
{
	struct Eq_387 * edx_9 = (uint32) bArg04;
	if ((dwArg0C & (uint32) edx_9->b40A8B9) != 0x00)
		return 0x01;
	ui32 ecx_18 = 0x00;
	if (dwArg08 != 0x00)
		ecx_18 = (uint32) g_a40A5FA[edx_9] & dwArg08;
	if (ecx_18 != 0x00)
		return 0x01;
	return 0x00;
}

// 00403A80: void fn00403A80()
// Called from:
//      Win32CrtStartup
void fn00403A80()
{
	Eq_9 edx_22;
	edx_22.u1 = g_t40A5D0.u1;
	ui32 esi_16 = 0x00;
	while (edx_22.u2->b0000 != 0x00)
	{
		if (edx_22.u2->b0000 != 0x3D)
			++esi_16;
		edx_22.u1 = edx_22 + (strlen(edx_22) - ~0x00);
	}
	Eq_9 eax_49 = fn00404F00(esi_16 * 0x04 + 0x04);
	g_t40A5A0.u1 = (word32 *) eax_49;
	Eq_9 ebx_104 = eax_49;
	if (eax_49 == 0x00)
		fn004029F0(0x09);
	Eq_9 ebp_154;
	ebp_154.u1 = g_t40A5D0.u1;
	while (ebp_154.u2->b0000 != 0x00)
	{
		Eq_421 ecx_88 = strlen(ebp_154) - ~0x00;
		if (ebp_154.u2->b0000 != 0x3D)
		{
			Eq_9 eax_95 = fn00404F00(ecx_88);
			*ebx_104.u1 = (word32) eax_95;
			if (eax_95 == 0x00)
				fn004029F0(0x09);
			char * edi_136 = *ebx_104.u1;
			strcpy(edi_136, ebp_154);
			ebx_104.u2 += 4;
		}
		ebp_154.u1 = ebp_154 + ecx_88;
	}
	fn00404EB0(g_t40A5D0.u1);
	g_t40A5D0.u1 = (word32 *) 0x00;
	*ebx_104.u1 = 0x00;
}

// 00403B70: void fn00403B70()
// Called from:
//      Win32CrtStartup
void fn00403B70()
{
	GetModuleFileNameA(0x00, 4242744, 0x0104);
	Eq_9 eax_20;
	eax_20.u1 = g_t40CF64.u1;
	g_ptr40A5B0 = &g_t40BD38;
	Eq_9 esi_13;
	esi_13.u0 = 4242744;
	if (eax_20.u2->b0000 != 0x00)
		esi_13.u1 = g_t40CF64.u1;
	Eq_543 tLoc08;
	Eq_545 tLoc04;
	fn00403C10(esi_13, 0x00, null, &tLoc08, &tLoc04);
	Eq_9 eax_54 = fn00404F00((word32) tLoc04 + (tLoc08 << 0x02));
	if (eax_54 == 0x00)
		fn004029F0(0x08);
	fn00403C10(esi_13, eax_54, eax_54.u1 + tLoc08, &tLoc08, &tLoc04);
	word32 eax_106 = (word32) tLoc08;
	g_t40A598.u1 = (word32 *) eax_54;
	g_dw40A594 = eax_106 - 0x01;
}

// 00403C10: void fn00403C10(Stack Eq_9 dwArg04, Stack Eq_9 dwArg08, Stack (ptr32 Eq_538) dwArg0C, Stack (ptr32 word32) dwArg10, Stack (ptr32 word32) dwArg14)
// Called from:
//      fn00403B70
void fn00403C10(Eq_9 dwArg04, Eq_9 dwArg08, struct Eq_538 * dwArg0C, word32 * dwArg10, word32 * dwArg14)
{
	*dwArg14 = 0x00;
	*dwArg10 = 0x01;
	Eq_9 esi_101 = dwArg04;
	struct Eq_538 * eax_111 = dwArg0C;
	if (dwArg08 != 0x00)
	{
		*dwArg08.u1 = dwArg0C;
		dwArg08.u2 += 4;
	}
	if (dwArg04.u2->b0000 != 0x22)
	{
		uint8 dl_123;
		do
		{
			++*dwArg14;
			if (eax_111 != null)
			{
				eax_111->b0000 = esi_101.u2->b0000;
				++eax_111;
			}
			dl_123 = (uint8) esi_101.u2->b0000;
			++esi_101.u2;
			if ((g_a40A8B9[(uint32) dl_123] & 0x04) != 0x00)
			{
				++*dwArg14;
				if (eax_111 != null)
				{
					eax_111->b0000 = esi_101.u2->b0000;
					++eax_111;
				}
				++esi_101.u2;
			}
			if (dl_123 == 0x20)
				break;
			if (dl_123 == 0x00)
				goto l00403C80;
		} while (dl_123 != 0x09);
		if (dl_123 == 0x00)
		{
l00403C80:
			--esi_101;
		}
		else if (eax_111 != null)
			eax_111->bFFFFFFFF = 0x00;
	}
	else
	{
		esi_101.u2 = dwArg04.u2 + 1;
		if (dwArg04.u2[1] != 0x22)
		{
			do
			{
				uint8 bl_39 = (uint8) esi_101.u2->b0000;
				if (bl_39 == 0x00)
					break;
				if ((g_a40A8B9[(uint32) bl_39] & 0x04) != 0x00)
				{
					++*dwArg14;
					if (eax_111 != null)
					{
						eax_111->b0000 = esi_101.u2->b0000;
						++esi_101.u2;
						++eax_111;
					}
				}
				++*dwArg14;
				if (eax_111 != null)
				{
					eax_111->b0000 = esi_101.u2->b0000;
					++eax_111;
				}
				++esi_101.u2;
			} while (esi_101.u2->b0000 != 0x22);
		}
		++*dwArg14;
		if (eax_111 != null)
		{
			eax_111->b0000 = 0x00;
			++eax_111;
		}
		if (esi_101.u2->b0000 == 0x22)
			++esi_101.u2;
	}
	up32 edi_176 = 0x00;
	while (esi_101.u2->b0000 != 0x00)
	{
		while (true)
		{
			byte dl_186 = esi_101.u2->b0000;
			if (dl_186 != 0x20 && dl_186 != 0x09)
				break;
			++esi_101.u2;
		}
		if (esi_101.u2->b0000 == 0x00)
			break;
		if (dwArg08 != 0x00)
		{
			*dwArg08.u1 = eax_111;
			dwArg08.u2 += 4;
		}
		++*dwArg10;
l00403D0E:
		word32 ebx_229 = 0x01;
		uint32 ebp_230 = 0x00;
		while (esi_101.u2->b0000 == 0x5C)
		{
			++esi_101.u2;
			++ebp_230;
		}
		if (esi_101.u2->b0000 == 0x22)
		{
			if ((ebp_230 & 0x01) == 0x00)
			{
				if (edi_176 != 0x00)
				{
					Eq_9 edx_258;
					edx_258.u2 = esi_101.u2 + 1;
					if (edx_258.u2->b0000 != 0x22)
						goto l00403D3E;
					esi_101 = edx_258;
				}
				else
				{
l00403D3E:
					ebx_229 = 0x00;
				}
				edi_176 = (word32) (edi_176 < 0x01);
			}
			ebp_230 >>= 0x01;
		}
		word32 ebp_281 = ebp_230 - 0x01;
		if (ebp_230 != 0x00)
		{
			word32 ebp_790;
			do
			{
				if (eax_111 != null)
				{
					eax_111->b0000 = 0x5C;
					++eax_111;
				}
				++*dwArg14;
				ebp_281 = ebp_790 - 0x01;
				ebp_790 = ebp_281;
			} while (ebp_790 != 0x00);
		}
		uint8 dl_320 = (uint8) esi_101.u2->b0000;
		if (dl_320 != 0x00 && (edi_176 != 0x00 || dl_320 != 0x20 && dl_320 != 0x09))
		{
			if (ebx_229 != 0x00)
			{
				if (eax_111 != null)
				{
					if ((g_a40A8B9[(uint32) dl_320] & 0x04) != 0x00)
					{
						eax_111->b0000 = dl_320;
						++*dwArg14;
						++esi_101.u2;
						++eax_111;
					}
					++eax_111;
					eax_111->bFFFFFFFF = esi_101.u2->b0000;
					++*dwArg14;
					++esi_101.u2;
					goto l00403D0E;
				}
				if ((g_a40A8B9[(uint32) dl_320] & 0x04) != 0x00)
				{
					++*dwArg14;
					++esi_101.u2;
				}
				++*dwArg14;
			}
			++esi_101.u2;
			goto l00403D0E;
		}
		if (eax_111 != null)
		{
			eax_111->b0000 = 0x00;
			++eax_111;
		}
		++*dwArg14;
	}
	if (dwArg08 != 0x00)
		*dwArg08.u1 = 0x00;
	++*dwArg10;
}

// 00403DF0: Register Eq_9 fn00403DF0()
// Called from:
//      Win32CrtStartup
Eq_9 fn00403DF0()
{
	Eq_990 ebx_14;
	ebx_14.u0 = 0x00;
	Eq_992 edi_164;
	edi_164.u0 = 0x00;
	if (g_dw40A8B0 == 0x00)
	{
		Eq_992 eax_22 = GetEnvironmentStringsW();
		edi_164 = eax_22;
		if (eax_22 != 0x00)
			g_dw40A8B0 = 0x01;
		else
		{
			Eq_990 eax_26 = GetEnvironmentStrings();
			ebx_14 = eax_26;
			if (eax_26 == 0x00)
				return 0x00;
			g_dw40A8B0 = 0x02;
		}
	}
	if (g_dw40A8B0 != 0x01)
	{
		if (g_dw40A8B0 != 0x02)
			return 0x00;
		if (ebx_14 == 0x00)
		{
			Eq_990 eax_67 = GetEnvironmentStrings();
			ebx_14 = eax_67;
			if (eax_67 == 0x00)
				return 0x00;
		}
		Eq_990 ebp_74 = ebx_14;
		if (ebx_14.u0->b0000 != 0x00)
		{
			do
			{
				do
					++ebp_74.u0;
				while (ebp_74.u0->b0000 != 0x00);
				ebp_74.u0 = ebp_74 + 0x01;
			} while (*(ebp_74 + (struct Eq_3489 *) 0x01) != 0x00);
		}
		word32 ebp_89 = ebp_74 - ebx_14;
		Eq_9 eax_98 = fn00404F00(ebp_89 + 0x01);
		if (eax_98 != 0x00)
		{
			uint32 ecx_115 = ebp_89 + 0x01 >> 0x02;
			memcpy(eax_98, ebx_14, ecx_115 * 0x04);
			memcpy(eax_98 + ecx_115 * 0x04, ebx_14 + ecx_115 * 0x04, ebp_89 + 0x01 & 0x03);
			FreeEnvironmentStringsA(ebx_14);
			return eax_98;
		}
		else
		{
			FreeEnvironmentStringsA(ebx_14);
			return 0x00;
		}
	}
	else
	{
		if (edi_164 == 0x00)
		{
			Eq_992 eax_170 = GetEnvironmentStringsW();
			edi_164 = eax_170;
			if (eax_170 == 0x00)
				return 0x00;
		}
		Eq_992 esi_179 = edi_164;
		if (edi_164.u0->w0000 != 0x00)
		{
			do
			{
				do
					++esi_179.u0;
				while (esi_179.u0->w0000 != 0x00);
				esi_179.u0 = esi_179 + 0x02;
			} while (*(esi_179 + (struct Eq_3488 *) 0x02) != 0x00);
		}
		int32 esi_201 = (esi_179 - edi_164 >> 0x01) + 0x01;
		Eq_421 eax_214 = WideCharToMultiByte(0x00, 0x00, edi_164, esi_201, 0x00, 0x00, null, null);
		if (eax_214 != 0x00)
		{
			Eq_9 eax_223 = fn00404F00(eax_214);
			Eq_9 ebx_232 = eax_223;
			if (eax_223 != 0x00)
			{
				if (WideCharToMultiByte(0x00, 0x00, edi_164, esi_201, eax_223, eax_214, null, null) == 0x00)
				{
					fn00404EB0(eax_223);
					ebx_232.u0 = 0x00;
				}
				FreeEnvironmentStringsW(edi_164);
				return ebx_232;
			}
		}
		FreeEnvironmentStringsW(edi_164);
		return 0x00;
	}
}

// 00403F80: void fn00403F80(Stack Eq_80 dwArg04)
// Called from:
//      fn00404240
void fn00403F80(Eq_80 dwArg04)
{
	Eq_80 eax_22 = fn00404160(dwArg04);
	if (eax_22 == g_t40A9BC.u0)
		return;
	if (eax_22 != 0x00)
	{
		ui32 dwLoc18_358 = 0x00;
		struct Eq_1195 * eax_155 = (struct Eq_1195 *) g_a40A9E0;
		do
		{
			if (eax_155->dw0000 == eax_22)
			{
				struct Eq_1200 * edi_153 = (struct Eq_1200 *) g_a40A8B8;
				word32 ecx_154;
				for (ecx_154 = 0x40; ecx_154 != 0x00; --ecx_154)
				{
					edi_153->b0000 = (byte) 0x00;
					++edi_153;
				}
				edi_153->b0000 = 0x00;
				struct Eq_1255 * eax_104 = null;
				do
				{
					struct Eq_1350 * esi_59 = (struct Eq_1350 *) ((char *) &g_a40A9E0->t0000 + 16 + (eax_104 + dwLoc18_358 * 0x06) * 0x08);
					while (esi_59->b0000 != 0x00)
					{
						uint8 cl_65 = esi_59->b0001;
						if (cl_65 == 0x00)
							break;
						struct Eq_1360 * edx_77 = (uint32) esi_59->b0000;
						if ((uint32) cl_65 >= edx_77)
						{
							byte cl_81 = (byte) eax_104[4237784];
							do
							{
								edx_77[4237497] = (struct Eq_1360) (edx_77[4237497] | cl_81);
								++edx_77;
							} while ((uint32) esi_59->b0001 >= edx_77);
						}
						++esi_59;
					}
					++eax_104;
				} while (eax_104 < (struct Eq_1255 *) 0x04);
				g_t40A9BC.u0 = (int32) eax_22;
				g_dw40A9C0 = fn004041B0(eax_22);
				struct Eq_1412 * ecx_133 = (dwLoc18_358 << 0x04) + 0x0040A9E4 + (dwLoc18_358 << 0x04) * 0x02;
				uip32 ebx_130 = (dwLoc18_358 << 0x04)->a40A9E8[dwLoc18_358 << 0x04].dw0000;
				uip32 ecx_141 = ecx_133->dw0008;
				g_dw40A9C8 = ecx_133->dw0000;
				g_dw40A9CC = ebx_130;
				g_dw40A9D0 = ecx_141;
				return;
			}
			++eax_155;
			++dwLoc18_358;
		} while (eax_155 < &g_t40AAD0);
		Eq_1218 tLoc14;
		if (GetCPInfo(eax_22, &tLoc14) != 0x01)
		{
			if (g_dw40A9D4 == 0x00)
				return;
			fn00404210();
		}
		else
		{
			struct Eq_1227 * edi_200 = (struct Eq_1227 *) g_a40A8B8;
			word32 ecx_205;
			for (ecx_205 = 0x40; ecx_205 != 0x00; --ecx_205)
			{
				edi_200->b0000 = (byte) 0x00;
				++edi_200;
			}
			edi_200->b0000 = 0x00;
			uip32 eax_214;
			if (tLoc14.MaxCharSize > 0x01)
			{
				union Eq_1273 * esi_219 = (union Eq_1273 *) tLoc14.LeadByte;
				if (Mem209[&tLoc14 + 6:byte] != 0x00)
				{
					do
					{
						uint8 al_224 = esi_219->u1.b0001;
						if (al_224 == 0x00)
							break;
						struct Eq_1292 * ecx_236 = (uint32) esi_219->u1.b0000;
						if ((uint32) al_224 >= ecx_236)
						{
							do
							{
								ecx_236[4237497] = (struct Eq_1292) (ecx_236[4237497] | 0x04);
								++ecx_236;
							} while ((uint32) esi_219->u1.b0001 >= ecx_236);
						}
						esi_219 = (union Eq_1273 *) ((char *) esi_219 + 2);
					} while (esi_219->u1.b0000 != 0x00);
				}
				struct Eq_1281 * eax_257 = (struct Eq_1281 *) 0x01;
				do
				{
					eax_257[4237497] = (struct Eq_1281) (eax_257[4237497] | 0x08);
					++eax_257;
				} while (eax_257 < (struct Eq_1281 *) 0xFF);
				g_t40A9BC.u0 = (int32) eax_22;
				eax_214 = fn004041B0(eax_22);
			}
			else
			{
				g_t40A9BC.u0 = 0x00;
				eax_214 = 0x00;
			}
			g_dw40A9C0 = eax_214;
			g_dw40A9C8 = 0x00;
			g_dw40A9CC = 0x00;
			g_dw40A9D0 = 0x00;
		}
	}
	else
		fn00404210();
}

// 00404160: Register Eq_80 fn00404160(Stack Eq_80 dwArg04)
// Called from:
//      fn00403F80
Eq_80 fn00404160(Eq_80 dwArg04)
{
	g_dw40A9D4 = 0x00;
	Eq_80 eax_13 = dwArg04;
	switch (dwArg04)
	{
	case ~0x01:
		g_dw40A9D4 = 0x01;
		return GetOEMCP();
	case ~0x02:
		g_dw40A9D4 = 0x01;
		return GetACP();
	default:
		if (dwArg04 == ~0x03)
		{
			g_dw40A9D4 = 0x01;
			eax_13.u0 = g_t40AE40.u0;
		}
		return eax_13;
	}
}

// 004041B0: Register word32 fn004041B0(Stack Eq_80 dwArg04)
// Called from:
//      fn00403F80
word32 fn004041B0(Eq_80 dwArg04)
{
	if (dwArg04 <= 0x03B6 && dwArg04 >= 0x03A4)
	{
		switch (dwArg04)
		{
		case 0x03A4:
			return 0x0411;
		case 933:
		case 0x03A6:
		case 0x03A7:
		case 0x03A9:
		case 0x03AA:
		case 939:
		case 0x03AC:
		case 0x03AD:
		case 0x03AE:
		case 0x03AF:
		case 944:
		case 0x03B1:
		case 0x03B2:
		case 0x03B3:
		case 0x03B4:
			break;
		case 0x03A8:
			return 0x0804;
		case 949:
			return 0x0412;
		case 0x03B6:
			return 0x0404;
		}
	}
	return 0x00;
}

// 00404210: void fn00404210()
// Called from:
//      fn00403F80
void fn00404210()
{
	struct Eq_1473 * edi_11 = (struct Eq_1473 *) g_a40A8B8;
	word32 ecx_12;
	for (ecx_12 = 0x40; ecx_12 != 0x00; --ecx_12)
	{
		edi_11->b0000 = (byte) 0x00;
		++edi_11;
	}
	edi_11->b0000 = 0x00;
	g_dw40A9C8 = 0x00;
	g_t40A9BC.u0 = 0x00;
	g_dw40A9C0 = 0x00;
	g_dw40A9CC = 0x00;
	g_dw40A9D0 = 0x00;
}

// 00404240: void fn00404240()
// Called from:
//      Win32CrtStartup
void fn00404240()
{
	fn00403F80(~0x02);
}

// 00404250: void fn00404250()
// Called from:
//      Win32CrtStartup
void fn00404250()
{
	Eq_9 eax_20 = fn00404F00(0x0100);
	struct Eq_1513 * esi_29 = (struct Eq_1513 *) (eax_20.u2 + 4);
	if (eax_20 == 0x00)
		fn004029F0(0x1B);
	g_t40CE60.u1 = (word32 *) eax_20;
	g_t40CF60.u0 = 0x20;
	if ((word32) eax_20 + 0x0100 > eax_20)
	{
		do
		{
			esi_29->b0000 = 0x00;
			++esi_29;
			esi_29->dwFFFFFFF8 = ~0x00;
			esi_29->bFFFFFFFD = 0x0A;
		} while (g_t40CE60.u1 + 64 > esi_29);
	}
	Eq_1531 tLoc44;
	GetStartupInfoA(&tLoc44);
	if (tLoc44.cbReserved2 != 0x00 && tLoc44.lpReserved2 != null)
	{
		Eq_1569 eax_79;
		eax_79.u0 = tLoc44.lpReserved2;
		Eq_80 esi_107;
		esi_107.u0 = eax_79.u0->u0;
		Eq_1576 edi_150 = (Eq_1576) (eax_79 + 4);
		Eq_1579 ebx_145;
		ebx_145.u0 = (word32) esi_107 + (eax_79 + (union Eq_80 *) 4);
		if (esi_107 >= 0x0800)
			esi_107.u0 = 0x0800;
		if (g_t40CF60.u0 < esi_107)
		{
			up32 * ebp_109 = g_a40CE64;
			do
			{
				struct Eq_1593 * eax_120 = (struct Eq_1593 *) (fn00404F00(0x0100).u2 + 4);
				if (eax_120 == null)
				{
					esi_107.u0 = g_t40CF60.u0;
					break;
				}
				*ebp_109 = eax_120;
				g_t40CF60.u0 = (int32) (g_t40CF60.u0 + 0x20);
				if (eax_120 + 32 > eax_120)
				{
					do
					{
						eax_120->b0000 = 0x00;
						++eax_120;
						eax_120->dwFFFFFFF8 = ~0x00;
						eax_120->bFFFFFFFD = 0x0A;
					} while (*ebp_109 + 0x0100 > eax_120);
				}
				++ebp_109;
			} while (g_t40CF60.u0 < esi_107);
		}
		Eq_80 ebp_138;
		ebp_138.u0 = 0x00;
		if (esi_107 > 0x00)
		{
			do
			{
				Eq_107 ecx_147;
				ecx_147.u1 = *ebx_145.u0;
				if (ecx_147 != ~0x00)
				{
					byte al_151 = *edi_150;
					if ((al_151 & 0x01) != 0x00 && ((al_151 & 0x08) != 0x00 || GetFileType(ecx_147) != 0x00))
					{
						struct Eq_1671 * ecx_181 = ((ebp_138 & ~0x18) >> 0x03)->dw40CE60 + (ebp_138 & 0x1F) * 0x08;
						ecx_181->dw0000 = *ebx_145.u0;
						ecx_181->b0004 = *edi_150;
					}
				}
				ebp_138 = (word32) ebp_138.u0 + 1;
				edi_150 = (Eq_1576) (edi_150 + (BYTE *) 0x01);
				ebx_145.u0 = ebx_145 + 0x04;
			} while (ebp_138 < esi_107);
		}
	}
	int32 esi_197;
	for (esi_197 = 0x00; esi_197 < 0x03; ++esi_197)
	{
		struct Eq_1691 * edi_205 = (struct Eq_1691 *) (g_t40CE60.u1 + esi_197 * 2);
		if (edi_205->t0000.u1 == ~0x00)
		{
			edi_205->b0004 = 0x81;
			Eq_10 eax_213;
			eax_213.u0 = ~0x09;
			if (esi_197 != 0x00)
				eax_213 = (cond(esi_197 - 1 - 0x01) & 0x02) + ~0x0B;
			Eq_107 eax_239 = GetStdHandle(eax_213);
			if (eax_239 != ~0x00)
			{
				Eq_10 eax_249 = GetFileType(eax_239);
				if (eax_249 == 0x00)
					goto l00404404;
				edi_205->t0000.u1 = (HANDLE) eax_239;
				if ((eax_249 & 0xFF) == 0x02)
					edi_205->b0004 |= 0x40;
				else if ((eax_249 & 0xFF) == 0x03)
					edi_205->b0004 |= 0x08;
			}
			else
			{
l00404404:
				edi_205->b0004 |= 0x40;
			}
		}
		else
			edi_205->b0004 |= 0x80;
	}
	SetHandleCount(g_t40CF60.u0);
}

// 00404430: Register word32 fn00404430()
// Called from:
//      Win32CrtStartup
word32 fn00404430()
{
	Eq_107 eax_10 = HeapCreate(0x01, 0x1000, 0x00);
	g_t40CE54.u1 = (HANDLE) eax_10;
	if (eax_10 == 0x00)
		return 0x00;
	if (fn00404FB0() != 0x00)
		return 0x01;
	HeapDestroy(g_t40CE54.u1);
	return 0x00;
}

// 00404550: void fn00404550()
// Called from:
//      fn004029F0
void fn00404550()
{
	word32 eax_5 = g_dw40A5DC;
	if (eax_5 == 0x01 || eax_5 == 0x00 && g_dw40A5E0 == 0x01)
	{
		fn00404590(252);
		<anonymous> * eax_25 = g_ptr40AB70;
		if (eax_25 != null)
			eax_25();
		fn00404590(0xFF);
	}
}

// 00404590: void fn00404590(Stack word32 dwArg04)
// Called from:
//      fn004029F0
//      fn00404550
void fn00404590(word32 dwArg04)
{
	ui32 ecx_29 = 0x00;
	struct Eq_1834 * eax_23 = (struct Eq_1834 *) g_a40AAE0;
	while (eax_23->dw0000 != dwArg04)
	{
		++eax_23;
		++ecx_29;
		if (eax_23 >= &g_ptr40AB70)
			break;
	}
	if (g_a40AAE0[ecx_29] != dwArg04)
		return;
	if (g_dw40A5DC != 0x01 && (g_dw40A5DC != 0x00 || g_dw40A5E0 != 0x01))
	{
		if (dwArg04 == 252)
			return;
		word32 dwLoc0104;
		if (GetModuleFileNameA(0x00, &dwLoc0104, 0x0104) == 0x00)
			memcpy(&dwLoc0104, &g_t4077AC, 0x14);
		union Eq_1877 * ebp_138 = &dwLoc0104;
		if (strlen(&dwLoc0104) > 0x3B)
		{
			ptr32 fp;
			ebp_138 = (word32) (strlen(&dwLoc0104) - ~0x00) + (fp - 0x0140);
			fn004057B0(ebp_138, &g_b4077A8, 0x03);
		}
		word32 dwLoc01A4;
		memcpy(&dwLoc01A4, &g_t40778C, 0x18);
		ptr32 edi_199 = (char *) &dwLoc01A4 + ((word32) strlen(&dwLoc01A4) + 1);
		strcpy(edi_199 - 0x01, ebp_138);
		ptr32 edi_223 = (char *) &dwLoc01A4 + ((word32) strlen(&dwLoc01A4) + 1);
		strcpy(edi_223 - 0x01, "\n\n");
		char * edi_236 = (char *) *((char *) &g_a40AAE0->ptr0004 + ecx_29 * 0x08);
		ptr32 edi_250 = (char *) &dwLoc01A4 + ((word32) strlen(&dwLoc01A4) + 1);
		strcpy(edi_250 - 0x01, edi_236);
		fn00405710();
		return;
	}
	Eq_107 esi_49;
	if (g_t40CE60.u1 != 0x00)
	{
		esi_49.u1 = g_t40CE60.u1[4];
		if (esi_49 != ~0x00)
		{
l00404757:
			Eq_1998 edx_65;
			edx_65.u0 = *((char *) &g_a40AAE0->ptr0004 + ecx_29 * 0x08);
			Eq_10 tLoc01A8;
			WriteFile(esi_49, edx_65, strlen(edx_65), &tLoc01A8, null);
			return;
		}
	}
	esi_49 = GetStdHandle(~0x0B);
	goto l00404757;
}

// 00404EB0: void fn00404EB0(Stack Eq_9 dwArg04)
// Called from:
//      fn00403A80
//      fn00403DF0
void fn00404EB0(Eq_9 dwArg04)
{
	Eq_2024 tLoc08;
	Eq_2022 tLoc04;
	if (dwArg04 == 0x00)
		return;
	byte * eax_21 = fn00405260(dwArg04, &tLoc04, &tLoc08);
	if (eax_21 == null)
		HeapFree(g_t40CE54.u1, 0x00, dwArg04);
	else
		fn004052C0(tLoc04, tLoc08, eax_21);
}

// 00404F00: Register word32 fn00404F00(Stack Eq_421 dwArg04)
// Called from:
//      fn00403A80
//      fn00403B70
//      fn00403DF0
//      fn00404250
word32 fn00404F00(Eq_421 dwArg04)
{
	return fn00404F20(dwArg04, g_dw40B7F0);
}

// 00404F20: Register word32 fn00404F20(Stack Eq_421 dwArg04, Stack word32 dwArg08)
// Called from:
//      fn00404F00
word32 fn00404F20(Eq_421 dwArg04, word32 dwArg08)
{
	Eq_421 esi_10 = dwArg04;
	if (dwArg04 > ~0x1F)
		return 0x00;
	if (dwArg04 == 0x00)
		esi_10.u0 = 0x01;
	word32 eax_104;
	do
	{
		eax_104 = 0x00;
		if (esi_10 <= ~0x1F)
			eax_104 = fn00404F70(esi_10);
		if (eax_104 != 0x00 || dwArg08 == 0x00)
			return eax_104;
	} while (fn00405DE0(esi_10) != 0x00);
	eax_104 = 0x00;
	return eax_104;
}

// 00404F70: Register Eq_9 fn00404F70(Stack Eq_421 dwArg04)
// Called from:
//      fn00404F20
Eq_9 fn00404F70(Eq_421 dwArg04)
{
	Eq_1787 esi_9 = (word32) dwArg04 + 0x0F & ~0x0F;
	Eq_9 eax_17;
	if (esi_9 <= g_t40B664)
	{
		eax_17 = fn00405310(esi_9 >> 0x04);
		if (eax_17 != 0x00)
			return eax_17;
	}
	eax_17 = HeapAlloc(g_t40CE54.u1, 0x00, esi_9);
	return eax_17;
}

// 00404FB0: Register Eq_9 fn00404FB0()
// Called from:
//      fn00404430
//      fn00405310
Eq_9 fn00404FB0()
{
	Eq_9 esi_28;
	if (g_dw40B658 == 0x00)
		esi_28.u0 = 0x0040AE48;
	else
	{
		Eq_9 eax_26 = HeapAlloc(g_t40CE54.u1, 0x00, 0x0814);
		esi_28 = eax_26;
		if (eax_26 == 0x00)
			return 0x00;
	}
	Eq_9 eax_56 = VirtualAlloc(0x00, 0x00400000, 0x2000, 0x04);
	Eq_9 ebx_178 = eax_56;
	if (eax_56 != 0x00)
	{
		if (VirtualAlloc(eax_56, 0x00010000, 0x1000, 0x04) != 0x00)
		{
			if (esi_28 == 0x0040AE48)
			{
				if (g_ptr40AE48 == null)
					g_ptr40AE48 = &g_ptr40AE48;
				if (g_t40AE4C.u1 == 0x00)
					g_t40AE4C.u1 = (word32 *) 0x0040AE48;
			}
			else
			{
				*esi_28.u1 = &g_ptr40AE48;
				esi_28.u2[4] = (struct Eq_3482) g_t40AE4C.u1;
				g_t40AE4C.u1 = (word32 *) esi_28;
				*esi_28.u2[4].b0000 = (struct Eq_3482) esi_28;
			}
			esi_28.u2[0x0810] = (struct Eq_3482) eax_56;
			esi_28.u2[8] = (struct Eq_3482) 0x00;
			esi_28.u2[0x0C] = (struct Eq_3482) 0x10;
			Eq_2208 ebp_129;
			ebp_129.u0 = 0x00;
			do
			{
				Eq_2213 edi_145;
				edi_145.u0 = esi_28 + ebp_129;
				if (ebp_129 < 0x10)
					edi_145.u0->t0010.u0 = 0xF0;
				else
					edi_145.u0->t0010.u0 = ~0x00;
				edi_145.u0->b0410 = ~0x0E;
				ebp_129.u0 = (word32) ebp_129 + 1;
			} while (ebp_129 < 0x0400);
			Eq_9 edi_162 = eax_56;
			word32 ecx_167;
			for (ecx_167 = 0x4000; ecx_167 != 0x00; --ecx_167)
			{
				*edi_162.u1 = 0x00;
				edi_162.u1 = edi_162 + 4;
			}
			if ((word32) esi_28.u2[0x0810].t0810 + 0x0000F7F0 > eax_56)
			{
				do
				{
					*ebx_178.u1 = ebx_178.u2 + 8;
					ebx_178.u2[4] = (struct Eq_3482) 0xF0;
					ebx_178.u4->b00F8 = ~0x00;
					ebx_178.u1 = ebx_178 + 0x1000;
				} while ((word32) esi_28.u2[0x0810].t0810 + 0x0000F7F0 > ebx_178);
			}
			return esi_28;
		}
		VirtualFree(eax_56, 0x00, 0x8000);
	}
	if (esi_28 != 0x0040AE48)
		HeapFree(g_t40CE54.u1, 0x00, esi_28);
	return 0x00;
}

// 00405120: void fn00405120(Stack Eq_9 dwArg04)
// Called from:
//      fn00405180
void fn00405120(Eq_9 dwArg04)
{
	VirtualFree(dwArg04.u2[0x0810], 0x00, 0x8000);
	if (g_t40B65C.u1 == dwArg04)
		g_t40B65C.u1 = (word32 *) dwArg04.u2[4];
	if (dwArg04 == 0x0040AE48)
		g_dw40B658 = 0x00;
	else
	{
		*dwArg04.u2[4].b0000 = (struct Eq_3482) *dwArg04.u1;
		*((word32) *dwArg04.u1 + 4) = (word32) dwArg04.u2[4];
		HeapFree(g_t40CE54.u1, 0x00, dwArg04);
	}
}

// 00405180: void fn00405180(Stack int32 dwArg04)
// Called from:
//      fn004052C0
void fn00405180(int32 dwArg04)
{
	Eq_9 esi_128;
	esi_128.u1 = g_t40AE4C.u1;
	do
	{
		if (esi_128.u2[0x0810] != 0x00)
		{
			int32 ebp_23 = 0x03FF;
			struct Eq_2338 * ebx_24 = esi_128 + (struct Eq_2337 *) 0x040F;
			word32 dwLoc04_154 = 0x00;
			int32 edi_27;
			for (edi_27 = 0x003FF000; edi_27 >= 0x00; edi_27 -= 0x1000)
			{
				if (ebx_24->b0000 == 0xF0 && VirtualFree((byte) ((esi_128.u2))[0x0810].b0000 + edi_27, 0x1000, 0x4000) != 0x00)
				{
					ebx_24->b0000 = ~0x00;
					--g_dw40B660;
					int32 eax_52 = (int32) esi_128.u2[0x0C];
					if (eax_52 == ~0x00 || ebp_23 < eax_52)
						esi_128.u2[0x0C] = (struct Eq_3482) ebp_23;
					int32 v18_66 = dwArg04 - 0x01;
					++dwLoc04_154;
					dwArg04 = v18_66;
					if (v18_66 == 0x00)
						break;
				}
				--ebp_23;
				ebx_24 -= (struct Eq_2348 *) 0x01;
			}
			esi_128.u1 = esi_128.u2[4];
			if (dwLoc04_154 != 0x00 && (esi_128.u2)[16] == ~0x00)
			{
				int32 edx_105 = 0x01;
				struct Eq_2417 * ecx_100 = esi_128 + (struct Eq_2416 *) 0x0011;
				while (ecx_100->b0000 == ~0x00)
				{
					++edx_105;
					ecx_100 += (struct Eq_2423 *) 0x01;
					if (edx_105 >= 0x0400)
						break;
				}
				if (edx_105 == 0x0400)
					fn00405120(esi_128);
			}
		}
	} while (esi_128 != g_t40AE4C.u1 && dwArg04 > 0x00);
}

// 00405260: Register int32 fn00405260(Stack Eq_9 dwArg04, Stack (ptr32 (ptr32 Eq_2436)) dwArg08, Stack (ptr32 ui32) dwArg0C)
// Called from:
//      fn00404EB0
int32 fn00405260(Eq_9 dwArg04, struct Eq_2436 ** dwArg08, ui32 * dwArg0C)
{
	struct Eq_2436 * ecx_34 = (struct Eq_2436 *) &g_ptr40AE48;
	do
	{
		Eq_9 eax_9;
		eax_9.u1 = ecx_34->t0810.u1;
		if (eax_9 != 0x00 && (eax_9 < dwArg04 && (word32) eax_9 + 0x00400000 > dwArg04))
		{
			*dwArg08 = (struct Eq_2436 **) ecx_34;
			*dwArg0C = dwArg04 & ~0x0FFF;
			return (dwArg04 - (dwArg04 & ~0x0FFF) - 0x0100 >> 0x04) + 8 + (dwArg04 & ~0x0FFF);
		}
		ecx_34 = ecx_34->ptr0000;
	} while (ecx_34 != &g_ptr40AE48);
	return 0x00;
}

// 004052C0: void fn004052C0(Stack (ptr32 Eq_2040) dwArg04, Stack int32 dwArg08, Stack (ptr32 byte) dwArg0C)
// Called from:
//      fn00404EB0
void fn004052C0(struct Eq_2040 * dwArg04, int32 dwArg08, byte * dwArg0C)
{
	struct Eq_2478 * ecx_9 = (struct Eq_2478 *) ((char *) dwArg04 + (dwArg08 - dwArg04->dw0810 >> 0x0C));
	ecx_9->b0010 += *dwArg0C;
	*dwArg0C = 0x00;
	ecx_9->b0410 = ~0x0E;
	if (ecx_9->b0010 == 0xF0)
	{
		++g_dw40B660;
		if (g_dw40B660 == 0x20)
			fn00405180(0x10);
	}
}

// 00405310: Register word32 fn00405310(Stack uint32 dwArg04)
// Called from:
//      fn00404F70
word32 fn00405310(uint32 dwArg04)
{
	Eq_9 edi_168;
	edi_168.u1 = g_t40B65C.u1;
	do
	{
		if (edi_168.u2[0x0810] != 0x00)
		{
			Eq_2524 esi_22 = (Eq_2524) edi_168.u2[8];
			if (esi_22 < 0x0400)
			{
				int32 ebp_26 = esi_22 << 0x0C;
				do
				{
					Eq_9 cl_31;
					cl_31.u0 = (&esi_22.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2809 *) 16];
					Eq_9 bl_74 = (byte) dwArg04;
					uint32 eax_35 = (uint32) cl_31;
					if (eax_35 >= dwArg04 && (cl_31 != ~0x00 && (uint32) (&(((esi_22.ptr0000)->a0000))[0].u0)[edi_168 + (struct Eq_2549 *) 0x0410] > dwArg04))
					{
						word32 eax_58 = fn00405590((byte) edi_168.u2[0x0810].b0000 + ebp_26, eax_35, dwArg04);
						if (eax_58 != 0x00)
						{
							g_t40B65C.u1 = (word32 *) edi_168;
							(&esi_22.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2576 *) 16] = (uint8) ((&esi_22.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2570 *) 16] - bl_74);
							edi_168.u2[8] = (struct Eq_3482) esi_22;
							return eax_58;
						}
						(&esi_22.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2583 *) 0x0410] = (uint8) bl_74;
					}
					ebp_26 += 0x1000;
					esi_22 = (Eq_2524) ((char *) esi_22.ptr0000->a0000 + 1);
				} while (ebp_26 < 0x00400000);
			}
			word32 ebp_125 = 0x00;
			Eq_2524 esi_101 = (Eq_2524) 0x00;
			if (edi_168.u2[8] > 0x00)
			{
				do
				{
					Eq_9 cl_103;
					cl_103.u0 = (&esi_101.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2816 *) 16];
					Eq_9 bl_146 = (byte) dwArg04;
					uint32 eax_107 = (uint32) cl_103;
					if (eax_107 >= dwArg04 && (cl_103 != ~0x00 && (uint32) (&(((esi_101.ptr0000)->a0000))[0].u0)[edi_168 + (struct Eq_2836 *) 0x0410] > dwArg04))
					{
						word32 eax_130 = fn00405590((byte) edi_168.u2[0x0810].b0000 + ebp_125, eax_107, dwArg04);
						if (eax_130 != 0x00)
						{
							g_t40B65C.u1 = (word32 *) edi_168;
							(&esi_101.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2857 *) 16] = (uint8) ((&esi_101.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2852 *) 16] - bl_146);
							edi_168.u2[8] = (struct Eq_3482) esi_101;
							return eax_130;
						}
						(&esi_101.ptr0000->a0000[0].u0)[edi_168 + (struct Eq_2864 *) 0x0410] = (uint8) bl_146;
					}
					ebp_125 += 0x1000;
					esi_101 = (Eq_2524) (esi_101 + (struct Eq_2828 *) 0x01);
				} while (edi_168.u2[8] > esi_101);
			}
		}
		edi_168.u1 = *edi_168.u1;
	} while (g_t40B65C.u1 != edi_168);
	Eq_9 esi_171;
	esi_171.u0 = 0x0040AE48;
	byte bl_382;
	do
	{
		byte bl_308 = (byte) dwArg04;
		if (esi_171.u2[0x0810] != null && (esi_171.u2)[0x0C] != ~0x00)
		{
			int32 edx_185 = (int32) esi_171.u2[0x0C];
			int32 ecx_187 = edx_185 + 16;
			if (edx_185 >= 0x03F0)
				ecx_187 = 0x0400;
			int32 edi_192 = edx_185 + 0x01;
			if (ecx_187 > edx_185 + 0x01)
			{
				while ((esi_171.u2 + 16)[edi_192] == ~0x00)
				{
					++edi_192;
					if (ecx_187 <= edi_192)
						break;
				}
			}
			if (VirtualAlloc((byte) esi_171.u2[0x0810].b0000 + (edx_185 << 0x0C), edi_192 - edx_185 << 0x0C, 0x1000, 0x04) != (byte) ((esi_171.u2))[0x0810].b0000 + (edx_185 << 0x0C))
				return 0x00;
			else
			{
				int32 ecx_249 = (int32) esi_171.u2[0x0C];
				struct Eq_2708 * ebp_252 = (struct Eq_2708 *) ((byte) esi_171.u2[0x0810].b0000 + (ecx_249 << 0x0C));
				while (ecx_249 < edi_192)
				{
					ebp_252->dw0000 = &ebp_252->dw0000 + 2;
					++ebp_252;
					ebp_252->dwFFFFF004 = 0xF0;
					ebp_252->bFFFFF0F8 = ~0x00;
					++ecx_249;
					struct Eq_2733 * edx_263 = esi_171 - 1 + ecx_249;
					edx_263->b0010 = 0xF0;
					edx_263->b0410 = ~0x0E;
				}
				g_t40B65C.u1 = (word32 *) esi_171;
				if (edi_192 < 0x0400)
				{
					while ((esi_171.u2 + 16)[edi_192] != ~0x00)
					{
						++edi_192;
						if (edi_192 >= 0x0400)
							break;
					}
				}
				int32 ecx_290 = (int32) esi_171.u2[0x0C];
				esi_171.u2[0x0C] = (struct Eq_3482) ~0x00;
				if (edi_192 < 0x0400)
					esi_171.u2[0x0C] = (struct Eq_3482) edi_192;
				struct Eq_2769 * eax_302 = (struct Eq_2769 *) ((byte) esi_171.u2[0x0810].b0000 + (ecx_290 << 0x0C));
				eax_302->b0008 = bl_308;
				esi_171.u2[8] = (struct Eq_3482) ecx_290;
				(esi_171.u2 + 16)[ecx_290] = (struct Eq_3482) ((esi_171.u2 + 16)[ecx_290] - bl_308);
				eax_302->dw0000 = (char *) &eax_302->dw0000 + dwArg04 + 8;
				eax_302->dw0004 -= dwArg04;
				return (word32) esi_171.u2[0x0810].t0010 + 0x00F0 + (ecx_290 << 0x0C);
			}
		}
		bl_382 = (byte) dwArg04;
		esi_171.u1 = *esi_171.u1;
	} while (esi_171 != 0x0040AE48);
	Eq_9 eax_352 = fn00404FB0();
	if (eax_352 == 0x00)
		return 0x00;
	struct Eq_2619 * edx_377 = (struct Eq_2619 *) eax_352.u2[0x0810];
	edx_377->b0008 = bl_382;
	g_t40B65C.u1 = (word32 *) eax_352;
	edx_377->dw0000 = (char *) &edx_377->dw0000 + dwArg04 + 8;
	edx_377->dw0004 = 0xF0 - dwArg04;
	eax_352.u2[16] = (struct Eq_3482) (eax_352.u2[16] - bl_382);
	return (word32) eax_352.u2[0x0810].t0010 + 0x00F0;
}

// 00405590: Register ui32 fn00405590(Stack (ptr32 Eq_2557) dwArg04, Stack uint32 dwArg08, Stack uint32 dwArg0C)
// Called from:
//      fn00405310
ui32 fn00405590(struct Eq_2557 * dwArg04, uint32 dwArg08, uint32 dwArg0C)
{
	Eq_2871 edi_20;
	edi_20.u0 = dwArg04->b0000;
	Eq_2871 dl_269 = (byte) dwArg0C;
	uint32 ecx_16 = (uint32) dwArg04[4];
	Eq_2871 ebp_130 = edi_20;
	if (dwArg0C > ecx_16)
	{
		Eq_2871 ecx_24;
		ecx_24.u1 = edi_20.u1 + ecx_16;
		if (*ecx_24.u1 != 0x00)
			ebp_130 = ecx_24;
		uint32 esi_111 = dwArg08;
		while (ebp_130.u1 + dwArg0C < dwArg04 + 0x00F8)
		{
			byte dl_85 = (byte) dwArg0C;
			uint8 cl_40 = *ebp_130.u1;
			if (cl_40 == 0x00)
			{
				Eq_2871 ecx_129;
				ecx_129.u1 = (word32) ebp_130 + 1;
				uint32 ebx_52 = 0x01;
				while (*ecx_129.u1 == 0x00)
				{
					ecx_129.u1 = (word32) ecx_129 + 1;
					++ebx_52;
				}
				if (ebx_52 >= dwArg0C)
				{
					Eq_2871 esi_70;
					esi_70.u1 = ebp_130.u1 + dwArg0C;
					if (esi_70 < dwArg04 + 0x00F8)
					{
						dwArg04->b0000 = (byte) esi_70;
						dwArg04[4] = (struct Eq_2557) (ebx_52 - dwArg0C);
					}
					else
					{
						dwArg04[4] = (struct Eq_2557) 0x00;
						dwArg04->b0000 = (byte) (dwArg04 + 8);
					}
					*ebp_130.u1 = dl_85;
					return dwArg04 + ((ebp_130 - dwArg04 << 0x04) + 0x80);
				}
				if (edi_20 == ebp_130)
				{
					dwArg04[4] = (struct Eq_2557) ebx_52;
					ebp_130 = ecx_129;
				}
				else
				{
					esi_111 -= ebx_52;
					if (dwArg0C > esi_111)
						return 0x00;
					ebp_130 = ecx_129;
				}
			}
			else
				ebp_130.u1 += (uint32) cl_40;
		}
		Eq_2871 ebp_141;
		ebp_141.u1 = dwArg04 + 8;
		if (edi_20 > dwArg04 + 8)
		{
			do
			{
				byte dl_199 = (byte) dwArg0C;
				if (ebp_141.u1 + dwArg0C > dwArg04 + 0x00F7)
					return 0x00;
				uint8 cl_156 = *ebp_141.u1;
				if (cl_156 == 0x00)
				{
					Eq_2871 ecx_167;
					ecx_167.u1 = (word32) ebp_141 + 1;
					uint32 ebx_168 = 0x01;
					while (*ecx_167.u1 == 0x00)
					{
						ecx_167.u1 = (word32) ecx_167 + 1;
						++ebx_168;
					}
					if (ebx_168 >= dwArg0C)
					{
						Eq_3015 esi_185 = ebp_141.u1 + dwArg0C;
						if (esi_185 < dwArg04 + 0x00F8)
						{
							dwArg04->b0000 = (byte) esi_185;
							dwArg04[4] = (struct Eq_2557) (ebx_168 - dwArg0C);
						}
						else
						{
							dwArg04[4] = (struct Eq_2557) 0x00;
							dwArg04->b0000 = (byte) (dwArg04 + 8);
						}
						*ebp_141.u1 = dl_199;
						return dwArg04 + ((ebp_141 - dwArg04 << 0x04) + 0x80);
					}
					esi_111 -= ebx_168;
					if (dwArg0C > esi_111)
						return 0x00;
					ebp_141 = ecx_167;
				}
				else
					ebp_141.u1 += (uint32) cl_156;
			} while (edi_20 > ebp_141);
		}
		return 0x00;
	}
	else
	{
		*edi_20.u1 = (byte) dl_269;
		if (edi_20.u1 + dwArg0C < dwArg04 + 0x00F8)
		{
			dwArg04->b0000 = (byte) (dwArg04->b0000 + dwArg0C);
			dwArg04[4] = (struct Eq_2557) (dwArg04[4] - dwArg0C);
		}
		else
		{
			dwArg04[4] = (struct Eq_2557) 0x00;
			dwArg04->b0000 = (byte) (dwArg04 + 8);
		}
		return dwArg04 + ((edi_20 - dwArg04 << 0x04) + 0x80);
	}
}

// 00405710: void fn00405710()
// Called from:
//      fn00404590
void fn00405710()
{
	ptr32 fp;
	word32 esi_101 = 0x00;
	if (g_t40B668 == null)
	{
		Eq_3 eax_18 = LoadLibraryA(0x004077F8);
		if (eax_18 == 0x00)
			return;
		Eq_3078 eax_30 = GetProcAddress(eax_18, 4225004);
		g_t40B668 = eax_30;
		if (eax_30 == null)
			return;
		g_t40B66C = GetProcAddress(eax_18, 4224988);
		g_t40B670 = GetProcAddress(eax_18, 0x004077C8);
	}
	struct Eq_3083 * esp_102 = fp - 0x0C;
	Eq_3078 eax_64 = g_t40B66C;
	if (eax_64 != null)
	{
		eax_64();
		word32 eax_75;
		esi_101 = eax_75;
	}
	if (esi_101 != 0x00 && g_t40B670 != null)
	{
		esp_102->dwFFFFFFFC = esi_101;
		g_t40B670();
		word32 eax_96;
		esi_101 = eax_96;
	}
	word32 eax_104 = esp_102->dw0018;
	word32 ecx_105 = esp_102->dw0014;
	word32 edx_106 = esp_102->dw0010;
	struct Eq_3139 * esp_107 = esp_102 - 4;
	esp_107->dw0000 = eax_104;
	esp_107->dwFFFFFFFC = ecx_105;
	esp_107->dwFFFFFFF8 = edx_106;
	esp_107->dwFFFFFFF4 = esi_101;
	g_t40B668();
}

// 004057B0: void fn004057B0(Stack (ptr32 Eq_1877) dwArg04, Stack (ptr32 byte) dwArg08, Stack uint32 dwArg0C)
// Called from:
//      fn00404590
void fn004057B0(union Eq_1877 * dwArg04, byte * dwArg08, uint32 dwArg0C)
{
	uint32 ecx_33 = dwArg0C;
	if (dwArg0C == 0x00)
		return;
	uint32 ebx_130 = dwArg0C;
	byte * esi_189 = dwArg08;
	union Eq_1877 * edi_123 = dwArg04;
	uint32 ecx_126;
	uint32 ecx_144;
	if ((dwArg08 & 0x03) == 0x00)
	{
		ecx_126 = dwArg0C >> 0x02;
		if (dwArg0C >> 0x02 == 0x00)
			goto l004057F5;
	}
	else
	{
		byte al_191;
		do
		{
			al_191 = *esi_189;
			edi_123->u0 = al_191;
			++esi_189;
			edi_123 = (union Eq_1877 *) ((char *) edi_123 + 1);
			--ecx_33;
			if (ecx_33 == 0x00)
				return;
			if (al_191 == 0x00)
			{
				while ((edi_123 & 0x03) != 0x00)
				{
					edi_123->u0 = al_191;
					edi_123 = (union Eq_1877 *) ((char *) edi_123 + 1);
					--ecx_33;
					if (ecx_33 == 0x00)
						return;
				}
				ebx_130 = ecx_33;
				ecx_144 = ecx_33 >> 0x02;
				if (ecx_144 != 0x00)
				{
l00405897:
					do
					{
						edi_123->u1 = 0x00;
						edi_123 = (union Eq_1877 *) ((char *) edi_123 + 4);
						--ecx_144;
					} while (ecx_144 != 0x00);
l004058A1:
					al_191 = 0x00;
					ebx_130 &= 0x03;
					if (ebx_130 == 0x00)
						return;
				}
				do
				{
					edi_123->u0 = al_191;
					edi_123 = (union Eq_1877 *) ((char *) edi_123 + 1);
l0040582E:
					--ebx_130;
				} while (ebx_130 != 0x00);
				return;
			}
		} while ((esi_189 & 0x03) != 0x00);
		ebx_130 = ecx_33;
		ecx_126 = ecx_33 >> 0x02;
		if (ecx_33 >> 0x02 == 0x00)
		{
l004057F0:
			ebx_130 &= 0x03;
			if (ebx_130 == 0x00)
				return;
l004057F5:
			do
			{
				al_191 = *esi_189;
				edi_123->u0 = al_191;
				++esi_189;
				edi_123 = (union Eq_1877 *) ((char *) edi_123 + 1);
				if (al_191 == 0x00)
					goto l0040582E;
				--ebx_130;
			} while (ebx_130 != 0x00);
			return;
		}
	}
	do
	{
		Eq_3195 edx_80;
		edx_80.u1 = *esi_189;
		Eq_3199 eax_76;
		eax_76.u0 = *esi_189;
		byte dl_86 = (byte) edx_80;
		byte dh_97 = SLICE(edx_80, byte, 8);
		esi_189 += 4;
		if (((~eax_76 ^ (word32) eax_76 + 0x7EFEFEFF) & 0x81010100) != 0x00)
		{
			if (dl_86 != 0x00)
			{
				if (dh_97 != 0x00)
				{
					if ((edx_80 & 0x00FF0000) != 0x00)
					{
						if ((edx_80 & 0xFF000000) != 0x00)
							goto l00405839;
						edi_123->u1 = (word32) edx_80;
					}
					else
						edi_123->u1 = (word32) (edx_80 & 0xFFFF);
				}
				else
					edi_123->u1 = (word32) (edx_80 & 0xFF);
			}
			else
				edi_123->u1 = 0x00;
			edi_123 = (union Eq_1877 *) ((char *) edi_123 + 4);
			ecx_144 = ecx_126 - 0x01;
			if (ecx_144 != 0x00)
				goto l00405897;
			goto l004058A1;
		}
l00405839:
		edi_123->u1 = (word32) edx_80;
		edi_123 = (union Eq_1877 *) ((char *) edi_123 + 4);
		--ecx_126;
	} while (ecx_126 != 0x00);
	goto l004057F0;
}

// 00405DE0: Register word32 fn00405DE0(Stack Eq_421 dwArg04)
// Called from:
//      fn00404F20
word32 fn00405DE0(Eq_421 dwArg04)
{
	<anonymous> * ecx_5 = g_ptr40BE3C;
	if (ecx_5 == null)
		return 0x00;
	ecx_5();
	word32 eax_15;
	if (eax_15 == 0x00)
		return 0x00;
	return 0x01;
}

// tmpg83xd8u2.globals.c
// Generated by decompiling tmpg83xd8u2
// using Reko decompiler version 0.11.6.0.

#include "tmpg83xd8u2.h"

Eq_1281 g_t0001;
Eq_1281 g_t00FF;
// tmpg83xd8u2_data.c
// Generated by decompiling tmpg83xd8u2
// using Reko decompiler version 0.11.6.0.

#include "tmpg83xd8u2.h"

word32 g_dw408000 = 0x00; // 00408000
word32 g_dw408004 = 0x00; // 00408004
word32 g_dw408008 = 0x00; // 00408008
word32 g_dw408010 = 0x00; // 00408010
word32 g_dw408014 = 0x00; // 00408014
word32 g_dw40801C = 0x00; // 0040801C
word32 g_dw408020 = 0x00; // 00408020
word32 g_dw408024 = 0x00; // 00408024
Eq_10 g_t40A584 = // 0040A584
	{
		0x00
	};
uint8 g_b40A585 = 0x00; // 0040A585
ui32 g_dw40A588 = 0x00; // 0040A588
ui32 g_dw40A58C = 0x00; // 0040A58C
uint32 g_dw40A590 = 0x00; // 0040A590
word32 g_dw40A594 = 0x00; // 0040A594
Eq_9 g_t40A598 = // 0040A598
	{
		0x00
	};
Eq_9 g_t40A5A0 = // 0040A5A0
	{
		0x00
	};
ptr32 g_ptr40A5B0 = 0x00; // 0040A5B0
byte g_b40A5B8 = 0x00; // 0040A5B8
word32 g_dw40A5BC = 0x00; // 0040A5BC
word32 g_dw40A5C0 = 0x00; // 0040A5C0
Eq_9 g_t40A5D0 = // 0040A5D0
	{
		0x00
	};
<anonymous> * g_ptr40A5D8 = &g_t402490; // 0040A5D8
word32 g_dw40A5DC = 0x00; // 0040A5DC
word32 g_dw40A5E0 = 0x02; // 0040A5E0
uint16 g_a40A5FA[] = // 0040A5FA
	{
	};
word32 g_dw40A8B0 = 0x00; // 0040A8B0
Eq_1231 g_a40A8B8[] = // 0040A8B8
	{
	};
byte g_a40A8B9[] = // 0040A8B9
	{
	};
byte g_a40A8BA[255] = // 0040A8BA
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_80 g_t40A9BC = // 0040A9BC
	{
		0
	};
uip32 g_dw40A9C0 = 0x00; // 0040A9C0
uip32 g_dw40A9C8 = 0x00; // 0040A9C8
uip32 g_dw40A9CC = 0x00; // 0040A9CC
uip32 g_dw40A9D0 = 0x00; // 0040A9D0
word32 g_dw40A9D4 = 0x00; // 0040A9D4
byte g_a40A9D8[5] = // 0040A9D8
	{
		0x01,
		0x02,
		0x04,
		0x08,
		0x00,
	};
Eq_3438 g_a40A9E0[6] = // 0040A9E0
	{
		
		{
			
			{
				932
			},
		},
		
		{
			
			{
				936
			},
		},
		
		{
			
			{
				949
			},
		},
		
		{
			
			{
				950
			},
		},
		
		{
			
			{
				0x0551
			},
		},
		
		{
			
			{
				-1
			},
		},
	};
Eq_1195 g_t40AAD0 = // 0040AAD0
	{
		~0x00,
	};
Eq_3466 g_a40AAE0[19] = // 0040AAE0
	{
		
		{
			0x02,
			&g_str407738,
		},
		
		{
			0x08,
			&g_str40770C,
		},
		
		{
			0x09,
			&g_str4076E0,
		},
		
		{
			0x0A,
			&g_str4076BC,
		},
		
		{
			0x10,
			&g_str407690,
		},
		
		{
			0x11,
			&g_str407660,
		},
		
		{
			0x12,
			&g_str40763C,
		},
		
		{
			0x13,
			&g_str407610,
		},
		
		{
			0x18,
			&g_str4075D8,
		},
		
		{
			0x19,
			&g_str4075B0,
		},
		
		{
			0x1A,
			&g_str407578,
		},
		
		{
			0x1B,
			&g_str407540,
		},
		
		{
			0x1C,
			&g_str407518,
		},
		
		{
			0x78,
			&g_str407508,
		},
		
		{
			121,
			&g_str4074F8,
		},
		
		{
			122,
			&g_str4074E8,
		},
		
		{
			252,
			&g_str4074E4,
		},
		
		{
			0xFF,
			&g_str4074D4,
		},
		
		{
			0x00,
			null,
		},
	};
<anonymous> * g_ptr40AB70 = null; // 0040AB70
Eq_80 g_t40AE40 = // 0040AE40
	{
		0
	};
ptr32 g_ptr40AE48 = 0x0040AE48; // 0040AE48
Eq_9 g_t40AE4C = // 0040AE4C
	{
		0x48
	};
word32 g_dw40B658 = 0x00; // 0040B658
Eq_9 g_t40B65C = // 0040B65C
	{
		0x48
	};
word32 g_dw40B660 = 0x00; // 0040B660
Eq_1787 g_t40B664 = 0x01E0; // 0040B664
Eq_3078 g_t40B668 = null; // 0040B668
Eq_3078 g_t40B66C = null; // 0040B66C
Eq_3078 g_t40B670 = null; // 0040B670
word32 g_dw40B7F0 = 0x00; // 0040B7F0
Eq_3 g_t40BA10 = // 0040BA10
	{
		null
	};
byte g_b40BA18 = 0x00; // 0040BA18
<unknown> g_t40BD38 = // 0040BD38;
<anonymous> * g_ptr40BE3C = null; // 0040BE3C
Eq_107 g_t40CE54 = // 0040CE54
	{
		0x00
	};
Eq_9 g_t40CE60 = // 0040CE60
	{
		0x00
	};
struct Eq_1593 * g_a40CE64[] = // 0040CE64
	{
	};
Eq_80 g_t40CF60 = // 0040CF60
	{
		0
	};
Eq_9 g_t40CF64 = // 0040CF64
	{
		0x00
	};
up32 g_dw40CF68 = 0x00; // 0040CF68
word32 * g_ptr40CF6C = null; // 0040CF6C
<anonymous> * g_ptr40CF70 = null; // 0040CF70
// tmpg83xd8u2_idata.c
// Generated by decompiling tmpg83xd8u2
// using Reko decompiler version 0.11.6.0.

#include "tmpg83xd8u2.h"

word32 g_dw40D0B4 = 54724; // 0040D0B4
word32 g_dw40D0B8 = 0xD5B2; // 0040D0B8
word32 g_dw40D0BC = 0xD5A4; // 0040D0BC
word32 g_dw40D0C4 = 0xD6B0; // 0040D0C4
word32 g_dw40D0CC = 54652; // 0040D0CC
word32 g_dw40D0D4 = 0xD420; // 0040D0D4
word32 g_dw40D0D8 = 0xD40A; // 0040D0D8
word32 g_dw40D0DC = 54258; // 0040D0DC
word32 g_dw40D0E0 = 0xD3DE; // 0040D0E0
word32 g_dw40D0E4 = 55602; // 0040D0E4
word32 g_dw40D0E8 = 55552; // 0040D0E8
word32 g_dw40D0EC = 55536; // 0040D0EC
word32 g_dw40D0F0 = 55520; // 0040D0F0
word32 g_dw40D0F4 = 55502; // 0040D0F4
word32 g_dw40D0F8 = 55586; // 0040D0F8
word32 g_dw40D0FC = 55572; // 0040D0FC
word32 g_dw40D100 = 54204; // 0040D100
word32 g_dw40D104 = 55486; // 0040D104
word32 g_dw40D108 = 0xD3D2; // 0040D108
word32 g_dw40D10C = 0xD870; // 0040D10C
word32 g_dw40D110 = 0xD860; // 0040D110
word32 g_dw40D114 = 55380; // 0040D114
word32 g_dw40D118 = 55366; // 0040D118
word32 g_dw40D11C = 55352; // 0040D11C
word32 g_dw40D120 = 55338; // 0040D120
word32 g_dw40D124 = 55322; // 0040D124
word32 g_dw40D128 = 0xD80C; // 0040D128
word32 g_dw40D12C = 55132; // 0040D12C
word32 g_dw40D130 = 55474; // 0040D130
word32 g_dw40D134 = 0xD882; // 0040D134
word32 g_dw40D138 = 0xD7EE; // 0040D138
word32 g_dw40D13C = 55268; // 0040D13C
word32 g_dw40D140 = 55256; // 0040D140
word32 g_dw40D144 = 54184; // 0040D144
word32 g_dw40D148 = 54164; // 0040D148
word32 g_dw40D14C = 0xD388; // 0040D14C
word32 g_dw40D150 = 55462; // 0040D150
word32 g_dw40D154 = 55444; // 0040D154
word32 g_dw40D158 = 55290; // 0040D158
word32 g_dw40D15C = 55158; // 0040D15C
word32 g_dw40D160 = 0xD740; // 0040D160
word32 g_dw40D164 = 54140; // 0040D164
word32 g_dw40D168 = 55078; // 0040D168
word32 g_dw40D16C = 55060; // 0040D16C
word32 g_dw40D170 = 55234; // 0040D170
word32 g_dw40D174 = 55208; // 0040D174
word32 g_dw40D178 = 55182; // 0040D178
word32 g_dw40D17C = 55092; // 0040D17C
word32 g_dw40D180 = 55022; // 0040D180
word32 g_dw40D184 = 0xD6CC; // 0040D184
word32 g_dw40D188 = 55002; // 0040D188
word32 g_dw40D18C = 0xD702; // 0040D18C
word32 g_dw40D194 = 0xD650; // 0040D194
word32 g_dw40D198 = 0xD620; // 0040D198
word32 g_dw40D19C = 54756; // 0040D19C
word32 g_dw40D1A0 = 0xD60A; // 0040D1A0
word32 g_dw40D1A4 = 54770; // 0040D1A4
word32 g_dw40D1A8 = 54834; // 0040D1A8
word32 g_dw40D1B0 = 0xD504; // 0040D1B0
word32 g_dw40D1B4 = 54544; // 0040D1B4
word32 g_dw40D1B8 = 0xD444; // 0040D1B8
word32 g_dw40D1BC = 0xD454; // 0040D1BC
word32 g_dw40D1C0 = 0xD462; // 0040D1C0
word32 g_dw40D1C4 = 0xD470; // 0040D1C4
word32 g_dw40D1C8 = 54402; // 0040D1C8
word32 g_dw40D1CC = 0xD564; // 0040D1CC
word32 g_dw40D1D0 = 0xD552; // 0040D1D0
word32 g_dw40D1D4 = 54588; // 0040D1D4
word32 g_dw40D1D8 = 0xD530; // 0040D1D8
word32 g_dw40D1DC = 54558; // 0040D1DC
word32 g_dw40D1E0 = 0xD490; // 0040D1E0
word32 g_dw40D1E4 = 54520; // 0040D1E4
word32 g_dw40D1E8 = 54506; // 0040D1E8
word32 g_dw40D1EC = 54488; // 0040D1EC
word32 g_dw40D1F0 = 54472; // 0040D1F0
word32 g_dw40D1F4 = 54456; // 0040D1F4
word32 g_dw40D1F8 = 54442; // 0040D1F8
word32 g_dw40D1FC = 54428; // 0040D1FC
word32 g_dw40D208 = 0xD670; // 0040D208
word32 g_dw40D20C = 54914; // 0040D20C
word32 g_dw40D210 = 0xD692; // 0040D210
<anonymous> * __imp__RegCreateKeyExA = &g_tD5C4; // 0040D218
<anonymous> * __imp__RegSetValueExA = &g_tD5B2; // 0040D21C
<anonymous> * __imp__RegCloseKey = &g_tD5A4; // 0040D220
<anonymous> * __imp__DirectXSetupA = &g_tD6B0; // 0040D228
<anonymous> * __imp__DeleteObject = &g_tD57C; // 0040D230
<anonymous> * __imp__MultiByteToWideChar = &g_tD420; // 0040D238
<anonymous> * __imp__GetModuleFileNameA = &g_tD40A; // 0040D23C
<anonymous> * __imp__GetWindowsDirectoryA = &g_tD3F2; // 0040D240
<anonymous> * __imp__GetDiskFreeSpaceA = &g_tD3DE; // 0040D244
<anonymous> * __imp__LCMapStringW = &g_tD932; // 0040D248
<anonymous> * __imp__FlushFileBuffers = &g_tD900; // 0040D24C
<anonymous> * __imp__SetStdHandle = &g_tD8F0; // 0040D250
<anonymous> * __imp__LoadLibraryA = &g_tD8E0; // 0040D254
<anonymous> * __imp__GetProcAddress = &g_tD8CE; // 0040D258
<anonymous> * __imp__LCMapStringA = &g_tD922; // 0040D25C
<anonymous> * __imp__CloseHandle = &g_tD914; // 0040D260
<anonymous> * __imp__SetFileAttributesA = &g_tD3BC; // 0040D264
<anonymous> * __imp__VirtualAlloc = &g_tD8BE; // 0040D268
<anonymous> * __imp__lstrcpyA = &g_tD3D2; // 0040D26C
<anonymous> * __imp__SetFilePointer = &g_tD870; // 0040D270
<anonymous> * __imp__GetLastError = &g_tD860; // 0040D274
<anonymous> * __imp__WriteFile = &g_tD854; // 0040D278
<anonymous> * __imp__VirtualFree = &g_tD846; // 0040D27C
<anonymous> * __imp__HeapCreate = &g_tD838; // 0040D280
<anonymous> * __imp__HeapDestroy = &g_tD82A; // 0040D284
<anonymous> * __imp__GetStdHandle = &g_tD81A; // 0040D288
<anonymous> * __imp__GetFileType = &g_tD80C; // 0040D28C
<anonymous> * __imp__FreeEnvironmentStringsA = &g_tD75C; // 0040D290
<anonymous> * __imp__HeapAlloc = &g_tD8B2; // 0040D294
<anonymous> * __imp__GetStringTypeA = &g_tD882; // 0040D298
<anonymous> * __imp__GetOEMCP = &g_tD7EE; // 0040D29C
<anonymous> * __imp__GetACP = &g_tD7E4; // 0040D2A0
<anonymous> * __imp__GetCPInfo = &g_tD7D8; // 0040D2A4
<anonymous> * __imp__CreateDirectoryA = &g_tD3A8; // 0040D2A8
<anonymous> * __imp__GetModuleHandleA = &g_tD394; // 0040D2AC
<anonymous> * __imp__lstrlenA = &g_tD388; // 0040D2B0
<anonymous> * __imp__HeapFree = &g_tD8A6; // 0040D2B4
<anonymous> * __imp__GetStringTypeW = &g_tD894; // 0040D2B8
<anonymous> * __imp__SetHandleCount = &g_tD7FA; // 0040D2BC
<anonymous> * __imp__GetEnvironmentStrings = &g_tD776; // 0040D2C0
<anonymous> * __imp__UnhandledExceptionFilter = &g_tD740; // 0040D2C4
<anonymous> * __imp__lstrcatA = &g_tD37C; // 0040D2C8
<anonymous> * __imp__GetVersion = &g_tD726; // 0040D2CC
<anonymous> * __imp__GetCommandLineA = &g_tD714; // 0040D2D0
<anonymous> * __imp__WideCharToMultiByte = &g_tD7C2; // 0040D2D4
<anonymous> * __imp__GetEnvironmentStringsW = &g_tD7A8; // 0040D2D8
<anonymous> * __imp__FreeEnvironmentStringsW = &g_tD78E; // 0040D2DC
<anonymous> * __imp__RtlUnwind = &g_tD734; // 0040D2E0
<anonymous> * __imp__GetCurrentProcess = &g_tD6EE; // 0040D2E4
<anonymous> * __imp__ExitProcess = &g_tD6CC; // 0040D2E8
<anonymous> * __imp__TerminateProcess = &g_tD6DA; // 0040D2EC
<anonymous> * __imp__GetStartupInfoA = &g_tD702; // 0040D2F0
<anonymous> * __imp__SHFileOperationA = &g_tD650; // 0040D2F8
<anonymous> * __imp__SHChangeNotify = &g_tD620; // 0040D2FC
<anonymous> * __imp__SHGetMalloc = &g_tD5E4; // 0040D300
<anonymous> * __imp__SHBrowseForFolderA = &g_tD60A; // 0040D304
<anonymous> * __imp__SHGetPathFromIDListA = &g_tD5F2; // 0040D308
<anonymous> * __imp__SHGetSpecialFolderLocation = &g_tD632; // 0040D30C
<anonymous> * __imp__SetCursor = &g_tD504; // 0040D314
<anonymous> * __imp__LoadCursorA = &g_tD510; // 0040D318
<anonymous> * __imp__SendMessageA = &g_tD444; // 0040D31C
<anonymous> * __imp__LoadImageA = &g_tD454; // 0040D320
<anonymous> * __imp__GetDlgItem = &g_tD462; // 0040D324
<anonymous> * __imp__SetDlgItemTextA = &g_tD470; // 0040D328
<anonymous> * __imp__wvsprintfA = &g_tD482; // 0040D32C
<anonymous> * __imp__CharNextA = &g_tD564; // 0040D330
<anonymous> * __imp__DialogBoxParamA = &g_tD552; // 0040D334
<anonymous> * __imp__SendDlgItemMessageA = &g_tD53C; // 0040D338
<anonymous> * __imp__SetFocus = &g_tD530; // 0040D33C
<anonymous> * __imp__GetWindowTextA = &g_tD51E; // 0040D340
<anonymous> * __imp__EndDialog = &g_tD490; // 0040D344
<anonymous> * __imp__wsprintfA = &g_tD4F8; // 0040D348
<anonymous> * __imp__ShowWindow = &g_tD4EA; // 0040D34C
<anonymous> * __imp__SetWindowTextA = &g_tD4D8; // 0040D350
<anonymous> * __imp__EnableWindow = &g_tD4C8; // 0040D354
<anonymous> * __imp__ExitWindowsEx = &g_tD4B8; // 0040D358
<anonymous> * __imp__LoadStringA = &g_tD4AA; // 0040D35C
<anonymous> * __imp__MessageBoxA = &g_tD49C; // 0040D360
<anonymous> * __imp__CoUninitialize = &g_tD670; // 0040D36C
<anonymous> * __imp__CoInitialize = &g_tD682; // 0040D370
<anonymous> * __imp__CoCreateInstance = &g_tD692; // 0040D374
// tmpg83xd8u2_rdata.c
// Generated by decompiling tmpg83xd8u2
// using Reko decompiler version 0.11.6.0.

#include "tmpg83xd8u2.h"

char g_str4074D4[] = "runtime error "; // 004074D4
char g_str4074E4[] = "\r\n"; // 004074E4
char g_str4074E8[] = "TLOSS error\r\n"; // 004074E8
char g_str4074F8[] = "SING error\r\n"; // 004074F8
char g_str407508[] = "DOMAIN error\r\n"; // 00407508
char g_str407518[] = "R6028\r\n- unable to initialize heap\r\n"; // 00407518
char g_str407540[] = "R6027\r\n- not enough space for lowio initialization\r\n"; // 00407540
char g_str407578[] = "R6026\r\n- not enough space for stdio initialization\r\n"; // 00407578
char g_str4075B0[] = "R6025\r\n- pure virtual function call\r\n"; // 004075B0
char g_str4075D8[] = "R6024\r\n- not enough space for _onexit/atexit table\r\n"; // 004075D8
char g_str407610[] = "R6019\r\n- unable to open console device\r\n"; // 00407610
char g_str40763C[] = "R6018\r\n- unexpected heap error\r\n"; // 0040763C
char g_str407660[] = "R6017\r\n- unexpected multithread lock error\r\n"; // 00407660
char g_str407690[] = "R6016\r\n- not enough space for thread data\r\n"; // 00407690
char g_str4076BC[] = "\r\nabnormal program termination\r\n"; // 004076BC
char g_str4076E0[] = "R6009\r\n- not enough space for environment\r\n"; // 004076E0
char g_str40770C[] = "R6008\r\n- not enough space for arguments\r\n"; // 0040770C
char g_str407738[] = "R6002\r\n- floating point not loaded\r\n"; // 00407738
char g_str407788[] = "\n\n"; // 00407788
Eq_1898 g_t40778C = // 0040778C;
byte g_b4077A8 = 0x2E; // 004077A8
Eq_1889 g_t4077AC = // 004077AC;
