using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Win32Emu.Generators;

/// <summary>
/// Source generator that generates ref struct wrappers for memory-mapped structures.
/// Annotate a struct with [GenerateMemoryRef] to generate a corresponding ref struct
/// that provides direct memory read/write access via properties.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MemoryRefStructGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Find structs with [GenerateMemoryRef] attribute
		var structDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is StructDeclarationSyntax { AttributeLists.Count: > 0 },
				transform: static (ctx, _) => GetStructToGenerate(ctx))
			.Where(static m => m is not null);

		// Generate ref structs
		context.RegisterSourceOutput(structDeclarations, static (spc, structInfo) => Execute(structInfo!, spc));
	}

	private static StructInfo? GetStructToGenerate(GeneratorSyntaxContext context)
	{
		var structDecl = (StructDeclarationSyntax)context.Node;
		var symbol = context.SemanticModel.GetDeclaredSymbol(structDecl) as INamedTypeSymbol;

		if (symbol is null)
			return null;

		// Check for [GenerateMemoryRef] attribute
		var hasAttribute = symbol.GetAttributes()
			.Any(attr => attr.AttributeClass?.Name is "GenerateMemoryRefAttribute" or "GenerateMemoryRef");

		if (!hasAttribute)
			return null;

		// Extract field information
		var fields = symbol.GetMembers()
			.OfType<IFieldSymbol>()
			.Where(f => !f.IsStatic && !f.IsConst)
			.Select((f, index) => new FieldInfo(
				f.Name,
				f.Type.ToDisplayString(),
				GetFieldOffset(f, index)))
			.ToImmutableArray();

		// Get the full type name including containing types
		var fullTypeName = GetFullTypeName(symbol);

		return new StructInfo(
			symbol.ContainingNamespace.ToDisplayString(),
			symbol.Name,
			fullTypeName,
			fields);
	}

	private static string GetFullTypeName(INamedTypeSymbol symbol)
	{
		var parts = new List<string>();
		var current = symbol;
		
		while (current is not null)
		{
			parts.Add(current.Name);
			current = current.ContainingType;
		}
		
		parts.Reverse();
		return string.Join(".", parts);
	}

	private static int GetFieldOffset(IFieldSymbol field, int index)
	{
		// Look for [FieldOffset] attribute
		var offsetAttr = field.GetAttributes()
			.FirstOrDefault(attr => attr.AttributeClass?.Name == "FieldOffsetAttribute");

		if (offsetAttr is not null && offsetAttr.ConstructorArguments.Length > 0)
		{
			var value = offsetAttr.ConstructorArguments[0].Value;
			if (value is int offset)
				return offset;
		}

		// Defaulting to sequential layout is error-prone.
		// Throw an exception to enforce explicit [FieldOffset] attributes.
		throw new InvalidOperationException(
			$"Field '{field.Name}' in struct '{field.ContainingType.Name}' must have an explicit [FieldOffset] attribute. Automatic layout is not supported.");
	}

	private static void Execute(StructInfo structInfo, SourceProductionContext context)
	{
		var sb = new StringBuilder();
		
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("using Win32Emu.Memory;");
		sb.AppendLine();
		sb.AppendLine($"namespace {structInfo.Namespace}");
		sb.AppendLine("{");
		sb.AppendLine($"\t/// <summary>");
		sb.AppendLine($"\t/// Ref struct wrapper for {structInfo.Name} that provides direct memory access via properties.");
		sb.AppendLine($"\t/// Properties automatically read from and write to the underlying memory address.");
		sb.AppendLine($"\t/// </summary>");
		sb.AppendLine($"\tpublic readonly ref struct {structInfo.Name}Ref");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tprivate readonly VirtualMemory _memory;");
		sb.AppendLine("\t\tprivate readonly uint _address;");
		sb.AppendLine();
		sb.AppendLine($"\t\tpublic {structInfo.Name}Ref(VirtualMemory memory, uint address)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\t_memory = memory;");
		sb.AppendLine("\t\t\t_address = address;");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic uint Address => _address;");
		sb.AppendLine();

		// Generate properties for each field
		foreach (var field in structInfo.Fields)
		{
			GenerateProperty(sb, field);
		}

		// Generate ToStruct method
		sb.AppendLine("\t\t/// <summary>");
		sb.AppendLine("\t\t/// Converts this ref struct to a value struct snapshot.");
		sb.AppendLine("\t\t/// </summary>");
		sb.AppendLine($"\t\tpublic {structInfo.FullTypeName} ToStruct()");
		sb.AppendLine("\t\t{");
		sb.AppendLine($"\t\t\treturn new {structInfo.FullTypeName}");
		sb.AppendLine("\t\t\t{");
		foreach (var field in structInfo.Fields)
		{
			sb.AppendLine($"\t\t\t\t{field.Name} = {field.Name},");
		}
		sb.AppendLine("\t\t\t};");
		sb.AppendLine("\t\t}");
		sb.AppendLine();

		// Generate implicit conversion operator
		sb.AppendLine("\t\t/// <summary>");
		sb.AppendLine("\t\t/// Implicit conversion to the underlying value struct.");
		sb.AppendLine("\t\t/// </summary>");
		sb.AppendLine($"\t\tpublic static implicit operator {structInfo.FullTypeName}({structInfo.Name}Ref refStruct) => refStruct.ToStruct();");

		sb.AppendLine("\t}");
		sb.AppendLine("}");

		context.AddSource($"{structInfo.Name}Ref.g.cs", sb.ToString());
	}

	private static void GenerateProperty(StringBuilder sb, FieldInfo field)
	{
		var readMethod = GetReadMethod(field.Type);
		var writeMethod = GetWriteMethod(field.Type);

		sb.AppendLine($"\t\tpublic {field.Type} {field.Name}");
		sb.AppendLine("\t\t{");
		sb.AppendLine($"\t\t\tget => ({field.Type})_memory.{readMethod}(_address + {field.Offset});");
		sb.AppendLine($"\t\t\tset => _memory.{writeMethod}(_address + {field.Offset}, ({GetWriteType(field.Type)})value);");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
	}

	private static string GetReadMethod(string typeName)
	{
		return typeName switch
		{
			"byte" => "Read8",
			"ushort" or "short" => "Read16",
			"uint" or "int" => "Read32",
			"ulong" or "long" => "Read64",
			_ when typeName.Contains("uint") => "Read32",
			_ when typeName.Contains("int") => "Read32",
			_ => "Read32" // Default to 32-bit
		};
	}

	private static string GetWriteMethod(string typeName)
	{
		return typeName switch
		{
			"byte" => "Write8",
			"ushort" or "short" => "Write16",
			"uint" or "int" => "Write32",
			"ulong" or "long" => "Write64",
			_ when typeName.Contains("uint") => "Write32",
			_ when typeName.Contains("int") => "Write32",
			_ => "Write32" // Default to 32-bit
		};
	}

	private static string GetWriteType(string typeName)
	{
		return typeName switch
		{
			"byte" => "byte",
			"ushort" => "ushort",
			"short" => "ushort",      // Cast signed to unsigned for write
			"uint" => "uint",
			"int" => "uint",          // Cast signed to unsigned for write
			"ulong" => "ulong",
			"long" => "ulong",        // Cast signed to unsigned for write
			_ => "uint" // Default cast
		};
	}

	private class StructInfo
	{
		public string Namespace { get; }
		public string Name { get; }
		public string FullTypeName { get; }
		public ImmutableArray<FieldInfo> Fields { get; }

		public StructInfo(string nameSpace, string name, string fullTypeName, ImmutableArray<FieldInfo> fields)
		{
			Namespace = nameSpace;
			Name = name;
			FullTypeName = fullTypeName;
			Fields = fields;
		}
	}

	private class FieldInfo
	{
		public string Name { get; }
		public string Type { get; }
		public int Offset { get; }

		public FieldInfo(string name, string type, int offset)
		{
			Name = name;
			Type = type;
			Offset = offset;
		}
	}
}
