using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Win32Emu.Generators;

/// <summary>
/// Source generator that discovers all Win32 module DLL names by scanning for types
/// implementing IWin32ModuleUnsafe interface and extracts their Name property values.
/// Generates a static class containing a collection of system DLL names.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SystemDllsGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Find classes that implement IWin32ModuleUnsafe or IWin32ModuleAsync
		var moduleClasses = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (node, _) => node is ClassDeclarationSyntax cls && cls.BaseList != null,
				static (ctx, _) => GetModuleInfo(ctx))
			.Where(static m => m is not null);

		// Collect all module names
		var dllNames = moduleClasses.Collect()
			.Select(static (modules, _) => modules.Select(m => m!.DllName).Distinct().OrderBy(name => name).ToImmutableArray());

		// Generate the static class with system DLL names
		context.RegisterSourceOutput(dllNames, static (spc, names) => GenerateSystemDllsClass(spc, names));
	}

	private static ModuleInfo? GetModuleInfo(GeneratorSyntaxContext context)
	{
		var classDecl = (ClassDeclarationSyntax)context.Node;
		var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

		if (classSymbol is null)
			return null;

		// Check if class implements IWin32ModuleUnsafe or IWin32ModuleAsync
		var implementsInterface = classSymbol.AllInterfaces.Any(i =>
			i.Name is "IWin32ModuleUnsafe" or "IWin32ModuleAsync");

		if (!implementsInterface)
			return null;

		// Extract the Name property value
		var dllName = GetModuleDllName(classSymbol);
		if (string.IsNullOrEmpty(dllName))
			return null;

		return new ModuleInfo(classSymbol.Name, dllName!);
	}

	private static string? GetModuleDllName(INamedTypeSymbol typeSymbol)
	{
		// Try to get the Name property value
		var nameProperty = typeSymbol.GetMembers("Name")
			.OfType<IPropertySymbol>()
			.FirstOrDefault();

		if (nameProperty?.GetMethod != null)
		{
			var syntaxRef = nameProperty.GetMethod.DeclaringSyntaxReferences.FirstOrDefault();
			if (syntaxRef != null)
			{
				var syntax = syntaxRef.GetSyntax();
				var syntaxText = syntax.ToString();
				
				// Look for => "DLL_NAME"
				var arrowIndex = syntaxText.IndexOf("=>", StringComparison.Ordinal);
				if (arrowIndex >= 0)
				{
					var firstQuote = syntaxText.IndexOf('"', arrowIndex);
					if (firstQuote >= 0)
					{
						var secondQuote = syntaxText.IndexOf('"', firstQuote + 1);
						if (secondQuote > firstQuote)
						{
							return syntaxText.Substring(firstQuote + 1, secondQuote - firstQuote - 1);
						}
					}
				}
			}
		}

		// Fallback: derive from class name (e.g., Kernel32Module -> KERNEL32.DLL)
		var className = typeSymbol.Name;
		if (className.EndsWith("Module", StringComparison.OrdinalIgnoreCase))
		{
			var baseName = className.Substring(0, className.Length - 6);
			return baseName.ToUpperInvariant() + ".DLL";
		}

		return null;
	}

	private static void GenerateSystemDllsClass(SourceProductionContext context, ImmutableArray<string> dllNames)
	{
		var source = new StringBuilder();
		source.AppendLine("// <auto-generated/>");
		source.AppendLine("#nullable enable");
		source.AppendLine();
		source.AppendLine("using System.Collections.Frozen;");
		source.AppendLine();
		source.AppendLine("namespace Win32Emu.Win32.Modules;");
		source.AppendLine();
		source.AppendLine("/// <summary>");
		source.AppendLine("/// Auto-generated list of system DLL names discovered from IWin32ModuleUnsafe implementations.");
		source.AppendLine($"/// Found {dllNames.Length} DLL modules.");
		source.AppendLine("/// </summary>");
		source.AppendLine("internal static class KnownSystemDlls");
		source.AppendLine("{");
		source.AppendLine("\t/// <summary>");
		source.AppendLine("\t/// A frozen set of known system DLL names, automatically generated at compile time.");
		source.AppendLine("\t/// </summary>");
		
		if (dllNames.IsEmpty)
		{
			// Generate an empty set as fallback
			source.AppendLine("\tpublic static readonly FrozenSet<string> DllNames = FrozenSet<string>.Empty;");
		}
		else
		{
			source.AppendLine("\tpublic static readonly FrozenSet<string> DllNames = FrozenSet.ToFrozenSet(");
			source.AppendLine("\t[");

			foreach (var dllName in dllNames)
			{
				source.AppendLine($"\t\t\"{dllName}\",");
			}

			source.AppendLine("\t], System.StringComparer.OrdinalIgnoreCase);");
		}
		
		source.AppendLine("}");

		context.AddSource("KnownSystemDlls.g.cs", source.ToString());
	}

	private sealed class ModuleInfo
	{
		public ModuleInfo(string className, string dllName)
		{
			ClassName = className;
			DllName = dllName;
		}

		public string ClassName { get; }
		public string DllName { get; }
	}
}
