/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
DWORD sub_401130();
HWND __cdecl sub_401200(int nCmdShow);
LRESULT __stdcall sub_4012D0(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
int sub_401310();
LPVOID sub_401420();
int __thiscall sub_4014A0(int *this);
int __thiscall sub_4014D0(_DWORD *this, HINSTANCE hInst, int a3, int xSrc, int ySrc, int wSrc, int cy);
int __thiscall sub_401640(_DWORD *this, int *a2, int a3, int a4, int a5);
int __thiscall sub_401730(int this, int *a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __thiscall sub_4017D0(int *this);
int __thiscall sub_4017F0(_DWORD **this);
// HRESULT __stdcall DirectDrawCreateEx(GUID *lpGuid, LPVOID *lplpDD, const IID *const iid, IUnknown *pUnkOuter);
void __cdecl sub_4018B4(LPVOID lpMem);
void *__cdecl sub_4019FE(LPVOID lpMem, _DWORD *dwBytes);
int __cdecl sub_401DA0(_DWORD *lpMem);
// void *__cdecl malloc(size_t Size);
LPVOID __cdecl sub_401E3F(unsigned int a1);
void __cdecl sub_401EB3(LPVOID lpMem);
char __cdecl sub_4026DB(int a1);
int sub_402708();
int __cdecl sub_402850(int a1);
// _DWORD __cdecl __sbh_heap_init(_DWORD); weak
// _DWORD __cdecl __sbh_find_block(_DWORD); weak
_DWORD *__cdecl sub_402C7F(_DWORD *a1, int a2);
// _DWORD __cdecl __sbh_alloc_block(_DWORD); weak
// _DWORD __cdecl __sbh_resize_block(_DWORD, _DWORD, _DWORD); weak
int *sub_403753();
_UNKNOWN **__cdecl sub_403897(LPVOID *lpMem);
void __cdecl sub_4038ED(int a1);
unsigned int __cdecl sub_4039AF(unsigned int a1, _DWORD *a2, unsigned int *a3);
void __cdecl sub_403A06(int a1, int a2, _BYTE *a3);
int __cdecl sub_403A4B(unsigned int a1);
int __cdecl sub_403C53(int a1, unsigned int a2, unsigned int a3);
int __cdecl sub_403D77(int a1, _DWORD *a2, _BYTE *a3, unsigned int a4);
// int __cdecl _callnewh(size_t Size);
// void *__cdecl memcpy(void *, const void *Src, size_t Size);
// int __cdecl strtol(const char *String, char **EndPtr, int Radix);
// char *__cdecl strchr(const char *Str, int Val);
// char *__cdecl strstr(const char *Str, const char *SubStr);
// int __cdecl strncmp(const char *Str1, const char *Str2, size_t MaxCount);
// void *__cdecl memcpy_0(void *, const void *Src, size_t Size);
// void *__cdecl memset(void *, int Val, size_t Size);

//-------------------------------------------------------------------------
// Data declarations

// extern HGDIOBJ (__stdcall *SelectObject)(HDC hdc, HGDIOBJ h);
// extern HDC (__stdcall *CreateCompatibleDC)(HDC hdc);
// extern int (__stdcall *GetObjectA)(HANDLE h, int c, LPVOID pv);
// extern BOOL (__stdcall *StretchBlt)(HDC hdcDest, int xDest, int yDest, int wDest, int hDest, HDC hdcSrc, int xSrc, int ySrc, int wSrc, int hSrc, DWORD rop);
// extern BOOL (__stdcall *DeleteDC)(HDC hdc);
// extern HGDIOBJ (__stdcall *GetStockObject)(int i);
// extern void (__stdcall *OutputDebugStringA)(LPCSTR lpOutputString);
// extern LPVOID (__stdcall *HeapAlloc)(HANDLE hHeap, DWORD dwFlags, SIZE_T dwBytes);
// extern DWORD (__stdcall *GetModuleFileNameA)(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// extern LPVOID (__stdcall *VirtualAlloc)(LPVOID lpAddress, SIZE_T dwSize, DWORD flAllocationType, DWORD flProtect);
// extern HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName);
// extern LPVOID (__stdcall *HeapReAlloc)(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem, SIZE_T dwBytes);
// extern DWORD (__stdcall *GetTickCount)();
// extern SIZE_T (__stdcall *HeapSize)(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem);
// extern BOOL (__stdcall *HeapFree)(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem);
// extern HANDLE (__stdcall *HeapCreate)(DWORD flOptions, SIZE_T dwInitialSize, SIZE_T dwMaximumSize);
// extern BOOL (__stdcall *VirtualFree)(LPVOID lpAddress, SIZE_T dwSize, DWORD dwFreeType);
// extern DWORD (__stdcall *GetEnvironmentVariableA)(LPCSTR lpName, LPSTR lpBuffer, DWORD nSize);
// extern BOOL (__stdcall *GetVersionExA)(LPOSVERSIONINFOA lpVersionInformation);
// extern BOOL (__stdcall *HeapDestroy)(HANDLE hHeap);
// extern LRESULT (__stdcall *DispatchMessageA)(const MSG *lpMsg);
// extern BOOL (__stdcall *TranslateMessage)(const MSG *lpMsg);
// extern BOOL (__stdcall *PeekMessageA)(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg);
// extern int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// extern HWND (__stdcall *SetFocus)(HWND hWnd);
// extern BOOL (__stdcall *UpdateWindow)(HWND hWnd);
// extern BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow);
// extern HWND (__stdcall *CreateWindowExA)(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam);
// extern int (__stdcall *GetSystemMetrics)(int nIndex);
// extern HANDLE (__stdcall *LoadImageA)(HINSTANCE hInst, LPCSTR name, UINT type, int cx, int cy, UINT fuLoad);
// extern LRESULT (__stdcall *DefWindowProcA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern void (__stdcall *PostQuitMessage)(int nExitCode);
// extern HICON (__stdcall *LoadIconA)(HINSTANCE hInstance, LPCSTR lpIconName);
// extern HCURSOR (__stdcall *LoadCursorA)(HINSTANCE hInstance, LPCSTR lpCursorName);
// extern ATOM (__stdcall *RegisterClassA)(const WNDCLASSA *lpWndClass);
_UNKNOWN *off_406110 = &loc_401480; // weak
const IID iid = { 367419072u, 15260u, 4562u, { 185u, 47u, 0u, 96u, 151u, 151u, 234u, 91u } }; // idb
CHAR Text[] = "Could start DirectX engine in your computer. Make sure you have at least version 7 of DirectX installed."; // idb
CHAR Caption[] = "Error"; // idb
CHAR WindowName[] = "Basic DD"; // idb
CHAR OutputString[] = "Surface Destroyed\n"; // idb
_UNKNOWN *off_407208 = &off_407208; // weak
LPVOID off_40720C = &off_407208; // idb
int dword_407218 = -1; // weak
_UNKNOWN **off_409228 = &off_407208; // weak
int dword_40922C = 480; // weak
int dword_409548 = 0; // weak
int dword_409550[11] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }; // weak
HINSTANCE hInst = NULL; // idb
HWND hWnd = NULL; // idb
LPVOID lpDD = NULL; // idb
int dword_409588 = 0; // weak
int dword_40958C = 0; // weak
int dword_409590 = 0; // weak
int dword_409594 = 0; // weak
_UNKNOWN unk_409598; // weak
int dword_409704 = 0; // weak
int dword_40970C = 0; // idb
int dword_40996C = 0; // weak
int dword_409970 = 0; // weak
void *dword_409974 = NULL; // idb
int dword_409978 = 0; // weak
LPVOID lpMem = NULL; // idb
int dword_409980 = 0; // weak
HANDLE hHeap = NULL; // idb
int dword_409988 = 0; // weak


//----- (00401040) --------------------------------------------------------
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{
  struct tagMSG Msg; // [esp+0h] [ebp-1Ch] BYREF

  hInst = hInstance;
  hWnd = sub_401200(nShowCmd);
  if ( !hWnd )
    return -1;
  if ( sub_401310() >= 0 )
  {
    sub_401640(dword_409550, (int *)lpDD, 1500, 280, -1);
    sub_4014D0(dword_409550, hInst, 101, 0, 0, 1500, 280);
    while ( 1 )
    {
      while ( !PeekMessageA(&Msg, 0, 0, 0, 1u) )
        sub_401130();
      if ( Msg.message == 18 )
        break;
      TranslateMessage(&Msg);
      DispatchMessageA(&Msg);
    }
    sub_401420();
    return 0;
  }
  else
  {
    sub_401420();
    MessageBoxA(hWnd, Text, Caption, 0x30u);
    return 0;
  }
}
// 409550: using guessed type int dword_409550[11];

//----- (00401130) --------------------------------------------------------
DWORD sub_401130()
{
  DWORD result; // eax
  int v1; // eax

  result = GetTickCount() - dword_409548;
  if ( result >= 0x32 )
  {
    sub_401730((int)dword_409550, (int *)dword_40958C, 245, 170, dword_409590, dword_409594, 150, 140);
    do
    {
      v1 = (*(int (__stdcall **)(int, _DWORD, _DWORD))(*(_DWORD *)dword_409588 + 44))(dword_409588, 0, 0);
      if ( !v1 )
        break;
      if ( v1 == -2005532222 )
      {
        (*(void (__stdcall **)(int))(*(_DWORD *)dword_409588 + 108))(dword_409588);
        break;
      }
    }
    while ( v1 == -2005532132 );
    dword_409590 += 150;
    if ( dword_409590 >= 1500 )
    {
      dword_409590 = 0;
      dword_409594 += 140;
      if ( dword_409594 >= 280 )
        dword_409594 = 0;
    }
    result = GetTickCount();
    dword_409548 = result;
  }
  return result;
}
// 409548: using guessed type int dword_409548;
// 409550: using guessed type int dword_409550[11];
// 409588: using guessed type int dword_409588;
// 40958C: using guessed type int dword_40958C;
// 409590: using guessed type int dword_409590;
// 409594: using guessed type int dword_409594;

//----- (00401200) --------------------------------------------------------
HWND __cdecl sub_401200(int nCmdShow)
{
  int v1; // eax
  HWND Window; // esi
  int SystemMetrics; // [esp-14h] [ebp-40h]
  HINSTANCE v5; // [esp-8h] [ebp-34h]
  WNDCLASSA WndClass; // [esp+4h] [ebp-28h] BYREF

  WndClass.style = 3;
  WndClass.lpfnWndProc = sub_4012D0;
  WndClass.cbClsExtra = 0;
  WndClass.cbWndExtra = 0;
  WndClass.hInstance = hInst;
  WndClass.hIcon = LoadIconA(hInst, (LPCSTR)0x7F00);
  WndClass.hCursor = LoadCursorA(0, (LPCSTR)0x7F00);
  WndClass.hbrBackground = (HBRUSH)GetStockObject(4);
  WndClass.lpszMenuName = (LPCSTR)&unk_409598;
  WndClass.lpszClassName = WindowName;
  RegisterClassA(&WndClass);
  v5 = hInst;
  SystemMetrics = GetSystemMetrics(1);
  v1 = GetSystemMetrics(0);
  Window = CreateWindowExA(8u, WindowName, WindowName, 0x80000000, 0, 0, v1, SystemMetrics, 0, 0, v5, 0);
  ShowWindow(Window, nCmdShow);
  UpdateWindow(Window);
  SetFocus(Window);
  return Window;
}

//----- (004012D0) --------------------------------------------------------
LRESULT __stdcall sub_4012D0(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
  if ( Msg != 2 && (Msg != 256 || wParam != 27) )
    return DefWindowProcA(hWnd, Msg, wParam, lParam);
  PostQuitMessage(0);
  return 0;
}

//----- (00401310) --------------------------------------------------------
int sub_401310()
{
  _DWORD v1[4]; // [esp+34h] [ebp-8Ch] BYREF
  _DWORD v2[31]; // [esp+44h] [ebp-7Ch] BYREF

  if ( DirectDrawCreateEx(0, &lpDD, &iid, 0) )
    return -1;
  if ( (*(int (__stdcall **)(LPVOID, HWND, int))(*(_DWORD *)lpDD + 80))(lpDD, hWnd, 17) )
    return -2;
  if ( (*(int (__stdcall **)(LPVOID, int, int, int, _DWORD, _DWORD))(*(_DWORD *)lpDD + 84))(lpDD, 640, 480, 16, 0, 0) )
    return -3;
  memset(v2, 0, sizeof(v2));
  v2[0] = 124;
  v2[1] = 33;
  v2[26] = 536;
  v2[5] = 1;
  if ( (*(int (__stdcall **)(LPVOID, _DWORD *, int *, _DWORD))(*(_DWORD *)lpDD + 24))(lpDD, v2, &dword_409588, 0) )
    return -1;
  v1[0] = 4;
  memset(&v1[1], 0, 12);
  return -((*(int (__stdcall **)(int, _DWORD *, int *))(*(_DWORD *)dword_409588 + 48))(dword_409588, v1, &dword_40958C) != 0);
}
// 409588: using guessed type int dword_409588;
// 40958C: using guessed type int dword_40958C;

//----- (00401420) --------------------------------------------------------
LPVOID sub_401420()
{
  LPVOID result; // eax

  sub_4017D0(dword_409550);
  if ( dword_40958C )
    (*(void (__stdcall **)(int))(*(_DWORD *)dword_40958C + 8))(dword_40958C);
  if ( dword_409588 )
    (*(void (__stdcall **)(int))(*(_DWORD *)dword_409588 + 8))(dword_409588);
  result = lpDD;
  if ( lpDD )
    return (LPVOID)(*(int (__stdcall **)(LPVOID))(*(_DWORD *)lpDD + 8))(lpDD);
  return result;
}
// 409550: using guessed type int dword_409550[11];
// 409588: using guessed type int dword_409588;
// 40958C: using guessed type int dword_40958C;

//----- (004014A0) --------------------------------------------------------
int __thiscall sub_4014A0(int *this)
{
  int result; // eax

  result = *(this + 10);
  *this = (int)&off_406110;
  if ( result )
  {
    OutputDebugStringA(OutputString);
    result = (*(int (__stdcall **)(_DWORD))(*(_DWORD *)*(this + 10) + 8))(*(this + 10));
    *(this + 10) = 0;
  }
  return result;
}
// 406110: using guessed type _UNKNOWN *off_406110;

//----- (004014D0) --------------------------------------------------------
int __thiscall sub_4014D0(_DWORD *this, HINSTANCE hInst, int a3, int xSrc, int ySrc, int wSrc, int cy)
{
  int v7; // ebx
  HANDLE ImageA; // ebp
  int v10; // eax
  HDC CompatibleDC; // eax
  HDC v12; // edi
  int v13; // eax
  HDC hdcDest; // [esp+14h] [ebp-98h] BYREF
  _DWORD pv[6]; // [esp+18h] [ebp-94h] BYREF
  _DWORD v17[31]; // [esp+30h] [ebp-7Ch] BYREF

  v7 = wSrc;
  ImageA = LoadImageA(hInst, (LPCSTR)(unsigned __int16)a3, 0, wSrc, cy, 0);
  if ( !ImageA )
    return 0;
  v10 = *(this + 10);
  if ( !v10 )
    return 0;
  (*(void (__stdcall **)(_DWORD))(*(_DWORD *)v10 + 108))(*(this + 10));
  CompatibleDC = CreateCompatibleDC(0);
  v12 = CompatibleDC;
  if ( !CompatibleDC )
    return 0;
  SelectObject(CompatibleDC, ImageA);
  GetObjectA(ImageA, 24, pv);
  if ( !wSrc )
    v7 = pv[1];
  if ( !cy )
    cy = pv[2];
  v13 = *(this + 10);
  v17[0] = 124;
  v17[1] = 6;
  (*(void (__stdcall **)(int, _DWORD *))(*(_DWORD *)v13 + 88))(v13, v17);
  if ( !(*(int (__stdcall **)(_DWORD, HDC *))(*(_DWORD *)*(this + 10) + 68))(*(this + 10), &hdcDest) )
  {
    StretchBlt(hdcDest, 0, 0, v17[3], v17[2], v12, xSrc, ySrc, v7, cy, 0xCC0020u);
    (*(void (__stdcall **)(_DWORD, HDC))(*(_DWORD *)*(this + 10) + 104))(*(this + 10), hdcDest);
  }
  DeleteDC(v12);
  *(this + 1) = hInst;
  *(this + 2) = a3;
  *(this + 3) = xSrc;
  *(this + 4) = ySrc;
  *(this + 5) = v7;
  *(this + 6) = cy;
  return 1;
}

//----- (00401640) --------------------------------------------------------
int __thiscall sub_401640(_DWORD *this, int *a2, int a3, int a4, int a5)
{
  int v6; // ecx
  int v7; // eax
  int v8; // eax
  int v10; // edi
  _DWORD v11[2]; // [esp+10h] [ebp-84h] BYREF
  _DWORD v12[31]; // [esp+18h] [ebp-7Ch] BYREF

  memset(v12, 0, sizeof(v12));
  v6 = *a2;
  v12[0] = 124;
  v12[1] = 7;
  v12[26] = 16448;
  v12[3] = a3;
  v12[2] = a4;
  v7 = (*(int (__stdcall **)(int *, _DWORD *, _DWORD *, _DWORD))(v6 + 24))(a2, v12, this + 10, 0);
  if ( v7 )
  {
    if ( v7 == -2005532292 )
    {
      v8 = *a2;
      v12[26] = 2112;
      v7 = (*(int (__stdcall **)(int *, _DWORD *, _DWORD *, _DWORD))(v8 + 24))(a2, v12, this + 10, 0);
    }
    if ( v7 )
      return 0;
  }
  if ( a5 != -1 )
  {
    v10 = *(this + 10);
    v11[0] = a5;
    v11[1] = 0;
    (*(void (__stdcall **)(int, int, _DWORD *))(*(_DWORD *)v10 + 116))(v10, 8, v11);
  }
  *(this + 7) = a5;
  *(this + 9) = a3;
  *(this + 8) = a4;
  return 1;
}

//----- (00401730) --------------------------------------------------------
int __thiscall sub_401730(int this, int *a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v8; // esi
  int v10; // edx
  int v11; // eax
  int v12; // eax
  _DWORD v14[4]; // [esp+10h] [ebp-10h] BYREF

  v8 = a7;
  if ( !a7 )
    v8 = *(_DWORD *)(this + 36);
  v10 = a8;
  if ( !a8 )
    v10 = *(_DWORD *)(this + 32);
  v14[0] = a5;
  v14[1] = a6;
  v14[2] = v8 + a5;
  v14[3] = v10 + a6;
  while ( 1 )
  {
    v11 = *a2;
    v12 = *(int *)(this + 28) >= 0
        ? (*(int (__stdcall **)(int *, int, int, _DWORD, _DWORD *, int))(v11 + 28))(
            a2,
            a3,
            a4,
            *(_DWORD *)(this + 40),
            v14,
            1)
        : (*(int (__stdcall **)(int *, int, int, _DWORD, _DWORD *, _DWORD))(v11 + 28))(
            a2,
            a3,
            a4,
            *(_DWORD *)(this + 40),
            v14,
            0);
    if ( !v12 )
      break;
    if ( v12 == -2005532222 )
    {
      sub_4017F0((_DWORD **)this);
    }
    else if ( v12 != -2005532132 )
    {
      return 0;
    }
  }
  return 1;
}

//----- (004017D0) --------------------------------------------------------
int __thiscall sub_4017D0(int *this)
{
  int result; // eax

  result = *(this + 10);
  if ( result )
  {
    result = (*(int (__stdcall **)(int))(*(_DWORD *)result + 8))(result);
    *(this + 10) = 0;
  }
  return result;
}

//----- (004017F0) --------------------------------------------------------
int __thiscall sub_4017F0(_DWORD **this)
{
  return (*(int (__stdcall **)(_DWORD))(**(this + 10) + 108))(*(this + 10));
}

//----- (004018B4) --------------------------------------------------------
void __cdecl sub_4018B4(LPVOID lpMem)
{
  sub_401EB3(lpMem);
}

//----- (004019FE) --------------------------------------------------------
void *__cdecl sub_4019FE(LPVOID lpMem, _DWORD *dwBytes)
{
  void *result; // eax
  size_t v3; // esi
  void *v4; // edi
  _DWORD *block; // eax
  _DWORD *v6; // ebx
  size_t v7; // eax
  size_t v8; // eax
  _BYTE *v9; // eax
  _BYTE *v10; // ebx
  size_t v11; // eax
  size_t v12; // eax
  int v13; // [esp+Ch] [ebp-4h] BYREF

  if ( !lpMem )
    return malloc((size_t)dwBytes);
  v3 = (size_t)dwBytes;
  if ( !dwBytes )
  {
    sub_401EB3(lpMem);
    return 0;
  }
  if ( dword_409988 == 3 )
  {
    while ( 1 )
    {
      v4 = 0;
      if ( v3 <= 0xFFFFFFE0 )
        break;
LABEL_26:
      if ( !dword_40970C )
        return v4;
      if ( !_callnewh(v3) )
        return 0;
    }
    block = (_DWORD *)__sbh_find_block(lpMem);
    v6 = block;
    if ( !block )
    {
LABEL_22:
      if ( !v3 )
        v3 = 1;
      v3 = (v3 + 15) & 0xFFFFFFF0;
      v4 = HeapReAlloc(hHeap, 0, lpMem, v3);
LABEL_25:
      if ( v4 )
        return v4;
      goto LABEL_26;
    }
    if ( v3 > dword_409980 )
      goto LABEL_15;
    v4 = lpMem;
    if ( __sbh_resize_block(block, lpMem, v3) )
      goto LABEL_21;
    v4 = (void *)__sbh_alloc_block(v3);
    if ( v4 )
    {
      v7 = *((_DWORD *)lpMem - 1) - 1;
      if ( v7 >= v3 )
        v7 = v3;
      memcpy(v4, lpMem, v7);
      v6 = (_DWORD *)__sbh_find_block(lpMem);
      sub_402C7F(v6, (int)lpMem);
    }
    else
    {
LABEL_15:
      if ( !v3 )
        v3 = 1;
      v3 = (v3 + 15) & 0xFFFFFFF0;
      v4 = HeapAlloc(hHeap, 0, v3);
      if ( v4 )
      {
        v8 = *((_DWORD *)lpMem - 1) - 1;
        if ( v8 >= v3 )
          v8 = v3;
        memcpy(v4, lpMem, v8);
        sub_402C7F(v6, (int)lpMem);
      }
    }
LABEL_21:
    if ( v6 )
      goto LABEL_25;
    goto LABEL_22;
  }
  if ( dword_409988 != 2 )
  {
    do
    {
      result = 0;
      if ( v3 <= 0xFFFFFFE0 )
      {
        if ( !v3 )
          v3 = 1;
        v3 = (v3 + 15) & 0xFFFFFFF0;
        result = HeapReAlloc(hHeap, 0, lpMem, v3);
        if ( result )
          return result;
      }
      if ( !dword_40970C )
        return result;
    }
    while ( _callnewh(v3) );
    return 0;
  }
  if ( (unsigned int)dwBytes <= 0xFFFFFFE0 )
    v3 = ((unsigned int)dwBytes + 15) & 0xFFFFFFF0;
  while ( 1 )
  {
    v4 = 0;
    if ( v3 > 0xFFFFFFE0 )
      goto LABEL_49;
    v9 = (_BYTE *)sub_4039AF((unsigned int)lpMem, &v13, (unsigned int *)&dwBytes);
    v10 = v9;
    if ( !v9 )
    {
      v4 = HeapReAlloc(hHeap, 0, lpMem, v3);
      goto LABEL_48;
    }
    if ( v3 < dword_40922C )
    {
      if ( sub_403D77(v13, dwBytes, v9, v3 >> 4) )
        return lpMem;
      v4 = (void *)sub_403A4B(v3 >> 4);
      if ( v4 )
        break;
    }
    v4 = HeapAlloc(hHeap, 0, v3);
    if ( !v4 )
      goto LABEL_49;
    v12 = 16 * (unsigned __int8)*v10;
    if ( v12 >= v3 )
      v12 = v3;
    memcpy(v4, lpMem, v12);
    sub_403A06(v13, (int)dwBytes, v10);
LABEL_48:
    if ( v4 )
      return v4;
LABEL_49:
    if ( !dword_40970C )
      return v4;
    if ( !_callnewh(v3) )
      return 0;
  }
  v11 = 16 * (unsigned __int8)*v10;
  if ( v11 >= v3 )
    v11 = v3;
  memcpy(v4, lpMem, v11);
  sub_403A06(v13, (int)dwBytes, v10);
  return v4;
}
// 401B4E: conditional instruction was optimized away because %dwBytes.4 is in (1..FFFFFFE0)
// 401AAC: conditional instruction was optimized away because edi.4!=0
// 401BDD: conditional instruction was optimized away because edi.4!=0
// 402C54: using guessed type _DWORD __cdecl __sbh_find_block(_DWORD);
// 402FA8: using guessed type _DWORD __cdecl __sbh_alloc_block(_DWORD);
// 40345D: using guessed type _DWORD __cdecl __sbh_resize_block(_DWORD, _DWORD, _DWORD);
// 40922C: using guessed type int dword_40922C;
// 409980: using guessed type int dword_409980;
// 409988: using guessed type int dword_409988;

//----- (00401DA0) --------------------------------------------------------
int __cdecl sub_401DA0(_DWORD *lpMem)
{
  unsigned __int8 *v2; // eax
  int v3; // [esp+4h] [ebp-8h] BYREF
  unsigned int v4; // [esp+8h] [ebp-4h] BYREF

  if ( dword_409988 == 3 )
  {
    if ( __sbh_find_block(lpMem) )
      return *(lpMem - 1) - 9;
    else
      return HeapSize(hHeap, 0, lpMem);
  }
  else if ( dword_409988 == 2 && (v2 = (unsigned __int8 *)sub_4039AF((unsigned int)lpMem, &v3, &v4)) != 0 )
  {
    return 16 * *v2;
  }
  else
  {
    return HeapSize(hHeap, 0, lpMem);
  }
}
// 402C54: using guessed type _DWORD __cdecl __sbh_find_block(_DWORD);
// 409988: using guessed type int dword_409988;

//----- (00401E3F) --------------------------------------------------------
LPVOID __cdecl sub_401E3F(unsigned int a1)
{
  int v1; // esi
  LPVOID result; // eax
  SIZE_T v3; // esi

  v1 = a1;
  if ( dword_409988 == 3 )
  {
    if ( a1 <= dword_409980 )
    {
      result = (LPVOID)__sbh_alloc_block(a1);
      if ( result )
        return result;
    }
    goto LABEL_12;
  }
  if ( dword_409988 != 2 )
  {
LABEL_12:
    if ( !a1 )
      v1 = 1;
    v3 = (v1 + 15) & 0xFFFFFFF0;
    return HeapAlloc(hHeap, 0, v3);
  }
  if ( a1 )
    v3 = (a1 + 15) & 0xFFFFFFF0;
  else
    v3 = 16;
  if ( v3 > dword_40922C )
    return HeapAlloc(hHeap, 0, v3);
  result = (LPVOID)sub_403A4B(v3 >> 4);
  if ( !result )
    return HeapAlloc(hHeap, 0, v3);
  return result;
}
// 402FA8: using guessed type _DWORD __cdecl __sbh_alloc_block(_DWORD);
// 40922C: using guessed type int dword_40922C;
// 409980: using guessed type int dword_409980;
// 409988: using guessed type int dword_409988;

//----- (00401EB3) --------------------------------------------------------
void __cdecl sub_401EB3(LPVOID lpMem)
{
  LPVOID v1; // esi
  _DWORD *block; // eax
  _BYTE *v3; // eax
  void *v4; // [esp-4h] [ebp-Ch]
  int v5; // [esp+4h] [ebp-4h] BYREF

  v1 = lpMem;
  if ( lpMem )
  {
    if ( dword_409988 == 3 )
    {
      block = (_DWORD *)__sbh_find_block(lpMem);
      v4 = v1;
      if ( block )
      {
        sub_402C7F(block, (int)v1);
        return;
      }
    }
    else
    {
      if ( dword_409988 == 2 )
      {
        v3 = (_BYTE *)sub_4039AF((unsigned int)lpMem, &v5, (unsigned int *)&lpMem);
        if ( v3 )
        {
          sub_403A06(v5, (int)lpMem, v3);
          return;
        }
      }
      v4 = v1;
    }
    HeapFree(hHeap, 0, v4);
  }
}
// 402C54: using guessed type _DWORD __cdecl __sbh_find_block(_DWORD);
// 409988: using guessed type int dword_409988;

//----- (004026DB) --------------------------------------------------------
char __cdecl sub_4026DB(int a1)
{
  HMODULE ModuleHandleA; // eax
  int v2; // ecx

  *(_DWORD *)a1 = 0;
  ModuleHandleA = GetModuleHandleA(0);
  if ( *(_WORD *)ModuleHandleA == 23117 )
  {
    v2 = *((_DWORD *)ModuleHandleA + 15);
    if ( v2 )
    {
      ModuleHandleA = (HMODULE)((char *)ModuleHandleA + v2);
      *(_BYTE *)a1 = *((_BYTE *)ModuleHandleA + 26);
      LOBYTE(ModuleHandleA) = *((_BYTE *)ModuleHandleA + 27);
      *(_BYTE *)(a1 + 1) = (_BYTE)ModuleHandleA;
    }
  }
  return (char)ModuleHandleA;
}

//----- (00402708) --------------------------------------------------------
int sub_402708()
{
  int result; // eax
  CHAR *i; // ecx
  char v2; // al
  CHAR *v3; // eax
  CHAR *j; // ecx
  char v5; // al
  char *v6; // eax
  const char *v7; // eax
  const char *v8; // ecx
  CHAR Buffer[4240]; // [esp+4h] [ebp-122Ch] BYREF
  CHAR Filename[260]; // [esp+1094h] [ebp-19Ch] BYREF
  struct _OSVERSIONINFOA VersionInformation; // [esp+1198h] [ebp-98h] BYREF
  _BYTE v12[4]; // [esp+122Ch] [ebp-4h] BYREF

  VersionInformation.dwOSVersionInfoSize = 148;
  if ( GetVersionExA(&VersionInformation)
    && VersionInformation.dwPlatformId == 2
    && VersionInformation.dwMajorVersion >= 5 )
  {
    return 1;
  }
  if ( !GetEnvironmentVariableA("__MSVCRT_HEAP_SELECT", Buffer, 0x1090u) )
    goto LABEL_29;
  for ( i = Buffer; *i; ++i )
  {
    v2 = *i;
    if ( *i >= 97 && v2 <= 122 )
      *i = v2 - 32;
  }
  if ( !strncmp("__GLOBAL_HEAP_SELECTED", Buffer, 0x16u) )
  {
    v3 = Buffer;
  }
  else
  {
    GetModuleFileNameA(0, Filename, 0x104u);
    for ( j = Filename; *j; ++j )
    {
      v5 = *j;
      if ( *j >= 97 && v5 <= 122 )
        *j = v5 - 32;
    }
    v3 = strstr(Buffer, Filename);
  }
  if ( !v3 )
    goto LABEL_29;
  v6 = strchr(v3, 44);
  if ( !v6 )
    goto LABEL_29;
  v7 = v6 + 1;
  v8 = v7;
  while ( *v8 )
  {
    if ( *v8 == 59 )
      *v8 = 0;
    else
      ++v8;
  }
  result = strtol(v7, 0, 10);
  if ( result != 2 && result != 3 && result != 1 )
  {
LABEL_29:
    sub_4026DB((int)v12);
    return 3 - (v12[0] < 6u);
  }
  return result;
}

//----- (00402850) --------------------------------------------------------
int __cdecl sub_402850(int a1)
{
  int v1; // eax
  int *v2; // eax

  hHeap = HeapCreate(a1 == 0, 0x1000u, 0);
  if ( !hHeap )
    return 0;
  v1 = sub_402708();
  dword_409988 = v1;
  if ( v1 == 3 )
  {
    v2 = (int *)__sbh_heap_init(1016);
  }
  else
  {
    if ( v1 != 2 )
      return 1;
    v2 = sub_403753();
  }
  if ( !v2 )
  {
    HeapDestroy(hHeap);
    return 0;
  }
  return 1;
}
// 402C0C: using guessed type _DWORD __cdecl __sbh_heap_init(_DWORD);
// 409988: using guessed type int dword_409988;

//----- (00402C7F) --------------------------------------------------------
_DWORD *__cdecl sub_402C7F(_DWORD *a1, int a2)
{
  _DWORD *result; // eax
  int *v3; // esi
  unsigned int v4; // edi
  int v5; // ecx
  char *v6; // ebx
  unsigned int v7; // edx
  _BYTE *v8; // ecx
  unsigned int v9; // ebx
  bool v10; // zf
  _BYTE *v11; // ecx
  unsigned int v12; // ebx
  unsigned int v13; // edx
  unsigned int v14; // ebx
  unsigned int v15; // esi
  unsigned int v16; // esi
  _DWORD *v17; // ecx
  LPVOID *v18; // eax
  _DWORD *v19; // [esp+Ch] [ebp-10h]
  int v20; // [esp+10h] [ebp-Ch]
  int v21; // [esp+14h] [ebp-8h]
  int v22; // [esp+18h] [ebp-4h]
  char *v23; // [esp+28h] [ebp+Ch]
  int *v24; // [esp+28h] [ebp+Ch]
  char v25; // [esp+2Bh] [ebp+Fh]

  result = (_DWORD *)a1[4];
  v3 = (int *)(a2 - 4);
  v4 = (unsigned int)(a2 - a1[3]) >> 15;
  v19 = &result[129 * v4 + 81];
  v5 = *(_DWORD *)(a2 - 4) - 1;
  v22 = v5;
  if ( (v5 & 1) == 0 )
  {
    v6 = (char *)v3 + v5;
    v20 = *(int *)((char *)v3 + v5);
    v21 = *(_DWORD *)(a2 - 8);
    v23 = (char *)v3 + v5;
    if ( (v20 & 1) == 0 )
    {
      v7 = (v20 >> 4) - 1;
      if ( v7 > 0x3F )
        v7 = 63;
      if ( *((_DWORD *)v6 + 1) == *((_DWORD *)v6 + 2) )
      {
        if ( v7 >= 0x20 )
        {
          v11 = (char *)result + v7 + 4;
          v12 = ~(0x80000000 >> (v7 - 32));
          result[v4 + 49] &= v12;
          v10 = (*v11)-- == 1;
          if ( v10 )
            a1[1] &= v12;
        }
        else
        {
          v8 = (char *)result + v7 + 4;
          v9 = ~(0x80000000 >> v7);
          result[v4 + 17] &= v9;
          v10 = (*v8)-- == 1;
          if ( v10 )
            *a1 &= v9;
        }
        v5 = v22;
        v6 = v23;
      }
      v5 += v20;
      *(_DWORD *)(*((_DWORD *)v6 + 2) + 4) = *((_DWORD *)v6 + 1);
      v22 = v5;
      *(_DWORD *)(*((_DWORD *)v23 + 1) + 8) = *((_DWORD *)v23 + 2);
    }
    v13 = (v5 >> 4) - 1;
    if ( v13 > 0x3F )
      v13 = 63;
    if ( (v21 & 1) != 0 )
    {
      v14 = (unsigned int)a1;
    }
    else
    {
      v24 = (int *)((char *)v3 - v21);
      v14 = (v21 >> 4) - 1;
      if ( v14 > 0x3F )
        v14 = 63;
      v22 = v21 + v5;
      v13 = ((v21 + v5) >> 4) - 1;
      if ( v13 > 0x3F )
        v13 = 63;
      if ( v14 != v13 )
      {
        if ( v24[1] == v24[2] )
        {
          if ( v14 >= 0x20 )
          {
            v16 = ~(0x80000000 >> (v14 - 32));
            result[v4 + 49] &= v16;
            v10 = (*((_BYTE *)result + v14 + 4))-- == 1;
            if ( v10 )
              a1[1] &= v16;
          }
          else
          {
            v15 = ~(0x80000000 >> v14);
            result[v4 + 17] &= v15;
            v10 = (*((_BYTE *)result + v14 + 4))-- == 1;
            if ( v10 )
              *a1 &= v15;
          }
        }
        *(_DWORD *)(v24[2] + 4) = v24[1];
        *(_DWORD *)(v24[1] + 8) = v24[2];
      }
      v3 = v24;
    }
    if ( (v21 & 1) != 0 || v14 != v13 )
    {
      v17 = &v19[2 * v13];
      v3[1] = v17[1];
      v3[2] = (int)v17;
      v17[1] = v3;
      *(_DWORD *)(v3[1] + 8) = v3;
      if ( v3[1] == v3[2] )
      {
        v25 = *((_BYTE *)result + v13 + 4);
        *((_BYTE *)result + v13 + 4) = v25 + 1;
        if ( v13 >= 0x20 )
        {
          if ( !v25 )
            a1[1] |= 0x80000000 >> (v13 - 32);
          result[v4 + 49] |= 0x80000000 >> (v13 - 32);
        }
        else
        {
          if ( !v25 )
            *a1 |= 0x80000000 >> v13;
          result[v4 + 17] |= 0x80000000 >> v13;
        }
      }
    }
    *v3 = v22;
    *(int *)((char *)v3 + v22 - 4) = v22;
    result += 129 * v4 + 81;
    v10 = (*v19)-- == 1;
    if ( v10 )
    {
      if ( dword_409974 )
      {
        VirtualFree((LPVOID)(*((_DWORD *)dword_409974 + 3) + (dword_40996C << 15)), 0x8000u, 0x4000u);
        *((_DWORD *)dword_409974 + 2) |= 0x80000000 >> dword_40996C;
        *(_DWORD *)(*((_DWORD *)dword_409974 + 4) + 4 * dword_40996C + 196) = 0;
        --*(_BYTE *)(*((_DWORD *)dword_409974 + 4) + 67);
        v18 = (LPVOID *)dword_409974;
        if ( !*(_BYTE *)(*((_DWORD *)dword_409974 + 4) + 67) )
        {
          *((_DWORD *)dword_409974 + 1) &= ~1u;
          v18 = (LPVOID *)dword_409974;
        }
        if ( v18[2] == (LPVOID)-1 )
        {
          VirtualFree(v18[3], 0, 0x8000u);
          HeapFree(hHeap, 0, *((LPVOID *)dword_409974 + 4));
          memcpy_0(
            dword_409974,
            (char *)dword_409974 + 20,
            (size_t)lpMem + 20 * dword_409978 - (_DWORD)dword_409974 - 20);
          --dword_409978;
          if ( a1 > dword_409974 )
            a1 -= 5;
          dword_409970 = (int)lpMem;
        }
      }
      dword_40996C = v4;
      dword_409974 = a1;
      return a1;
    }
  }
  return result;
}
// 40996C: using guessed type int dword_40996C;
// 409970: using guessed type int dword_409970;
// 409978: using guessed type int dword_409978;

//----- (00403753) --------------------------------------------------------
int *sub_403753()
{
  int *v0; // esi
  _DWORD *v1; // eax
  _DWORD *v2; // edi
  int *v3; // eax
  int v4; // ebp
  int v5; // edx

  if ( dword_407218 == -1 )
  {
    v0 = (int *)&off_407208;
  }
  else
  {
    v0 = (int *)HeapAlloc(hHeap, 0, 0x2020u);
    if ( !v0 )
      return 0;
  }
  v1 = VirtualAlloc(0, 0x400000u, 0x2000u, 4u);
  v2 = v1;
  if ( !v1 )
  {
LABEL_19:
    if ( v0 != (int *)&off_407208 )
      HeapFree(hHeap, 0, v0);
    return 0;
  }
  if ( !VirtualAlloc(v1, 0x10000u, 0x1000u, 4u) )
  {
    VirtualFree(v2, 0, 0x8000u);
    goto LABEL_19;
  }
  if ( v0 == (int *)&off_407208 )
  {
    if ( !off_407208 )
      off_407208 = &off_407208;
    if ( !off_40720C )
      off_40720C = &off_407208;
  }
  else
  {
    *v0 = (int)&off_407208;
    v0[1] = (int)off_40720C;
    off_40720C = v0;
    *(_DWORD *)v0[1] = v0;
  }
  v0[5] = (int)(v2 + 0x100000);
  v3 = v0 + 6;
  v0[3] = (int)(v0 + 38);
  v0[4] = (int)v2;
  v0[2] = (int)(v0 + 6);
  v4 = 0;
  do
  {
    v5 = v4++ >= 16 ? -1 : 240;
    *v3 = v5;
    v3[1] = 241;
    v3 += 2;
  }
  while ( v4 < 1024 );
  memset(v2, 0, 0x10000u);
  while ( (unsigned int)v2 < v0[4] + 0x10000 )
  {
    *((_BYTE *)v2 + 248) = -1;
    *v2 = v2 + 2;
    v2[1] = 240;
    v2 += 1024;
  }
  return v0;
}
// 407208: using guessed type _UNKNOWN *off_407208;
// 407218: using guessed type int dword_407218;

//----- (00403897) --------------------------------------------------------
_UNKNOWN **__cdecl sub_403897(LPVOID *lpMem)
{
  _UNKNOWN **result; // eax

  result = (_UNKNOWN **)VirtualFree(lpMem[4], 0, 0x8000u);
  if ( off_409228 == (_UNKNOWN **)lpMem )
  {
    result = (_UNKNOWN **)lpMem[1];
    off_409228 = result;
  }
  if ( lpMem == (LPVOID *)&off_407208 )
  {
    dword_407218 = -1;
  }
  else
  {
    *(_DWORD *)lpMem[1] = *lpMem;
    *((_DWORD *)*lpMem + 1) = lpMem[1];
    return (_UNKNOWN **)HeapFree(hHeap, 0, lpMem);
  }
  return result;
}
// 407208: using guessed type _UNKNOWN *off_407208;
// 407218: using guessed type int dword_407218;
// 409228: using guessed type _UNKNOWN **off_409228;

//----- (004038ED) --------------------------------------------------------
void __cdecl sub_4038ED(int a1)
{
  _DWORD *v1; // esi
  _DWORD *v2; // edi
  int i; // ebx
  unsigned int v4; // eax
  _DWORD *v5; // ecx
  _DWORD *v6; // eax
  int j; // edx
  int v8; // [esp+Ch] [ebp-4h]

  v1 = off_40720C;
  do
  {
    if ( v1[4] != -1 )
    {
      v8 = 0;
      v2 = v1 + 2052;
      for ( i = 4190208; i >= 0; i -= 4096 )
      {
        if ( *v2 == 240 && VirtualFree((LPVOID)(v1[4] + i), 0x1000u, 0x4000u) )
        {
          *v2 = -1;
          --dword_409704;
          v4 = v1[3];
          if ( !v4 || v4 > (unsigned int)v2 )
            v1[3] = v2;
          ++v8;
          if ( !--a1 )
            break;
        }
        v2 -= 2;
      }
      v5 = v1;
      v1 = (_DWORD *)v1[1];
      if ( v8 && v5[6] == -1 )
      {
        v6 = v5 + 8;
        for ( j = 1; j < 1024; ++j )
        {
          if ( *v6 != -1 )
            break;
          v6 += 2;
        }
        if ( j == 1024 )
          sub_403897((LPVOID *)v5);
      }
    }
  }
  while ( v1 != off_40720C && a1 > 0 );
}
// 409704: using guessed type int dword_409704;

//----- (004039AF) --------------------------------------------------------
unsigned int __cdecl sub_4039AF(unsigned int a1, _DWORD *a2, unsigned int *a3)
{
  _UNKNOWN **v3; // ecx

  v3 = &off_407208;
  while ( a1 <= (unsigned int)v3[4] || a1 >= (unsigned int)v3[5] )
  {
    v3 = (_UNKNOWN **)*v3;
    if ( v3 == &off_407208 )
      return 0;
  }
  if ( (a1 & 0xF) == 0 && (a1 & 0xFFF) >= 0x100 )
  {
    *a2 = v3;
    *a3 = a1 & 0xFFFFF000;
    return ((int)(a1 - (a1 & 0xFFFFF000) - 256) >> 4) + (a1 & 0xFFFFF000) + 8;
  }
  return 0;
}
// 407208: using guessed type _UNKNOWN *off_407208;

//----- (00403A06) --------------------------------------------------------
void __cdecl sub_403A06(int a1, int a2, _BYTE *a3)
{
  _DWORD *v3; // eax
  bool v4; // zf

  v3 = (_DWORD *)(a1 + 8 * ((a2 - *(_DWORD *)(a1 + 16)) >> 12) + 24);
  *v3 += (unsigned __int8)*a3;
  *a3 = 0;
  v4 = *v3 == 240;
  v3[1] = 241;
  if ( v4 && ++dword_409704 == 32 )
    sub_4038ED(16);
}
// 409704: using guessed type int dword_409704;

//----- (00403A4B) --------------------------------------------------------
int __cdecl sub_403A4B(unsigned int a1)
{
  _UNKNOWN **v1; // esi
  void *v2; // edx
  unsigned int *v3; // edi
  int v4; // eax
  unsigned int v5; // ebx
  int result; // eax
  char *v7; // edi
  _DWORD *v8; // ebx
  _DWORD *v9; // eax
  _DWORD *i; // esi
  _DWORD *v11; // ecx
  _DWORD *v12; // eax
  _UNKNOWN **v13; // eax
  bool v14; // cf
  int *v15; // eax
  int v16; // ecx
  unsigned int Val; // [esp+Ch] [ebp-8h]
  int v18; // [esp+10h] [ebp-4h]
  int v19; // [esp+10h] [ebp-4h]
  int v20; // [esp+10h] [ebp-4h]

  v1 = off_409228;
  do
  {
    v2 = v1[4];
    if ( v2 == (void *)-1 )
    {
      v5 = a1;
    }
    else
    {
      v3 = (unsigned int *)v1[2];
      v4 = (int)v2 + 4096 * (((char *)v3 - (char *)v1 - 24) >> 3);
      v18 = v4;
      if ( v3 < (unsigned int *)v1 + 2054 )
      {
        while ( 1 )
        {
          v5 = a1;
          if ( (int)*v3 >= (int)a1 && v3[1] > a1 )
          {
            result = sub_403C53(v4, *v3, a1);
            if ( result )
            {
LABEL_21:
              off_409228 = v1;
              *v3 -= v5;
              v1[2] = v3;
              return result;
            }
            v4 = v18;
            v3[1] = a1;
          }
          v3 += 2;
          v4 += 4096;
          v18 = v4;
          if ( v3 >= (unsigned int *)v1 + 2054 )
            goto LABEL_11;
        }
      }
      v5 = a1;
LABEL_11:
      v3 = (unsigned int *)(v1 + 6);
      Val = (unsigned int)v1[2];
      v19 = (int)v1[4];
      if ( (unsigned int)(v1 + 6) < Val )
      {
        do
        {
          if ( (int)*v3 >= (int)v5 && v3[1] > v5 )
          {
            result = sub_403C53(v19, *v3, v5);
            if ( result )
              goto LABEL_21;
            v3[1] = v5;
          }
          v19 += 4096;
          v3 += 2;
        }
        while ( (unsigned int)v3 < Val );
      }
    }
    v1 = (_UNKNOWN **)*v1;
  }
  while ( v1 != off_409228 );
  v7 = (char *)&off_407208;
  while ( *((_DWORD *)v7 + 4) == -1 || !*((_DWORD *)v7 + 3) )
  {
    v7 = *(char **)v7;
    if ( v7 == (char *)&off_407208 )
    {
      v15 = sub_403753();
      if ( v15 )
      {
        v16 = v15[4];
        *(_BYTE *)(v16 + 8) = v5;
        off_409228 = (_UNKNOWN **)v15;
        *(_DWORD *)v16 = v16 + v5 + 8;
        *(_DWORD *)(v16 + 4) = 240 - v5;
        v15[6] -= (unsigned __int8)v5;
        return v16 + 256;
      }
      return 0;
    }
  }
  v8 = (_DWORD *)*((_DWORD *)v7 + 3);
  v20 = 0;
  v9 = v8;
  for ( i = (_DWORD *)(*((_DWORD *)v7 + 4) + (((char *)v8 - v7 - 24) >> 3 << 12)); *v9 == -1; ++v20 )
  {
    if ( v20 >= 16 )
      break;
    v9 += 2;
  }
  if ( VirtualAlloc(i, v20 << 12, 0x1000u, 4u) != i )
    return 0;
  v11 = v8;
  if ( v20 > 0 )
  {
    v12 = i + 1;
    do
    {
      *((_BYTE *)v12 + 244) = -1;
      *(v12 - 1) = v12 + 1;
      *v12 = 240;
      *v11 = 240;
      v11[1] = 241;
      v12 += 1024;
      v11 += 2;
      --v20;
    }
    while ( v20 );
  }
  off_409228 = (_UNKNOWN **)v7;
  v13 = (_UNKNOWN **)(v7 + 8216);
  while ( 1 )
  {
    v14 = v11 < v13;
    if ( v11 >= v13 )
      break;
    if ( *v11 == -1 )
    {
      v14 = v11 < v13;
      break;
    }
    v11 += 2;
  }
  *((_DWORD *)v7 + 3) = v14 ? v11 : 0;
  *((_BYTE *)i + 8) = a1;
  *((_DWORD *)v7 + 2) = v8;
  *v8 -= a1;
  i[1] -= a1;
  *i = (char *)i + a1 + 8;
  return (int)(i + 64);
}
// 407208: using guessed type _UNKNOWN *off_407208;
// 409228: using guessed type _UNKNOWN **off_409228;

//----- (00403C53) --------------------------------------------------------
int __cdecl sub_403C53(int a1, unsigned int a2, unsigned int a3)
{
  unsigned int v4; // esi
  _BYTE *v5; // edi
  unsigned int v6; // ebx
  _BYTE *v7; // eax
  _BYTE *v8; // eax
  _BYTE *v9; // esi
  _BYTE *v10; // ebx
  unsigned int v11; // esi
  _BYTE *v12; // esi
  _BYTE *v13; // ebx
  unsigned int v14; // eax
  _BYTE *v16; // [esp+Ch] [ebp-4h]
  unsigned int v17; // [esp+18h] [ebp+8h]

  v4 = *(_DWORD *)(a1 + 4);
  v5 = *(_BYTE **)a1;
  v6 = a1 + 248;
  v16 = *(_BYTE **)a1;
  v7 = *(_BYTE **)a1;
  v17 = a1 + 248;
  if ( v4 >= a3 )
  {
    *v5 = a3;
    if ( (unsigned int)&v5[a3] >= v6 )
    {
      *(_DWORD *)(a1 + 4) = 0;
      *(_DWORD *)a1 = a1 + 8;
    }
    else
    {
      *(_DWORD *)a1 += a3;
      *(_DWORD *)(a1 + 4) -= a3;
    }
    v8 = v5 + 8;
    return 16 * (_DWORD)v8 - 15 * a1;
  }
  v9 = &v5[v4];
  if ( *v9 )
    v7 = v9;
  if ( (unsigned int)&v7[a3] >= v6 )
  {
LABEL_20:
    v12 = (_BYTE *)(a1 + 8);
    while ( v12 < v5 && (unsigned int)&v12[a3] < v17 )
    {
      if ( *v12 )
      {
        v12 += (unsigned __int8)*v12;
      }
      else
      {
        v13 = v12 + 1;
        v14 = 1;
        while ( !*v13 )
        {
          ++v13;
          ++v14;
        }
        if ( v14 >= a3 )
        {
          if ( (unsigned int)&v12[a3] >= v17 )
          {
            *(_DWORD *)(a1 + 4) = 0;
            *(_DWORD *)a1 = a1 + 8;
          }
          else
          {
            *(_DWORD *)a1 = &v12[a3];
            *(_DWORD *)(a1 + 4) = v14 - a3;
          }
          *v12 = a3;
          v8 = v12 + 8;
          return 16 * (_DWORD)v8 - 15 * a1;
        }
        a2 -= v14;
        if ( a2 < a3 )
          return 0;
        v12 = v13;
      }
    }
    return 0;
  }
  while ( *v7 )
  {
    v7 += (unsigned __int8)*v7;
LABEL_19:
    if ( (unsigned int)&v7[a3] >= v17 )
      goto LABEL_20;
  }
  v10 = v7 + 1;
  v11 = 1;
  while ( !*v10 )
  {
    ++v10;
    ++v11;
  }
  if ( v11 < a3 )
  {
    if ( v7 == v16 )
    {
      *(_DWORD *)(a1 + 4) = v11;
    }
    else
    {
      a2 -= v11;
      if ( a2 < a3 )
        return 0;
    }
    v5 = v16;
    v7 = v10;
    goto LABEL_19;
  }
  if ( (unsigned int)&v7[a3] >= v17 )
  {
    *(_DWORD *)(a1 + 4) = 0;
    *(_DWORD *)a1 = a1 + 8;
  }
  else
  {
    *(_DWORD *)a1 = &v7[a3];
    *(_DWORD *)(a1 + 4) = v11 - a3;
  }
  *v7 = a3;
  v8 = v7 + 8;
  return 16 * (_DWORD)v8 - 15 * a1;
}

//----- (00403D77) --------------------------------------------------------
int __cdecl sub_403D77(int a1, _DWORD *a2, _BYTE *a3, unsigned int a4)
{
  unsigned int v4; // ecx
  _DWORD *v5; // edi
  _BYTE *v6; // esi
  _BYTE *i; // eax
  bool v8; // zf
  int v9; // eax
  int v11; // [esp+Ch] [ebp-4h]

  v4 = (unsigned __int8)*a3;
  v11 = 0;
  v5 = (_DWORD *)(a1 + 8 * (((int)a2 - *(_DWORD *)(a1 + 16)) >> 12) + 24);
  if ( v4 > a4 )
  {
    *a3 = a4;
    *v5 += v4 - a4;
    v5[1] = 241;
    return 1;
  }
  if ( v4 < a4 )
  {
    v6 = &a3[a4];
    if ( a2 + 62 >= (_DWORD *)&a3[a4] )
    {
      for ( i = &a3[v4]; ; ++i )
      {
        v8 = i == v6;
        if ( i >= v6 )
          break;
        if ( *i )
        {
          v8 = i == v6;
          break;
        }
      }
      if ( v8 )
      {
        *a3 = a4;
        if ( (unsigned int)a3 <= *a2 && (unsigned int)v6 > *a2 )
        {
          if ( v6 >= (_BYTE *)a2 + 248 )
          {
            a2[1] = 0;
            *a2 = a2 + 2;
          }
          else
          {
            v9 = 0;
            *a2 = v6;
            if ( !*v6 )
            {
              do
                ++v9;
              while ( !v6[v9] );
            }
            a2[1] = v9;
          }
        }
        *v5 += v4 - a4;
        return 1;
      }
    }
  }
  return v11;
}

// nfuncs=99 queued=29 decompiled=29 lumina nreq=0 worse=0 better=0
// ALL OK, 29 function(s) have been successfully decompiled

